### ISSUE TITLE
Registry Uninstall Issue

### ISSUE THREAD

**Issue by drkludge** [Esri/arcgis-cookbook#101]
I am not convinced that the uninstall part of the cookbooks work correctly.  I had enough problems with the scripts per #99 that I switched to the 10.5.1 builder install method.  I ran the Chef uninstall scripts, however, there were still registry entries that influenced the builder install.  I wound up with the same split code across C: and D: drives.  I found a working directory that builder created.  I was able to execute
`C:\ProgramData\ArcGISBuilder10.5.1\Builder\Server\setup.exe`.  I selected the uninstall option.  This uninstall option completely removed registry entries and folders where manual methods of removing the registry entries and folders failed.

Note to Google searches:  Builder provided this message and died, "The following must be resolved to run this setup program: ArcGIS Server 10.5.1 needs to be removed."  Builder installs out of 
 `C:\ProgramData\ArcGISBuilder10.5.1` even if you have an ISO mounted elsewhere.  The reason I bring up this builder error message is that all the install logs are in that directory in addition to the resolution to the error noted above.

Just for fun I ran the other four setup programs.  Either I cleaned up the data before a reinstall attempt or those setup programs did not provide a cleanup option.  `Server\Setup.exe` seems to be that program.
```
DataStore\Setup.exe
Portal\Setup.exe
PortalAdaptor\Setup.exe
Server\Setup.exe
ServerAdaptor\Setup.exe
```

I hope this helps.

![error](https://user-images.githubusercontent.com/1669057/28851012-b5a2f488-76d4-11e7-9ea3-40c22cbf04f0.png)

**Comment by pbobov** [comment]
ArcGIS Enterprise Builder is not supported by ArcGIS Chef cookbooks.
