### ISSUE TITLE
If it ok to update an expired SSL Certificate using Chef?

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#107]
Hi Pavel:
Our SSL domain Certificate just expired.  We started to update certificates by hand for IIS, Portal (via portaladmin) and Server (via server/admin).

Can we just update by modifying the Chef json to point at the new certificate and password?  
Would we need to define a cert_alias? 
I noticed that our DEV Portal json used a cert_alias but I hadn't done that in the Test and Prod portals.  
The default cert_alias is the FQDN of the host, correct?  
So a new cert would probably need a different cert_alias in order to install without a conflict?
My SSL Cert knowledge is limited...

I tried doing this on our 10.4.1 Test Portal and it looks like it ran ok but thought I'd verify if this is an appropriate use of Chef
Appreciate all your work!

**Comment by pbobov** [comment]
Hi Paul,

The certificate on IIS is updated if node['iis']['replace_https_binding'] attribute is set to true.

Chef does not upload/update SSL certificates on server and portal if the cert aliases of the installed certificates are equal to the aliases specified in the JSON file. The default alias for server is node['arcgis']['server']['domain_name'], for portal is node['arcgis']['portal']['domain_name'], and the default domain_name is FQDN of the host. So yes, you would need to change cert_alias attribute for server and portal.

Regards,
Pavel

**Comment by pkdavidson** [comment]
Thanks Pavel....
I've run Chef with server, portal, etc... running before but it just occurred to me, should I be turning off those services before running Chef?

**Comment by pbobov** [comment]
Stopping server and portal windows services is not required to update the SSL settings. There services must be running for the update to work (they will be started if they are in stopped state).

**Comment by pkdavidson** [comment]
Once again, you've saved me a lot of work!
 Setting the 'iis']['replace_https_binding'] attribute to true was useful.
I think it was renaming the cert_alias did the trick in some cases.
