### ISSUE TITLE
Change appServerMaxHeapSize/webServerMaxHeapSize through attributes\server.rb?

### ISSUE THREAD

**Issue by mhkok** [Esri/arcgis-cookbook#108]
Would it be possible to change the appServerMaxHeapSize/webServerMaxHeapSize via the attributes\server.rb file through the ArcGIS server REST api?

**Comment by cameronkroeker** [comment]
No longer applicable in 10.6 or later.

https://developers.arcgis.com/rest/enterprise-administration/server/editmachine.htm

However, can adjust Soc HEAP size:

node['arcgis']['server']['soc_max_heap_size'] = SOC maximum heap size in megabytes. Default value is 64.
