### ISSUE TITLE
Argument error

### ISSUE THREAD

**Issue by tysontaylor** [Esri/arcgis-cookbook#109]
I am trying to run this very basic .json file, getting  an argument error.
Does anyone have any ideas?   Thanks

I've testing the json in JSONLint (valid json)

{
	"arcgis": {
		"run_as_user": "XXX",
		"run_as_password": "XXX",
		"version": "10.5",
		"configure_windows_fireall":false
	},
	"server": {
		"admin_username": "XXX",
		"admin_password": "XXX",
		"setup":"\\\\xxx\\GISData\\Software\\ESRI\\ArcGIS10_5_1\\Server\\ArcGIS_Server_Windows_1051_156124\\ArcGISServer\\Setup.exe",
		"authorization_file":"\\\\xxx\\GIS105Data\\AGS_Licenses\\dev_dv028_10_5_1_ArcGISGISServerAdvancedWorkgroup_ArcGISServer_543916.prvc"
	},
	"run_list": [
		"recipe[arcgis-enterprise::system]",
		"recipe[esri-iis]",
		"recipe[arcgis-enterprise::server]"
	]
}
-----------------------------------------------------------------
Getting Error
Generated at 2017-08-24 12:11:04 -0600
Chef::Exceptions::PrivateKeyMissing: I cannot read C:\chef\validation.pem, which you told me to use to sign requests!
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http/authenticator.rb:86:in `rescue in load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http/authenticator.rb:76:in `load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http/authenticator.rb:40:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:98:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:98:in `block in initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:97:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/server_api.rb:36:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:150:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:150:in `http_api'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:96:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:87:in `create_or_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:620:in `register'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:260:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:243:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'

>>>> Caused by Errno::ENOENT: No such file or directory @ rb_sysopen - C:\chef\validation.pem
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http/authenticator.rb:77:in `read'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http/authenticator.rb:77:in `load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http/authenticator.rb:40:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:98:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:98:in `block in initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/http.rb:97:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/server_api.rb:36:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:150:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:150:in `http_api'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:96:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:87:in `create_or_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/api_client/registration.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:620:in `register'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:260:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:243:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'

-----------------------------------------------------------------------------------------------------------------
Recipe: arcgis-enterprise::system
  * chef_gem[multipart-post] action install (up to date)
  ==============================================================================
==
  Recipe Compile Error in c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterp
rise/recipes/server.rb
  ==============================================================================
==

  ArgumentError
  -------------
  You must supply a name when declaring a file resource

  Platform:
  ---------
  x64-mingw32

**Comment by pbobov** [comment]
How do you run the .json file?

This way
```chef-solo -j simple.json ```
or
```chef-client -z -j simple.json ```
?

Chef-solo should not care about C:\chef\validation.pem.

**Comment by nshampur** [comment]
if I wager a bet, it is the network file path. I'd try double backward slashes for each path seperator

**Comment by tysontaylor** [comment]
chef-solo -j c:\chef\roles\AGS_DEV_Installs.json

**Comment by tysontaylor** [comment]
I have these files out on a fileshare this is the correct paths in .json for a unc path right?

"setup":"\\\\<share>\\GISData\\Software\\ESRI\\ArcGIS10_5_1\\Server\\ArcGIS_Server_Windows_1051_156124\\ArcGISServer\\Setup.exe",
"authorization_file":"\\\\<share>\\GIS105Data\\AGS_Licenses\\dev_dv028_10_5_1_ArcGISGISServerAdvancedWorkgroup_ArcGISServer_543916.prvc"

**Comment by nshampur** [comment]
as a point of sanity.. could u try a local file path on the machine itself

**Comment by tysontaylor** [comment]
I’ve tried that as well.  Still got the same error.

**Comment by pbobov** [comment]
Try to delete C:\chef\cache folder (or better delete everything from C:\chef folder except for cookbooks and .json files) and run chef again.

**Comment by tysontaylor** [comment]
deleted folders still same results error.

**Comment by tysontaylor** [comment]
this has been resolved.   Thanks pbobov,   For fixing it.  appreciate the help..
