### ISSUE TITLE
Error when running chef-solo -j C:\chef\node-windows_neu.json

### ISSUE THREAD

**Issue by meinspieler** [Esri/arcgis-cookbook#11]
I'm testing the ArcGIS Cookbook with Win8.1 and Server 2012 R2 and running into this error: [2015-08-04T14:02:07+02:00] FATAL: Chef::Exceptions::Win32APIError: user[ArcGISService](arcgis::system line 21) had an error: Chef::Exceptions::Win32APIError: Received unknown error code (2220)

I think that's the important part of the message.

Further, I'm totally new with Chef and have no idea how I could handle this error? Maybe something should be changed int the system.rb... or maybe some other small and basic adjustment... 

If you need more Information, please let me know!

Thanks and with best regards,

Marko

**Comment by pbobov** [comment]
Thanks for submitting the issue!

The error message is not very descriptive. Could you share the whole chef-run log and the node.json file (without real passwords)?

**Comment by meinspieler** [comment]
Hi Pavel!

Attached I send you the chef-run log (error_cookbook_commandshell.txt) and my node.json file (node-windows_neu_Ser2012R2.json).

Meanwhile I was able to run the chef cookbook on Windows Server 2012 R2 system. What I made:
- changed both ['arcgis'] nodes to ['ArcGISService'] in recipes/system.rb and saved
- run node.json file with an error
- changed nodes above back to ['arcgis'] in recipes/system.rb and saved
- run node.jsan file again
- I got no errors and the installation run without troubles :-) (only the desktop installation was not ok, because I made some mistake, when I was setting esri_license_host...)

This behavior was very strange for me!!! Do you have an explanation for that?

I was also able to run the chef cookbook on my Windows 8.1 testsystem (same procedure like listed above). But here I got another error... There went something wrong in the IIS-Feature configuration... I atteched chef log (error_iis.txt) and node.json file (node-windows_neu_win81.json), too.
Another questions from my side is, if I want to disable the https, what would be the easiest way? I comment out the "Configure HTTPS Binding"-block in the recipe/iis.rb-file (iis_rb_https.png). Is that the right way?
And if I want to set an esri_license_host, I have to remove the ['seat_preference')-node and fill in the node ['esri_license_host'] (see attached node-windows_neu_win81.json-file). Is that correct?

Thank you and with best regards,

Marko

Von: Pavel Bobov [mailto:notifications@github.com]
Gesendet: Dienstag, 04. August 2015 18:02
An: Esri/arcgis-cookbook <arcgis-cookbook@noreply.github.com>
Cc: Einspieler Marko <m.einspieler@mysynergis.com>
Betreff: Re: [arcgis-cookbook] Error when running chef-solo -j C:\chef\node-windows_neu.json (#11)


Thanks for submitting the issue!

The error message is not very descriptive. Could you share the whole chef-run log and the node.json file (without real passwords)?

—
Reply to this email directly or view it on GitHub<https://github.com/Esri/arcgis-cookbook/issues/11#issuecomment-127659332>.

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>chef-solo -j C:\chef\node-windows_neu.json
[2015-08-05T10:41:16+02:00] WARN: *****************************************
[2015-08-05T10:41:16+02:00] WARN: Did not find config file: C:\chef\solo.rb, using command line options.
[2015-08-05T10:41:16+02:00] WARN: *****************************************
Starting Chef Client, version 12.4.1
Compiling Cookbooks...
[2015-08-05T10:41:40+02:00] WARN: You are overriding windows_package on {:os=>"windows"} with Chef::Resource::WindowsCookbook
Package: used to be Chef::Resource::WindowsPackage. Use override: true if this is what you intended.
[2015-08-05T10:41:41+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
Converging 14 resources
Recipe: arcgis::system
  * user[ArcGISService] action create

    ================================================================================
    Error executing action `create` on resource 'user[ArcGISService]'
    ================================================================================

    Chef::Exceptions::Win32APIError
    -------------------------------
    Received unknown error code (2220)
    ---- Begin Win32 API output ----
    Net Api Error Code: 2220
    Net Api Error Message: Received unknown error code (2220)
    ---- End Win32 API output ----

    Resource Declaration:
    ---------------------
    # In C:\chef\cookbooks\arcgis\recipes\system.rb

     21:   user node['arcgis']['run_as_user'] do
     22:     comment 'ArcGIS user account'
     23:     supports :manage_home => true
     24:     password node['arcgis']['run_as_password']
     25:     action :create
     26:   end
     27:

    Compiled Resource:
    ------------------
    # Declared in C:\chef\cookbooks\arcgis\recipes\system.rb:21:in `from_file'

    user("ArcGISService") do
      action [:create]
      supports {:manage_home=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      username "ArcGISService"
      comment "ArcGIS user account"
      password "**********"
      iterations 27855
      declared_type :user
      cookbook_name :arcgis
      recipe_name "system"
    end


Running handlers:
[2015-08-05T10:41:41+02:00] ERROR: Running exception handlers
Running handlers complete
[2015-08-05T10:41:41+02:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 24.743057 seconds
[2015-08-05T10:41:41+02:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-08-05T10:41:41+02:00] FATAL: Chef::Exceptions::Win32APIError: user[ArcGISService] (arcgis::system line 21) had an error
: Chef::Exceptions::Win32APIError: Received unknown error code (2220)
---- Begin Win32 API output ----
Net Api Error Code: 2220
Net Api Error Message: Received unknown error code (2220)
---- End Win32 API output ----


C:\Windows\system32>
C:\Windows\system32>chef-solo -j C:\chef\node-windows_neu.json
[2015-08-05T10:49:14+02:00] WARN: *****************************************
[2015-08-05T10:49:14+02:00] WARN: Did not find config file: C:\chef\solo.rb, using command line options.
[2015-08-05T10:49:14+02:00] WARN: *****************************************
Starting Chef Client, version 12.4.1
Compiling Cookbooks...
[2015-08-05T10:49:25+02:00] WARN: You are overriding windows_package on {:os=>"windows"} with Chef::Resource::WindowsCookbook
Package: used to be Chef::Resource::WindowsPackage. Use override: true if this is what you intended.
[2015-08-05T10:49:25+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
Converging 14 resources
Recipe: arcgis::system
  * user[ArcGISService] action create (up to date)
  * windows_feature[IIS-WebServerRole] action install

Recipe: arcgis::iis
  * arcgis_iis[Enable IIS Features] action enable[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (Window
sFeatureDism) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource,
 action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Cloning resource attributes for windows_feature[IIS-WebServerRole] from prior resource (CHE
F-3694)
[2015-08-05T10:50:30+02:00] WARN: Previous windows_feature[IIS-WebServerRole]: C:\chef\cookbooks\arcgis\recipes\system.rb:66:
in `block in from_file'
[2015-08-05T10:50:30+02:00] WARN: Current  windows_feature[IIS-WebServerRole]: C:\chef\cookbooks\arcgis\providers\iis.rb:61:i
n `block (2 levels) in class_from_file'
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-05T10:50:30+02:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in
Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.


  * windows_feature[IIS-WebServerRole] action install

  * windows_feature[IIS-ISAPIFilter] action install

  * windows_feature[IIS-ISAPIExtensions] action install

  * windows_feature[NetFx4Extended-ASPNET45] action install

  * windows_feature[IIS-NetFxExtensibility45] action install

  * windows_feature[IIS-ASPNET45] action install

  * windows_feature[IIS-WebServerManagementTools] action install

  * windows_feature[IIS-ManagementConsole] action install

  * windows_feature[IIS-ManagementService] action install

  * windows_feature[IIS-IIS6ManagementCompatibility] action install

  * windows_feature[IIS-ManagementScriptingTools] action install

  * windows_feature[IIS-StaticContent] action install

  * windows_feature[IIS-BasicAuthentication] action install

  * windows_feature[IIS-WindowsAuthentication] action install

  * windows_feature[IIS-NetFxExtensibility] action install

    ================================================================================
    Error executing action `install` on resource 'windows_feature[IIS-NetFxExtensibility]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0, 42, 127, 3010], but received '50'
    ---- Begin output of C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:IIS-NetFxExtensibility /norestart
   ----
    STDOUT: Tool zur Imageverwaltung f?r die Bereitstellung
    Version: 6.3.9600.17031

    Abbildversion: 6.3.9600.17031

    Features werden aktiviert

    Fehler: 50

    Der Vorgang ist abgeschlossen, das Feature "IIS-NetFxExtensibility" wurde jedoch nicht aktiviert.
    M?glicherweise wurde ein erforderliches ?bergeordnetes Feature nicht aktiviert. Sie k?nnen mit der Option "/enable-featur
e/all" alle ?bergeordneten Features der folgenden Liste aktivieren. Wenn die ?bergeordneten Features bereits aktiviert sind,
pr?fen Sie zur weiteren Diagnose die Protokolldatei.
    NetFx3

    Die DISM-Protokolldatei befindet sich unter "C:\Windows\Logs\DISM\dism.log".
    STDERR:
    ---- End output of C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:IIS-NetFxExtensibility /norestart
 ----
    Ran C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:IIS-NetFxExtensibility /norestart   returned 50

    Cookbook Trace:
    ---------------
    C:\chef\cookbooks\windows\providers\feature_dism.rb:28:in `install_feature'

    Resource Declaration:
    ---------------------
    # In C:\chef\cookbooks\arcgis\providers\iis.rb

     61:     windows_feature feature do
     62:       action :install
     63:     end
     64:   end

    Compiled Resource:
    ------------------
    # Declared in C:\chef\cookbooks\arcgis\providers\iis.rb:61:in `block (2 levels) in class_from_file'

    windows_feature("IIS-NetFxExtensibility") do
      provider LWRP provider windows_feature_dism from cookbook windows
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :windows_feature
      cookbook_name :arcgis
      feature_name "IIS-NetFxExtensibility"
    end


Running handlers:
[2015-08-05T10:52:15+02:00] ERROR: Running exception handlers
Running handlers complete
[2015-08-05T10:52:15+02:00] ERROR: Exception handlers complete
Chef Client failed. 16 resources updated in 181.109377 seconds
[2015-08-05T10:52:15+02:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-08-05T10:52:15+02:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_feature[IIS-NetFxExtensibility] (C:\chef\coo
kbooks\arcgis\providers\iis.rb line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0,
 42, 127, 3010], but received '50'
---- Begin output of C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:IIS-NetFxExtensibility /norestart   -
---
STDOUT: Tool zur Imageverwaltung f?r die Bereitstellung
Version: 6.3.9600.17031

Abbildversion: 6.3.9600.17031

Features werden aktiviert

Fehler: 50

Der Vorgang ist abgeschlossen, das Feature "IIS-NetFxExtensibility" wurde jedoch nicht aktiviert.
M?glicherweise wurde ein erforderliches ?bergeordnetes Feature nicht aktiviert. Sie k?nnen mit der Option "/enable-feature/al
l" alle ?bergeordneten Features der folgenden Liste aktivieren. Wenn die ?bergeordneten Features bereits aktiviert sind, pr?f
en Sie zur weiteren Diagnose die Protokolldatei.
NetFx3

Die DISM-Protokolldatei befindet sich unter "C:\Windows\Logs\DISM\dism.log".
STDERR:
---- End output of C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:IIS-NetFxExtensibility /norestart   ---
-
Ran C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:IIS-NetFxExtensibility /norestart   returned 50

C:\Windows\system32>

**Comment by meinspieler** [comment]
Hi Pavel!

I replied you directly via E-Mail. I hope, you got all attachements? Please, let me know if not!

Best regards,

Marko

**Comment by pbobov** [comment]
Hi Marko,

I did not receive the e-mail with attachments. 

1. Probably, the system recipe fails to create/update 'ArcGISService' user because the user account chef runs under does not have enough privileges (it needs so be able to create or modify user accounts), or the password for 'ArcGISService' user does not meet the password policy of the machine. 

2. The IIS features install fails because NetFxExtensibility feature requires NetFx3 feature. For some reason the recipe works on Windows Server 2012 R2 and does not work on Windows 8.1 (we assumed that these OS works the same way). To fix the problem try to add 'NetFx3' before  NetFxExtensibility  in  attributes/default.rb file or redefine the default set of IIS features in node.json file.
...
default['iis']['features'] = ["IIS-WebServerRole", "IIS-ISAPIFilter", "IIS-ISAPIExtensions",
        "NetFx4Extended-ASPNET45", "IIS-NetFxExtensibility45", "IIS-ASPNET45",
        "IIS-WebServerManagementTools", "IIS-ManagementConsole", "IIS-ManagementService",
        "IIS-IIS6ManagementCompatibility", "IIS-ManagementScriptingTools", "IIS-StaticContent",
        "IIS-BasicAuthentication", "IIS-WindowsAuthentication", "IIS-NetFxExtensibility",
        "IIS-ASPNET", "IIS-Metabase"] 
...
change to 
default['iis']['features'] = ["IIS-WebServerRole", "IIS-ISAPIFilter", "IIS-ISAPIExtensions",
        "NetFx4Extended-ASPNET45", "IIS-NetFxExtensibility45", "IIS-ASPNET45",
        "IIS-WebServerManagementTools", "IIS-ManagementConsole", "IIS-ManagementService",
        "IIS-IIS6ManagementCompatibility", "IIS-ManagementScriptingTools", "IIS-StaticContent",
        "IIS-BasicAuthentication", "IIS-WindowsAuthentication", "NetFx3", "IIS-NetFxExtensibility",
        "IIS-ASPNET", "IIS-Metabase"] 

3. To disable HTTPS you can comment out "Configure HTTPS Binding", however Portal for ArcGIS requires HTTPS. Don't do that if you need portal! If you don't have an SSL certificate,  just  remove  keystore_file and keystore_password iis attributes and the cookbook will generate a self-signed certificate for you.

4. I'll forward your desktop questions to the guys who wrote the desktop 'recipe'.

Regards,
Pavel

**Comment by jonathanan** [comment]
Hi Marko,

For your desktop question:
```
And if I want to set an esri_license_host, I have to remove the ['seat_preference')-node and fill in the node ['esri_license_host'] (see attached node-windows_neu_win81.json-file). Is that correct?
```
No you will you want to add and set node ['esri_license_host'] to your json file and keep ['seat_preference']. Setting seat_preference to fixed = single use seat, and to float = concurrent use seat. 

You can find out more about the supported desktop attributes here:
https://desktop.arcgis.com/en/desktop/latest/get-started/installation-guide/installing-silently.htm

Thanks,
Jonny

**Comment by meinspieler** [comment]
Hi Pavel,

thank you for your quick response!


1.)    After my workaround (see mail before) I use the same password for my ArcGIS Server Account as before without problems. I think, if there has been a passowrd issue, I should get appropriate error-message like in the Win Server 2012 R2 environment. Is that so?

2.)    When I added the‚ NetFx3‘-Feature the installation run without an error!

3.)    Current I do not need a Portal for ArcGIS installation. Regarding HTTP I also had to change https into http in the node [‚server‘][‚url‘] in attributes/default.rb, because I got an „WebAdaptorURL“-error. After the URL-adaption there was no problem anymore. Is there another possibilty to change that or hard-coding?

4.)    Thank you for forwarding my request!

Best regards,

Marko

Von: Pavel Bobov [mailto:notifications@github.com]
Gesendet: Mittwoch, 05. August 2015 18:25
An: Esri/arcgis-cookbook <arcgis-cookbook@noreply.github.com>
Cc: Einspieler Marko <m.einspieler@mysynergis.com>
Betreff: Re: [arcgis-cookbook] Error when running chef-solo -j C:\chef\node-windows_neu.json (#11)


Hi Marko,

I did not receive the e-mail with attachments.

1.      Probably, the system recipe fails to create/update 'ArcGISService' user because the user account chef runs under does not have enough privileges (it needs so be able to create or modify user accounts), or the password for 'ArcGISService' user does not meet the password policy of the machine.

2.      The IIS features install fails because NetFxExtensibility feature requires NetFx3 feature. For some reason the recipe works on Windows Server 2012 R2 and does not work on Windows 8.1 (we assumed that these OS works the same way). To fix the problem try to add 'NetFx3' before NetFxExtensibility in attributes/default.rb file or redefine the default set of IIS features in node.json file.
...
default['iis']['features'] = ["IIS-WebServerRole", "IIS-ISAPIFilter", "IIS-ISAPIExtensions",
"NetFx4Extended-ASPNET45", "IIS-NetFxExtensibility45", "IIS-ASPNET45",
"IIS-WebServerManagementTools", "IIS-ManagementConsole", "IIS-ManagementService",
"IIS-IIS6ManagementCompatibility", "IIS-ManagementScriptingTools", "IIS-StaticContent",
"IIS-BasicAuthentication", "IIS-WindowsAuthentication", "IIS-NetFxExtensibility",
"IIS-ASPNET", "IIS-Metabase"]
...
change to
default['iis']['features'] = ["IIS-WebServerRole", "IIS-ISAPIFilter", "IIS-ISAPIExtensions",
"NetFx4Extended-ASPNET45", "IIS-NetFxExtensibility45", "IIS-ASPNET45",
"IIS-WebServerManagementTools", "IIS-ManagementConsole", "IIS-ManagementService",
"IIS-IIS6ManagementCompatibility", "IIS-ManagementScriptingTools", "IIS-StaticContent",
"IIS-BasicAuthentication", "IIS-WindowsAuthentication", "NetFx3", "IIS-NetFxExtensibility",
"IIS-ASPNET", "IIS-Metabase"]

3.      To disable HTTPS you can comment out "Configure HTTPS Binding", however Portal for ArcGIS requires HTTPS. Don't do that if you need portal! If you don't have an SSL certificate, just remove keystore_file and keystore_password iis attributes and the cookbook will generate a self-signed certificate for you.

4.      I'll forward your desktop questions to the guys who wrote the desktop 'recipe'.

Regards,
Pavel

**Comment by meinspieler** [comment]
Hi Jonny,

thank you for quick response!

Exactly for that I was looking for. Till yet I haven’t found any documentation for used desktop or other attributes. That help me a lot!

It would be nice, if there will be a hint in the ArcGIS Cookbook-documentation where to find possible parameters for used attributes like desktop, server or portal!

With best regards,

Marko

Von: Jonathan An [mailto:notifications@github.com]
Gesendet: Mittwoch, 05. August 2015 18:54
An: Esri/arcgis-cookbook <arcgis-cookbook@noreply.github.com>
Cc: Einspieler Marko <m.einspieler@mysynergis.com>
Betreff: Re: [arcgis-cookbook] Error when running chef-solo -j C:\chef\node-windows_neu.json (#11)


Hi Marko,

For your desktop question:

And if I want to set an esri_license_host, I have to remove the ['seat_preference')-node and fill in the node ['esri_license_host'] (see attached node-windows_neu_win81.json-file). Is that correct?

No you will you want to add and set node ['esri_license_host'] to your json file and keep ['seat_preference']. Setting seat_preference to fixed = single use seat, and to float = concurrent use seat.

You can find out more about the supported desktop attributes here:
https://desktop.arcgis.com/en/desktop/latest/get-started/installation-guide/installing-silently.htm

Thanks,
Jonny

**Comment by pbobov** [comment]
Hi Marko,

1. I'm not sure what is the cause of "Net Api Error Message: Received unknown error code (2220)" error. You can try running chef-solo with '-l debug' option to get more info (chef-solo -j node.json -l debug), the chef run log it will probably contain the exception call stack for the error (the log will be very verbose).

 2. I'm glad that it works. We will add the fix to the cookbook.

3. File attributes/default.rb defines default values for node attributes. You can redefine the attributes values in the node.json file. For example, you can redefine attribute default['server']['url'] in node.json like this:
{ 
 ...
  "server" : {
    ...
    "url" : "http://localhost/server"
  }
}

Regards,
Pavel

**Comment by meinspieler** [comment]
Hi Pavel,

first, thank you for your help!

                1. Ok, I will try it next time!
2. Yes, of course, that’s much more easier!

Thanks a lot and best regards,

Marko

Von: Pavel Bobov [mailto:notifications@github.com]
Gesendet: Montag, 10. August 2015 17:58
An: Esri/arcgis-cookbook <arcgis-cookbook@noreply.github.com>
Cc: Einspieler Marko <m.einspieler@mysynergis.com>
Betreff: Re: [arcgis-cookbook] Error when running chef-solo -j C:\chef\node-windows_neu.json (#11)


Hi Marko,

1.      I'm not sure what is the cause of "Net Api Error Message: Received unknown error code (2220)" error. You can try running chef-solo with '-l debug' option to get more info (chef-solo -j node.json -l debug), the chef run log it will probably contain the exception call stack for the error (the log will be very verbose).

     *   I'm glad that it works. We will add the fix to the cookbook.

2.      File attributes/default.rb defines default values for node attributes. You can redefine the attributes values in the node.json file. For example, you can redefine attribute default['server']['url'] in node.json like this:
{
...
"server" : {
...
"url" : "http://localhost/server"
}
}

Regards,
Pavel

**Comment by pressi14** [comment]
Hi Pavel
        while i am running chef-solo -j C:\chef\node-windows.json file in command prompot it's showing that it's not able to find the C:\chef\solo.rb file and its not installing the softwares

     can you please tell me how to do the cookbook installation and i am following this link 
https:\\github.com\esri\arcgis-cookbook\


Regards
T.Lakshmi Prasanna.

**Comment by pbobov** [comment]
Hi Lakshmi,

solo.rb file is used to specify location of chef cookbooks. If the file is not found, chef client logs that warning message looks for the cookbooks in C:\chef folder. I recommend you to copy the cookbooks from the zip archive downloaded from https://github.com/Esri/arcgis-cookbook/releases/tag/v1.1.3 to C:\chef directory. 

To use the cookbooks you will need ArcGIS software setups and license files. Please make sure that the locations of these files are correctly specified in the .json file. The arcgis cookbook was not tested with new chef-client v12.5. Please use Chef-client v12.4.* or older. 

You will find a few more .json files in the zip archive. If you need to install web GIS, it's better to use webgis-windows.json file.

Regards,
Pavel

**Comment by pressi14** [comment]
Thank you so much, Pavel

regards
Lakshmi

**Comment by pressi14** [comment]
Dear Pavel,

                I am glad you replied, I followed the steps you told and I
installed 12.3.0 version. During the compilation of node-windows.json it's
not taking the authorization file of server and it's showing this error, I
attaching here.


regards,
Lakshmi.

**Comment by pbobov** [comment]
Hi Lakshmi,

I could not find the attached error message. Could you please send it directly to my e-mail or include in a comment? (Please don't send or post real passwords and other sensitive information.)

Regards,
Pavel

**Comment by pressi14** [comment]
Hai Pavel

             I resoveld that issue. I am having problem in finding webadapotorURL and it's stopping the execution.

Regards,
Lakshmi.
