### ISSUE TITLE
webgis-windows-uninstall: DataStore uninstall skipped, clean fails

### ISSUE THREAD

**Issue by jesa-esrich** [Esri/arcgis-cookbook#110]
**Enviroment:**
Our Web GIS Base deployment is on multiple machines.

**Problem**
The command _chef-solo -j C:\chef\webgis-windows-uninstall.json_ fails. The following error is returned: 
**Error executing action 'delete' on resource 'directory[C:\arcgisdatastore]'.**

Hence, I assumed that the uninstall wasn't working properly. Therefore, I tried to only call the recipe webgis_uninstalled with the following parameters: 

_{
  "arcgis": {
    "version": "10.5",
    "server": {
      "install_dir": "C:\\Program Files\\ArcGIS\\Server",
      "wa_name": "server"
    },
    "portal": {
      "install_dir": "C:\\Program Files\\ArcGIS\\Portal",
      "wa_name": "portal"
    },
    "data_store": {
      "install_dir": "C:\\Program Files\\ArcGIS\\DataStore"
    },
    "web_adaptor": {
      "install_dir": ""
    }
  },
  "run_list": [
    "recipe[arcgis-enterprise::webgis_uninstalled]"
  ]
}_

With this recipe the uninstall of Data Store is **skipped due to only_if**, even though the Install Directory is specified...

Is something missing in this recipe or did I forget to specify any other parameters?

**Comment by cameronkroeker** [comment]
This recipe has been depricated. try with enterprise_uninstalled:

https://github.com/Esri/arcgis-cookbook/blob/master/cookbooks/arcgis-enterprise/recipes/enterprise_uninstalled.rb
