### ISSUE TITLE
arcgis-desktop still requires manual intervention

### ISSUE THREAD

**Issue by waymanls** [Esri/arcgis-cookbook#111]
I'm currently using the 3.1.0 version of the arcgis-desktop recipe, installing on Windows Server 2012 R2 Standard, running chef-client 12.15.1 and chef server 12.15.8-1. When executing the following command 

> chef-client-o "recipe[arcgis-desktop]"

the installer window opens up immediately

<img width="1440" alt="screen shot 2017-08-31 at 12 47 53 pm" src="https://user-images.githubusercontent.com/3332397/29935299-3f83fede-8e4c-11e7-905c-bfd81f411a91.png">

Am I'm wondering are there attributes I'm missing out on that are causing this? Any assistance would be appreciated.

**Comment by waymanls** [comment]
Disregard; issue has been solved

**Comment by mschoelen** [comment]
@waymanls We are having a similar issue with arcgis-enterprise installation. Can you describe what you did to solve the issue?

**Comment by waymanls** [comment]
I needed to specify the ArcGIS Self Extractor exe file for the server['setup_archive'] attribute. This should then extract the Setup.exe installer executable and should proceed as normal. 

Sorry for the delay in responding. I hope this helps!
