### ISSUE TITLE
error with script trying to spin up a webservice on new machine, runs fine another machine

### ISSUE THREAD

**Issue by tysontaylor** [Esri/arcgis-cookbook#113]
Trying to run this script on a new machine,  getting this error; however, the script runs fine on another machine.  Anybody have any ideas.  Thank you.

Script.  json file
{
  "arcgis": {
    "run_as_password": "ixxxx",
    "run_as_user": "xxxc",
    "version": "10.5",
    "server": {
      "admin_username": "xxxx",
      "admin_password": "xxxx",
      "directories_root":"\\\\xxxxxx\\aaa\\AGS_Server\\Dev\\arcgisserver",
      "services": [
        {
          "folder": "AB",
          "name": "AgRetailers_v2",
          "type": "MapServer",
          "definition_file": "\\\\xxxxx\\aaa\\AGS_SD\\Dev\\AB_AgRetailers.sd"
         }
     ]
	 }
},
  "run_list": [
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::services]"
  ]
}
-------------------------------------------------
Getting this error:

Generated at 2017-09-14 08:20:29 -0600
ArgumentError: You must supply a name when declaring a file resource
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_builder.rb:46:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/dsl/declare_resource.rb:291:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/dsl/declare_resource.rb:248:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/dsl/resources.rb:40:in `file'
c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/server.rb:85:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context.rb:187:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:511:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/solo.rb:226:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-solo:25:in `<top (required)>'
C:/opscode/chef/bin/chef-solo:68:in `load'
C:/opscode/chef/bin/chef-solo:68:in `<main>'

**Comment by pbobov** [comment]
The problem looks similar to https://github.com/Esri/arcgis-cookbook/issues/112.

**Comment by tysontaylor** [comment]
I confirmed that i was using the same .json file that runs fine on one machine but when i copy and run the same script on this new machine it fails.  the only differences is directory root:

**Run fines on this machine:**
 "directories_root":"C:\\arcgisserver",

**Doesn't run on this machine, changed the directory root because this machine is in a cluster and conf files are stored on a file share**
  "directories_root":"\\\\xxxxxxx\\GIS105Data\\AGS_Server\\Dev\\arcgisserver",

**Comment by tysontaylor** [comment]
this is the script

/*chef-solo -j c:\chef\roles\AGS_DEV_Services.json*/
/*remember before you run this script add folder names in AGS this can be automated via portalpy later*/
{
  "arcgis": {
    "run_as_password": "xxxxx",
    "run_as_user": "xxxxx",
    "version": "10.5",
    "server": {
      "admin_username": "xxxxxx",
      "admin_password": "xxxxxxxxxxxxx",
      "directories_root": "C:\\arcgisserver",
      "services": [
        {
          "folder": "AB",
          "name": "AgRetailers",
          "type": "MapServer",
          "definition_file": "\\\\xxxxxxxx\\GIS105Data\\AGS_SD\\Dev\\AB_AgRetailers.sd"
         }
     ]
	 }
},
  "run_list": [
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::services]"
  ]
}
