### ISSUE TITLE
Web Adaptor Installer Quits If Site Already Exists

### ISSUE THREAD

**Issue by ZianAtFirstWatch** [Esri/arcgis-cookbook#116]
Steps to Reproduce:

1. Set up AGS Web Adaptor 10.3.1 with a name of "fw_arcgis"
2. Run the following role file:
{
  "arcgis":{
    "run_as_user":"fwadmin2",
    "run_as_password":"bleep",
    "version":"10.5.1",
	"server":{
	"wa_name":"fw_arcgis",
		"domain_name": "bleep",
		"url":"https://bleep:6443/arcgis",
      "admin_username":"bleep",
      "admin_password":"bleep",
	  "keystore_file":"C:\\SSLCertificates\\bleep.pfx",
	  "keystore_password":""
	},
    "iis": {
      "domain_name": "example.net",
      "web_site": "Default Web Site",
      "replace_https_binding": false
    },
	"web_adaptor": {
	"admin_access": false,
	"setup":"C:\\Setup.exe"	
	}
  },
  "run_list":[
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::server_wa]"
  ]
}
3. the AGS Web Adaptor IIS 10.5.1 installer will fail and say:
A Web Adaptor with the name "fw_arcgis" already exists on the web site "Default Web Site".

The workaround is to uninstall the existing web adaptor first.

**Comment by cameronkroeker** [comment]
The WA resource is now idempotent. Try with v3.5.0.
