### ISSUE TITLE
Installing Portal: Migration Error

### ISSUE THREAD

**Issue by iirsdeeps** [Esri/arcgis-cookbook#12]
I am using chef-client-12.2.1-1 on Windows 7.

I am having issue installing Portal for ArcGIS.(Using Valid Domain Certificate)
- Portal is getting authorized (with an .ecp file) properly. After that
- It gives an error in creating Portal site
  RuntimeError
  Migration failed.null

Thanks!
Shikhar Deep

**Comment by pbobov** [comment]
Shikhar,

Are you installing the portal on the machine for the first time?

Please try to delete C:\arcgisportal directory (!!! you will loose all the updated portal content if any!!!) and run chef again. 

We recently found a race condition in the cookbook during creation of portal site. Please add "sleep(120.0)" before "portal_admin_client.create_site" line in /providers/portal.rb
```
sleep(120.0)  #add this line
portal_admin_client.create_site(@new_resource.email, @new_resource.full_name, @new_resource.description, 
                             @new_resource.security_question, @new_resource.security_question_answer)
```

Thanks,
Pavel

**Comment by iirsdeeps** [comment]
Sure let me try with sleep(120.0) then shall tell about it!


I am new to it too. And doing a fresh installation:


FYI: Few Observations

1. The C:\arcgisportal gets created but its empty only.
The data actually gets into E:\arcgisportal where Folders "content, db,index
,logs,temp" get created.

Probably due to its path 
dir.data=E:/arcgisportal/
given in 
C:\Program Files\ArcGIS\Portal\etc\portal-config.properties

2. For authorisation:

args = "/VER #{@new_resource.authorization_file_version} /LIF \"#{@new_resource.authorization_file}\" /S"

didnot work for authorisation in portal.rb 
but

args = "-s -ver #{@new_resource.authorization_file_version} -lif \"#{@new_resource.authorization_file}\" "

worked for me!


Thanks & Rgds
Shikhar Deep

**Comment by iirsdeeps** [comment]
Hi Pavel,

Incorporating sleep (120.0) helped in moving further now its giving an error:

"Unable to configure the Portal with the Web Adaptor. Please make sure that the Portal and WebAdaptor are of the same version."

I am using DataStorePortal/Server/Webadaptor of ArcGIS 10.3.1.

Can you please tell where am I going wrong?

Thanks & Rgds
Shikhar Deep

**Comment by pbobov** [comment]
Hi Shikhar,

Could you check the installed versions of Portal and Web Adaptor?

Web Adaptor checks the portal version using version information from portaladmin : http://localhost:7080/arcgis/portaladmin?f=json.  For IIS Web Adaptor itself please check version information defined in the c:\inetpub\wwwroot\arcgis\WebAdaptor.config file. If it is a different version, please uninstall and reinstall WA.

Thanks,
Pavel

**Comment by iirsdeeps** [comment]
Thanks Pavel!

It worked for me now.

Just wanted to know, Portal Content going in E:/arcgisportal/ drive is ok? I still wondering how can I sort it out.


Rgds
Shikhar Deep

**Comment by pbobov** [comment]
Shikhar,

Having content directory on E:/arcgisportal/ is Ok. 

The portal contend directory is defined by ['portal']['content_dir']  attribute. The default value is
 'C:\arcgisportal\content'. I'n not sure how it ended up in E:/arcgisportal/ in your case. Did you set content_dir in node.json file?

Thanks,
Pavel

**Comment by iirsdeeps** [comment]
Okies! I did not set content_dir. 
Will have to look in how this went in E:/arcgisportal/.


Thanks & Rgds
Shikhar Deep

**Comment by pbobov** [comment]
Shikhar,

1. For single machine deployments attributes ['portal']['url'] and ['portal']['local_url'] are typically the same. For multi-machine highly available deployments, ['portal']['url'] is the public URL of load balancer and  ['portal']['local_url'] is the URL of portal on the machine behind load-balancer (where chef is running).

2. That is the race condition I was talking about. I hoped that adding sleep before creating site fixes it. The problem is that the portal content (including properties.json) is unzipped when ArcGISPortal windows service is started. If you try to create site immediately after starting ArcGISPortal sometimes properties.json is not yet there.

Thanks,
Pavel

**Comment by iirsdeeps** [comment]
Hi Pavel,

1. Sleep(120.0) before creating site didn't work always. And as you mentioned about ArcGISPortal   windows service; why dont we place sleep immediately after the portal content is unzipped?

    service "Portal for ArcGIS" do
          action [:enable,:restart]	  
        end
Does this statement starts the required service?

2. Small Observation regarding the E:\arcgisportal\content

While installing manually; Portal takes path for content dir
In my case default it is coming to E:\ (generally it is c:\ only)
Can we manage it thru chef?
I feel somehow its taking previously stored value as E:\ and not getting overrided by C:\:

Thanks
Shikhar Deep
