### ISSUE TITLE
webgis-windows.json "Error executing action `enable` on resource 'windows_service[ArcGIS Server"

### ISSUE THREAD

**Issue by mohibulah** [Esri/arcgis-cookbook#123]
Hello,

While running webgis-windows.json Chef client in Windows Server 2012 R2 terminates with error below:

11T13:17:58+04:30] INFO: Processing windows_feature_dism[IIS-WebServerManagement
Tools] action install (c:/chef/local-mode-cache/cache/cookbooks/windows/resource
s/feature.rb line 60)
 (up to date)
     (up to date)
  * windows_feature[IIS-ManagementConsole] action install[2017-12-11T13:17:58+04
:30] INFO: Processing windows_feature[IIS-ManagementConsole] action install (esr
i-iis::default line 33)

    * windows_feature_dism[IIS-ManagementConsole] action install[2017-12-11T13:1
7:58+04:30] INFO: Processing windows_feature_dism[IIS-ManagementConsole] action
install (c:/chef/local-mode-cache/cache/cookbooks/windows/resources/feature.rb l
ine 60)
 (up to date)
     (up to date)
  * windows_feature[IIS-ManagementService] action install[2017-12-11T13:17:58+04
:30] INFO: Processing windows_feature[IIS-ManagementService] action install (esr
i-iis::default line 33)

    * windows_feature_dism[IIS-ManagementService] action install[2017-12-11T13:1
7:58+04:30] INFO: Processing windows_feature_dism[IIS-ManagementService] action
install (c:/chef/local-mode-cache/cache/cookbooks/windows/resources/feature.rb l
ine 60)
 (up to date)
     (up to date)
  * windows_feature[IIS-IIS6ManagementCompatibility] action install[2017-12-11T1
3:17:58+04:30] INFO: Processing windows_feature[IIS-IIS6ManagementCompatibility]
 action install (esri-iis::default line 33)

    * windows_feature_dism[IIS-IIS6ManagementCompatibility] action install[2017-
12-11T13:17:58+04:30] INFO: Processing windows_feature_dism[IIS-IIS6ManagementCo
mpatibility] action install (c:/chef/local-mode-cache/cache/cookbooks/windows/re
sources/feature.rb line 60)

      - install Windows feature IIS-IIS6ManagementCompatibility
      * ohai[Reloading Dism_Features Plugin - Action [:install] of feature IIS-I
IS6ManagementCompatibility] action reload[2017-12-11T13:18:38+04:30] INFO: Proce
ssing ohai[Reloading Dism_Features Plugin - Action [:install] of feature IIS-IIS
6ManagementCompatibility] action reload (c:/chef/local-mode-cache/cache/cookbook
s/windows/resources/feature_dism.rb line 82)
[2017-12-11T13:18:38+04:30] WARN: Plugin Definition Error: <C:/chef/ohai/plugins
/dism_features.rb>: collect_data already defined on platform windows
[2017-12-11T13:18:40+04:30] INFO: ohai[Reloading Dism_Features Plugin - Action [
:install] of feature IIS-IIS6ManagementCompatibility] reloaded

        - re-run ohai and merge results into node attributes

  * windows_feature[IIS-ManagementScriptingTools] action install[2017-12-11T13:1
8:40+04:30] INFO: Processing windows_feature[IIS-ManagementScriptingTools] actio
n install (esri-iis::default line 33)

    * windows_feature_dism[IIS-ManagementScriptingTools] action install[2017-12-
11T13:18:40+04:30] INFO: Processing windows_feature_dism[IIS-ManagementScripting
Tools] action install (c:/chef/local-mode-cache/cache/cookbooks/windows/resource
s/feature.rb line 60)
 (up to date)
     (up to date)
  * windows_feature[IIS-StaticContent] action install[2017-12-11T13:18:40+04:30]
 INFO: Processing windows_feature[IIS-StaticContent] action install (esri-iis::d
efault line 33)

    * windows_feature_dism[IIS-StaticContent] action install[2017-12-11T13:18:40
+04:30] INFO: Processing windows_feature_dism[IIS-StaticContent] action install
(c:/chef/local-mode-cache/cache/cookbooks/windows/resources/feature.rb line 60)
 (up to date)
     (up to date)
  * windows_feature[IIS-BasicAuthentication] action install[2017-12-11T13:18:40+
04:30] INFO: Processing windows_feature[IIS-BasicAuthentication] action install
(esri-iis::default line 33)

    * windows_feature_dism[IIS-BasicAuthentication] action install[2017-12-11T13
:18:40+04:30] INFO: Processing windows_feature_dism[IIS-BasicAuthentication] act
ion install (c:/chef/local-mode-cache/cache/cookbooks/windows/resources/feature.
rb line 60)

      - install Windows feature IIS-BasicAuthentication
      * ohai[Reloading Dism_Features Plugin - Action [:install] of feature IIS-B
asicAuthentication] action reload[2017-12-11T13:18:51+04:30] INFO: Processing oh
ai[Reloading Dism_Features Plugin - Action [:install] of feature IIS-BasicAuthen
tication] action reload (c:/chef/local-mode-cache/cache/cookbooks/windows/resour
ces/feature_dism.rb line 82)
[2017-12-11T13:18:51+04:30] WARN: Plugin Definition Error: <C:/chef/ohai/plugins
/dism_features.rb>: collect_data already defined on platform windows
[2017-12-11T13:18:53+04:30] INFO: ohai[Reloading Dism_Features Plugin - Action [
:install] of feature IIS-BasicAuthentication] reloaded

        - re-run ohai and merge results into node attributes

  * windows_feature[IIS-WindowsAuthentication] action install[2017-12-11T13:18:5
3+04:30] INFO: Processing windows_feature[IIS-WindowsAuthentication] action inst
all (esri-iis::default line 33)

    * windows_feature_dism[IIS-WindowsAuthentication] action install[2017-12-11T
13:18:53+04:30] INFO: Processing windows_feature_dism[IIS-WindowsAuthentication]
 action install (c:/chef/local-mode-cache/cache/cookbooks/windows/resources/feat
ure.rb line 60)
 (up to date)
     (up to date)
  * windows_feature[IIS-Metabase] action install[2017-12-11T13:18:53+04:30] INFO
: Processing windows_feature[IIS-Metabase] action install (esri-iis::default lin
e 33)

    * windows_feature_dism[IIS-Metabase] action install[2017-12-11T13:18:53+04:3
0] INFO: Processing windows_feature_dism[IIS-Metabase] action install (c:/chef/l
ocal-mode-cache/cache/cookbooks/windows/resources/feature.rb line 60)
 (up to date)
     (up to date)
  * windows_service[W3SVC] action enable[2017-12-11T13:18:53+04:30] INFO: Proces
sing windows_service[W3SVC] action enable (esri-iis::default line 38)
 (up to date)
  * windows_service[W3SVC] action start[2017-12-11T13:18:53+04:30] INFO: Process
ing windows_service[W3SVC] action start (esri-iis::default line 38)
 (up to date)
  * openssl_x509[C:\ArcGISSetupFiles\weps16_certificates\WEPS16.MoI.Local.pem] a
ction create[2017-12-11T13:18:53+04:30] INFO: Processing openssl_x509[C:\ArcGISS
etupFiles\weps16_certificates\WEPS16.MoI.Local.pem] action create (esri-iis::def
ault line 42)
 (skipped due to only_if)
  * ruby_block[Convert to PKCS12] action nothing[2017-12-11T13:18:53+04:30] INFO
: Processing ruby_block[Convert to PKCS12] action nothing (esri-iis::default lin
e 52)
 (skipped due to action :nothing)
  * esri_iis_iis[Configure HTTPS Binding] action configure_https[2017-12-11T13:1
8:53+04:30] INFO: Processing esri_iis_iis[Configure HTTPS Binding] action config
ure_https (esri-iis::default line 71)
 (up to date)
Recipe: arcgis-enterprise::server
  * arcgis_enterprise_server[Update ArcGIS Server service logon account] action
nothing[2017-12-11T13:18:53+04:30] INFO: Processing arcgis_enterprise_server[Upd
ate ArcGIS Server service logon account] action nothing (arcgis-enterprise::serv
er line 21)
 (skipped due to action :nothing)
  * arcgis_enterprise_server[Install System Requirements:server] action system[2
017-12-11T13:18:53+04:30] INFO: Processing arcgis_enterprise_server[Install Syst
em Requirements:server] action system (arcgis-enterprise::server line 31)

    * windows_firewall_rule[ArcGIS Server] action create[2017-12-11T13:18:53+04:
30] INFO: Processing windows_firewall_rule[ArcGIS Server] action create (c:/chef
/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/server.rb line 39)

 (skipped due to only_if)
    * windows_firewall_rule[ArcGIS GeoAnalytics Server] action create[2017-12-11
T13:18:53+04:30] INFO: Processing windows_firewall_rule[ArcGIS GeoAnalytics Serv
er] action create (c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/pr
oviders/server.rb line 48)
 (skipped due to only_if)

  * arcgis_enterprise_server[Unpack ArcGIS Server Setup] action unpack[2017-12-1
1T13:18:53+04:30] INFO: Processing arcgis_enterprise_server[Unpack ArcGIS Server
 Setup] action unpack (arcgis-enterprise::server line 36)
 (skipped due to only_if)
  * arcgis_enterprise_server[Setup ArcGIS Server] action install[2017-12-11T13:1
8:53+04:30] INFO: Processing arcgis_enterprise_server[Setup ArcGIS Server] actio
n install (arcgis-enterprise::server line 52)

  * arcgis_enterprise_server[Configure arcgisserver service] action configure_au
tostart[2017-12-11T13:24:12+04:30] INFO: Processing arcgis_enterprise_server[Con
figure arcgisserver service] action configure_autostart (arcgis-enterprise::serv
er line 68)

    * windows_service[ArcGIS Server] action enable[2017-12-11T13:24:12+04:30] IN
FO: Processing windows_service[ArcGIS Server] action enable (c:/chef/local-mode-
cache/cache/cookbooks/arcgis-enterprise/providers/server.rb line 655)

      ==========================================================================
======
      Error executing action `enable` on resource 'windows_service[ArcGIS Server
]'
      ==========================================================================
======

      SystemCallError
      ---------------
      The specified service does not exist as an installed service. - OpenServic
e: The specified service does not exist as an installed service.

      Resource Declaration:
      ---------------------
      # In c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/
server.rb

      655:     service 'ArcGIS Server' do
      656:       action :enable
      657:     end
      658:   else

      Compiled Resource:
      ------------------
      # Declared in c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/p
roviders/server.rb:655:in `block in class_from_file'

      windows_service("ArcGIS Server") do
        action [:enable]
        supports {:restart=>nil, :reload=>nil, :status=>nil}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        service_name "ArcGIS Server"
        enabled nil
        running nil
        masked nil
        pattern "ArcGIS Server"
        startup_type :automatic
        declared_type :service
        cookbook_name "arcgis-enterprise"
      end

      System Info:
      ------------
      chef_version=12.21.26
      platform=windows
      platform_version=6.3.9600
      ruby=ruby 2.3.5p376 (2017-09-14 revision 59905) [x64-mingw32]
      program_name=C:/opscode/chef/bin/chef-solo
      executable=C:/opscode/chef/bin/chef-solo

[2017-12-11T13:24:12+04:30] INFO: Running queued delayed notifications before re
-raising exception

    ============================================================================
====
    Error executing action `configure_autostart` on resource 'arcgis_enterprise_
server[Configure arcgisserver service]'
    ============================================================================
====

    SystemCallError
    ---------------
    windows_service[ArcGIS Server] (c:/chef/local-mode-cache/cache/cookbooks/arc
gis-enterprise/providers/server.rb line 655) had an error: SystemCallError: The
specified service does not exist as an installed service. - OpenService: The spe
cified service does not exist as an installed service.

    Resource Declaration:
    ---------------------
    # In c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/serv
er.rb

     68: arcgis_enterprise_server 'Configure arcgisserver service' do
     69:   install_dir node['arcgis']['server']['install_dir']
     70:   only_if { node['arcgis']['server']['configure_autostart'] }
     71:   action :configure_autostart
     72: end
     73:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/rec
ipes/server.rb:68:in `from_file'

    arcgis_enterprise_server("Configure arcgisserver service") do
      action [:configure_autostart]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :arcgis_enterprise_server
      cookbook_name "arcgis-enterprise"
      recipe_name "server"
      install_dir "C:\\Program Files\\ArcGIS\\Server"
      system_properties {}
      log_level "WARNING"
      user_store_config {}
      role_store_config {}
      privileges {}
      only_if { #code block }
    end

    System Info:
    ------------
    chef_version=12.21.26
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.3.5p376 (2017-09-14 revision 59905) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-solo
    executable=C:/opscode/chef/bin/chef-solo

[2017-12-11T13:24:12+04:30] INFO: Running queued delayed notifications before re
-raising exception

Running handlers:
[2017-12-11T13:24:12+04:30] ERROR: Running exception handlers
Running handlers complete
[2017-12-11T13:24:12+04:30] ERROR: Exception handlers complete
Chef Client failed. 17 resources updated in 07 minutes 53 seconds
[2017-12-11T13:24:12+04:30] FATAL: Stacktrace dumped to c:/chef/local-mode-cache
/cache/chef-stacktrace.out
[2017-12-11T13:24:12+04:30] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2017-12-11T13:24:12+04:30] FATAL: SystemCallError: arcgis_enterprise_server[Con
figure arcgisserver service] (arcgis-enterprise::server line 68) had an error: S
ystemCallError: windows_service[ArcGIS Server] (c:/chef/local-mode-cache/cache/c
ookbooks/arcgis-enterprise/providers/server.rb line 655) had an error: SystemCal
lError: The specified service does not exist as an installed service. - OpenServ
ice: The specified service does not exist as an installed service.
C:\opscode\chef\bin>

This machine is not in a domain environment, we are using self-signed SSL certificate with root trust. FQDN is fully resolving and pinging from intranet computers.

The Windows User we are using to run Chef Client 12.21.26 in the server is an Administrator account. Please let us know what could be wrong. 

Thank you.
Mohibullah

**Comment by pbobov** [comment]
Can you try it with Chef Client 12.21.12? ArcGIS Chef cookbooks seem to have issues with Chef Client 12.21.26.

**Comment by mohibulah** [comment]
Hi Pavel,

Thank you for your prompt response.
Sure I will try it with 12.21.12 and let you know.

Thank you.

**Comment by mohibulah** [comment]
Hi Pavel,

With version 12.21.12 it terminates with exactly the same error:

  * arcgis_enterprise_server[Configure arcgisserver service] action configure_au
tostart[2017-12-12T10:54:01+04:30] INFO: Processing arcgis_enterprise_server[Con
figure arcgisserver service] action configure_autostart (arcgis-enterprise::serv
er line 68)

    * windows_service[ArcGIS Server] action enable[2017-12-12T10:54:01+04:30] IN
FO: Processing windows_service[ArcGIS Server] action enable (c:/chef/local-mode-
cache/cache/cookbooks/arcgis-enterprise/providers/server.rb line 655)


      ==========================================================================
======
      Error executing action `enable` on resource 'windows_service[ArcGIS Server
]'
      ==========================================================================
======

      SystemCallError
      ---------------
      The specified service does not exist as an installed service. - OpenServic
e: The specified service does not exist as an installed service.

      Resource Declaration:
      ---------------------
      # In c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/
server.rb

      655:     service 'ArcGIS Server' do
      656:       action :enable
      657:     end
      658:   else

      Compiled Resource:
      ------------------
      # Declared in c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/p
roviders/server.rb:655:in `block in class_from_file'

      windows_service("ArcGIS Server") do
        action [:enable]
        supports {:restart=>nil, :reload=>nil, :status=>nil}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        service_name "ArcGIS Server"
        enabled nil
        running nil
        masked nil
        pattern "ArcGIS Server"
        startup_type :automatic
        declared_type :service
        cookbook_name "arcgis-enterprise"
      end

      System Info:
      ------------
      chef_version=12.21.12
      platform=windows
      platform_version=6.3.9600
      ruby=ruby 2.3.5p376 (2017-09-14 revision 59905) [x64-mingw32]
      program_name=C:/opscode/chef/bin/chef-solo
      executable=C:/opscode/chef/bin/chef-solo

[2017-12-12T10:54:01+04:30] INFO: Running queued delayed notifications before re
-raising exception

    ============================================================================
====
    Error executing action `configure_autostart` on resource 'arcgis_enterprise_
server[Configure arcgisserver service]'
    ============================================================================
====

    SystemCallError
    ---------------
    windows_service[ArcGIS Server] (c:/chef/local-mode-cache/cache/cookbooks/arc
gis-enterprise/providers/server.rb line 655) had an error: SystemCallError: The
specified service does not exist as an installed service. - OpenService: The spe
cified service does not exist as an installed service.

    Resource Declaration:
    ---------------------
    # In c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/serv
er.rb

     68: arcgis_enterprise_server 'Configure arcgisserver service' do
     69:   install_dir node['arcgis']['server']['install_dir']
     70:   only_if { node['arcgis']['server']['configure_autostart'] }
     71:   action :configure_autostart
     72: end
     73:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/rec
ipes/server.rb:68:in `from_file'

    arcgis_enterprise_server("Configure arcgisserver service") do
      action [:configure_autostart]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :arcgis_enterprise_server
      cookbook_name "arcgis-enterprise"
      recipe_name "server"
      install_dir "C:\\Program Files\\ArcGIS\\Server"
      system_properties {}
      log_level "WARNING"
      user_store_config {}
      role_store_config {}
      privileges {}
      only_if { #code block }
    end

    System Info:
    ------------
    chef_version=12.21.12
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.3.5p376 (2017-09-14 revision 59905) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-solo
    executable=C:/opscode/chef/bin/chef-solo

[2017-12-12T10:54:01+04:30] INFO: Running queued delayed notifications before re
-raising exception

Running handlers:
[2017-12-12T10:54:01+04:30] ERROR: Running exception handlers
Running handlers complete
[2017-12-12T10:54:01+04:30] ERROR: Exception handlers complete
Chef Client failed. 10 resources updated in 05 minutes 18 seconds
[2017-12-12T10:54:01+04:30] FATAL: Stacktrace dumped to c:/chef/local-mode-cache
/cache/chef-stacktrace.out
[2017-12-12T10:54:01+04:30] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2017-12-12T10:54:01+04:30] FATAL: SystemCallError: arcgis_enterprise_server[Con
figure arcgisserver service] (arcgis-enterprise::server line 68) had an error: S
ystemCallError: windows_service[ArcGIS Server] (c:/chef/local-mode-cache/cache/c
ookbooks/arcgis-enterprise/providers/server.rb line 655) had an error: SystemCal
lError: The specified service does not exist as an installed service. - OpenServ
ice: The specified service does not exist as an installed service.

**Comment by pbobov** [comment]
@mohibulah Please check if 'ArcGIS Server' windows service exists on the machine? (There must be one if ArcGIS Server setup completed successfully.)

**Comment by nadiaChaimae** [comment]
Hi,
@pbobov  i have the seem issue but in webgis-ubuntu.json 
    Error executing action `enable` on resource 'service[arcgisserver]'

      Errno::ENOENT
      -------------
      No such file or directory - /sbin/status

      Resource Declaration:
      ---------------------
      # In /var/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/server.rb

      698:     service 'arcgisserver' do
      699:       supports :status => true, :restart => true, :reload => true
      700:       action :enable
      701:       retries 5
      702:       retry_delay 60
      703:     end
      704:

**Comment by cameronkroeker** [comment]
very likely the installation did not complete successfully or create the service. try with the latest cookbook v3.5.0
