### ISSUE TITLE
esri-iis cookbook issue

### ISSUE THREAD

**Issue by srinivas-anant** [Esri/arcgis-cookbook#124]
I was creating the portal server and when the esri-iis cookbook was converging it started failing and the error message I got was: 
`
no mapping between account names and security ids was done
`
I am running this cookbook on a windows 2016 and the server is joined to an AD and here is log:
```
Generated at 2018-01-04 03:54:06 -0500
Chef::Exceptions::Win32APIError: openssl_x509[c:\chef\cache/my_domain_name.pem] (esri-iis::default line 42) had an error: Chef::Exceptions::Win32APIError: file[c:\chef\cache/my_domain_name.pem] (c:/chef/cache/cookbooks/openssl/resources/x509.rb line 26) had an error: Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done.
---- Begin Win32 API output ----
System Error Code: 1332
System Error Message: No mapping between account names and security IDs was done.
---- End Win32 API output ----
```

What might be causing the issue @pbobov ? Its failing to create the self signed certificates.

**Comment by srinivas-anant** [comment]
@pbobov - Any thoughts on as to why this happening?

**Comment by pbobov** [comment]
Do you use disk drives mapped to network shares in your configuration?

**Comment by pbobov** [comment]
What chef-client version do you use?

**Comment by srinivas-anant** [comment]
No we are not using disk drives mapped to network share. 

Chef client version - 12.19.36

**Comment by pbobov** [comment]
I run into similar problem with chef client 12.17.44. The problem disappeared after I upgraded chef client to 12.21.12. Could you try chef-client 12.21.12?

In my case the error message was 
```
[2017-09-15T18:20:34+00:00] ERROR: #<Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done.
---- Begin Win32 API output ----
System Error Code: 1332
System Error Message: No mapping between account names and security IDs was done.
---- End Win32 API output ----
>
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/win32/error.rb:81:in `raise!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/win32/security.rb:383:in `lookup_account_name'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/win32/security/sid.rb:44:in `from_account'
```

**Comment by srinivas-anant** [comment]
I used chef client - 12.21.12 still the same issue.

**Comment by srinivas-anant** [comment]
All fixed it was an issue caused by the openssl cookbook.
