### ISSUE TITLE
Expected process to exit with [0, 3010], but received '16389' (client 12.21.3/ Windows 2008 R2)

### ISSUE THREAD

**Issue by mschoelen** [Esri/arcgis-cookbook#126]
Running **arcgis-enterprise::system** results in a fatal error (16389).

Chef-client version: 12.21.3
Client was installed via bootstrap on Windows Server 2008 R2

  "run_list":[
    "recipe[arcgis-enterprise::system]",    
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::federation]"
  ]

Error message:

`SERV01.website.com [2018-01-18T11:06:37-05:00] FATAL: Mixlib::ShellOut::Shell
CommandFailed: arcgis_enterprise_server[Install System Requirements:server] (ar
cgis-enterprise::server line 31) had an error: Mixlib::ShellOut::ShellCommandFa
iled: ms_dotnet_framework[4.5.1] (ms_dotnet::ms_dotnet4 line 24) had an error:
Mixlib::ShellOut::ShellCommandFailed: windows_package[Microsoft .NET Framework
4.5.1] (c:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb line 77) had a
n error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0
, 3010], but received '16389'`

I'm not entirely sure where to start with debugging this. It appears to be related to the MS .NET 4.5.1 configuration.

**Comment by jonathanan** [comment]
I'm guessing the source for installing .NET 4.5.1 is not available by default on the version of windows you are running. Can you verify this manually?

Please see the [ms_dotnet cookbook](https://github.com/criteo-cookbooks/ms_dotnet#net-recipes-attributes) how to set the attributes for .NET package_sources.

**Comment by mschoelen** [comment]
So I verified that the default source was available, but just in case, I added specific overwrite attributes to my environment to specify the source.

`{
  "msdotnet": {
    "v4": {
      "package_sources": "https://download.microsoft.com/download/1/6/7/167F0D79-9317-48AE-AEDB-17120579F8E2/NDP451-KB2858728-x86-x64-AllOS-ENU.exe"
    }
  },

  "arcgis": {
    "version": "10.5.1",
    "data_store": {
      "data_dir": "C:\\arcgisdatastore"
    },
    "server": {
      "directories_root": "C:\\arcgisserver"
    },
    "portal": {
      "data_dir": "C:\\arcgisportal"
    }
  }
}`

I got the same error code (16389)

`SERV01.website.com================================================================================←[0m
SERV01.website.com  ←[31mError executing action `install` on resource 'ms_dotn
et_framework[4.5.1]'←[0m
SERV01.website.com ==========================================================
======================←[0m`

**Comment by mschoelen** [comment]
I was able to circumvent this issue by manually installing the version of Microsoft .NET that was installed on the machine.

**Comment by mschoelen** [comment]
This issue is apparently related to permissions when using winrm. @Annih made the recommendation to trick chef-client into running locally via task scheduler or using PSExec ([outlined here](https://github.com/criteo-cookbooks/ms_dotnet#known-issues)).

The most immediate bandaid (not a long term solution for a production environment) to this issue is to simply set the attribute `['arcgis']['server']['install_system_requirements']` to `false`, and manually install the requirements (MS .NET 5.4.1) before running Chef.
