### ISSUE TITLE
Running arcgis-enterprise::server gets held up by prompt for installation Destination Folder

### ISSUE THREAD

**Issue by mschoelen** [Esri/arcgis-cookbook#129]
I am running a recipe for the installation of ArcGIS Enterprise Server. It was timing out (no error codes), so I ran the client directly on the node, and I was getting prompted for input on the location of the installation destination folder for unpacking. 

Is this because I don't have some attribute defined? I was fine with the default settings, so I didn't define anything.

![capture](https://user-images.githubusercontent.com/35381359/35168927-b10c2fcc-fd28-11e7-8390-bb1382f2580b.PNG)

**Comment by pbobov** [comment]
I guess the folder specified by arcgis/server/install_dir attribute is not accessible for some reason.

**Comment by mschoelen** [comment]
@pbobov , my thoughts too. However, changing that location gives me the same result. 
I don't think its the installation directory that is the problem (install_dir). I need to specify where the install files are unpacked/extracted to, and I can't seem to find what attribute I would need to define for that.

**Comment by pbobov** [comment]
:unpack action only runs if there is no Setup.exe at node['arcgis']['server']['setup'] path. :unpack extracts Setup.exe from the archive. In your case Setup.exe is running, so the problem is not related to :unpack.

**Comment by pbobov** [comment]
I guess I understand he problem.  You set node['arcgis']['server']['setup'] to the path of the self extracted setup archive (ArcGIS_Server_Windows_1051_156124.exe).  But that attribute should point to the path to Setup.exe.

The new way of doing that is to put all the setup archives to one folder, specify the folder path in node['arcgis']['repository']['archives'] attribute, and set node['arcgis']['version'] attribute. Chef will figure out what to get where.

```JSON
{
  "arcgis":{
    "run_as_password":"Run_As_Pa$$w0rd",
    "run_as_user":"arcgis",
    "version":"10.5.1",
    "repository":{
      "archives":"\\\\repo.com\\Software\\Esri"
    },
    "web_adaptor":{
      "admin_access":true
    },
    "server":{
      "admin_username":"admin",
      "admin_password":"changeit",
      "authorization_file":"\\\\repo\\Authorization_Files\\server105.prvc"
    },
    "portal":{
      "admin_username":"admin",
      "admin_password":"changeit",
      "admin_email":"admin@mydomain.com",
      "security_question":"Your favorite ice cream flavor?",
      "security_question_answer":"vanilla",
      "authorization_file":"\\\\repo\\Authorization_Files\\portal105.prvc"
    }
  },
  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::portal]",
    "recipe[arcgis-enterprise::portal_wa]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::server_wa]",
    "recipe[arcgis-enterprise::datastore]",
    "recipe[arcgis-enterprise::federation]"
  ]
}
```

**Comment by mschoelen** [comment]
That was it! Thank you.
