### ISSUE TITLE
Custom installation of ArcGIS for Desktop silently:

### ISSUE THREAD

**Issue by iirsdeeps** [Esri/arcgis-cookbook#13]
In chef arcgis-cookbook:
ADDLOCAL takes parameters through 'install_features': (Found in default.rb)

When I tried the following combinations: (I had issues with Python specially.)
1. 'install_features':'ArcMap,Python' -->Only these two gets installed properly
2. 'install_features':'Python' --> Only Python gets installed
3. 'install_features':'ArcMap,Python,ArcCatalog' --> Error, 
                   Invalid command line argument.
           Consult the Windows Installer SDK 
                    for detailed command line help.

4.'install_features':'ArcMap,ArcCatalog,Ext_3D_Analyst,NetworkAnalyst'--> Proper Installation 
    of each mentioned with an exception of Python

Kindly let me know why the issue is with Python.

Thanks & Rgds
Shikhar Deep

**Comment by jonathanan** [comment]
Hi Shikhar,

Thanks for submitting the issue!
I tried your #3 and did not run into a problem. ArcMap,Python,ArcCatalog were properly installed. Also your #4 did not include Python as an install feature.

Could you try editing your json file instead of the default attributes.rb?
Here is a sample of my json file:
```
{
   "desktop" : {
     "setup" : "C:\\temp\\Desktop\\Setup.exe",
     "authorization_file":"C:\\temp\\DTAdvanced.prvc",
     "software_class":"Viewer",
     "seat_preference":"Fixed",
     "desktop_config":"True",
     "install_features":"ArcMap,Python,ArcCatalog"
   },
   "run_list":[
      "recipe[arcgis::desktop]"
   ]
}
```
Our ESRI docs specify that the feature names are case sensitive which you appear to have correct. https://desktop.arcgis.com/en/desktop/latest/get-started/installation-guide/installing-silently.htm

Thanks,
Jonny

**Comment by iirsdeeps** [comment]
Hi Jonny,

My Sample of json is:
 "desktop" : {     
     "setup" : "C:\\Users\\ShikharD\\Documents\\ArcGIS 10.3.1\\Desktop\\Setup.exe",
     "esri_license_host":"SYSTEM-123",
     "software_class":"Professional",
     "seat_preference":"Float",
     "desktop_config":"true"
	}

Professional: ArcGIS for Desktop as Advanced 
Float: Concurrent User
esri_license_host: Machine name of license manager.


desktop_config: setting true doesn't takes it true. Found its not defined in default.rb too. 
                          Probably it takes false from the resources/desktop.rb

**Comment by jonathanan** [comment]
Shikhar,

After taking a closer look, I found the issue is in the providers/desktop.rb. You need to remove 
```
RENEWAL_CHECK=\"#{@new_resource.renewal_check}\"
```
in the install command. It is an outdated attribute.

Also, you need to add to recipes/desktop.rb as an attribute
```
desktop_config node['desktop']['desktop_config']
```
in order to get it to work properly in your json file.

I am working on getting these fixes updated to the repo.
Thanks for the bugs!

-Jonny

**Comment by iirsdeeps** [comment]
Thanks Jonny !

Will try the above and see how the installation goes.

Shikhar Deep

**Comment by iirsdeeps** [comment]
Jonny!

"install_features":"ArcMap,Python,ArcCatalog" : working perfectly
 But
 "install_features":"ArcMap,Python,ArcCatalog,ArcMap_Publishing_Extension,SpatialAnalyst,NetworkAnalyst,CivicAndBusiness,TemplateIndustry"

is giving me error now "Error, Invalid command line argument. Consult the Windows Installer SDK for detailed command line help."

Is there any wrong combination I am trying?

Thanks 
Shikhar Deep

**Comment by jonathanan** [comment]
Shikhar,

The default location in which chef-solo expects to find this file is /etc/chef/solo.rb; use the --config option from the command line to change this location. The config file is optional.
Reference: https://docs.chef.io/config_rb_solo.html

Also is it seems like you found another bug in terms of the setups. 
I got 
"install_features":"ArcMap,Python,ArcCatalog,Extensions"
to work. But this should be incorrect according to our docs.

I will contact our setup team about this issue, but unfortunately I do not have a solution right now. Sorry for the inconvenience.

-Jonny

**Comment by jonathanan** [comment]
Windows has a 255 character limit for a command line argument 

If you are using default values, 
Such as:
INSTALLDIR="C:\Program Files (x86)\ArcGIS"
INSTALLDIR1="C:\Python27"
SOFTWARE_CLASS="Professional"
SEAT_PREFERENCE="Float"

You could edit the cookbook/arcgis/providers/desktop.rb and remove those parameters.

**Comment by iirsdeeps** [comment]
Jonny!

Thanks a Lot!

I could not get exactly what do I need to change for solo.rb?

Thanks & Rgds
Shikhar Deep
