### ISSUE TITLE
10.6 Support

### ISSUE THREAD

**Issue by jesseadamsnpgs** [Esri/arcgis-cookbook#130]
Any ideas when the chef cookbook's will support the 10.6 upgrade?

![image](https://user-images.githubusercontent.com/19274266/35177385-8f7fbdee-fd44-11e7-9a36-836a41445ca9.png)

**Comment by pbobov** [comment]
I guess this will happen on Monday. :) See https://github.com/Esri/arcgis-cookbook/pull/128.

**Comment by jesseadamsnpgs** [comment]
Sounds great!  Thank you.

**Comment by pbobov** [comment]
ArcGIS 10.6 is supported by the just released ArcGIS Chef Cookbooks v3.2.0.
