### ISSUE TITLE
ArcGIS Server, Service Account as a domain user

### ISSUE THREAD

**Issue by powersparks** [Esri/arcgis-cookbook#134]
Great Chef Cookbooks at: arcgis-cookbook/cookbooks/arcgis-enterprise/
 Thanks.
I am having some trouble with domain user names for the "run_as_user" account for ArcGIS Server. 

Everything seems to be working very well for both single or HA installation.  I could have sworn that the installation with a domain account was working fine, and noticed that "domain\username" or "domain\\username" or "username@domain" or something like "username@domain.ou.ou.org" didn't apply the user name to the arcgis service.  
(note: this is a Windows Active Directory domain user, running Chef Cookbook Version = 3.10)
Can someone confirm if the recipes will correctly pass a domain user name to the ArcGIS Server setup.exe?

**Comment by jsthusker** [comment]
Yes they will.  I have done it.  Make sure permissions on the server are correct

**Comment by mkarikari** [comment]
@powersparks  were you able to resolve your issue? @jsthusker what the exact permission you have set for the domain account on the server. I'm having same issue, ive tried adding account in the admin group and updating the local login as service policy w/ no luck

**Comment by jsthusker** [comment]
The domain account is in the local server admin group. Here is some documentation detailing the permissions required. https://enterprise.arcgis.com/en/server/latest/install/windows/the-arcgis-server-account.htm
As long as the account has these permissions correct it should work.

**Comment by azinsharaf** [comment]
@powersparks Have you fixed this issue?

**Comment by cameronkroeker** [comment]
please try with latest cookbook v3.5.0 and chef client 13 or 14.
