### ISSUE TITLE
arcgis 10.5.1 - Failed to open TCP connection to arcgis.test.be:443 (Connection refused - connect(2) for "arcgis.test.be" port 443)

### ISSUE THREAD

**Issue by stijnvanrenterghem** [Esri/arcgis-cookbook#135]
Hi,

I use the following template to install on AWS (10.5.1):
https://s3.amazonaws.com/arcgisstore1051/7333/templates/arcgis-webgis-ha-ubuntu.template

*The installation fails with:
chef-solo -j /tmp/node.json -r https://arcgisstore1051.s3.amazonaws.com/7333/cookbooks/arcgis-3.1.0-cookbooks.tar.gz -L /var/log/chef-run.log -l info
 * arcgis_enterprise_webadaptor[Configure Web Adaptor with Server] action configure_with_server
     ================================================================================
    Error executing action `configure_with_server` on resource 'arcgis_enterprise_webadaptor[Configure Web Adaptor with Server]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Failed to open TCP connection to arcgis.test.be:443 (Connection refused - connect(2) for "arcgis.test.be" port 443)

    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/libraries/server_rest_client.rb:56:in `available?'
    /etc/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/webadaptor.rb:150:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/server_wa.rb

     65: arcgis_enterprise_webadaptor 'Configure Web Adaptor with Server' do
     66:   install_dir node['arcgis']['web_adaptor']['install_dir']
     67:   server_wa_url node['arcgis']['server']['wa_url']
     68:   server_url node['arcgis']['server']['url']
     69:   username node['arcgis']['server']['admin_username']
     70:   password node['arcgis']['server']['admin_password']
     71:   admin_access node['arcgis']['web_adaptor']['admin_access']
     72:   retries 5
     73:   retry_delay 60
     74:   action :configure_with_server
     75: end

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/server_wa.rb:65:in `from_file'

    arcgis_enterprise_webadaptor("Configure Web Adaptor with Server") do
      action [:configure_with_server]
      retries 5
      retry_delay 60
      default_guard_interpreter :default
      declared_type :arcgis_enterprise_webadaptor
      cookbook_name "arcgis-enterprise"
      recipe_name "server_wa"
      install_dir "/"
      server_wa_url "https://arcgis.test.be/server"
      server_url "https://10.42.0.107:6443/arcgis"
      username "admin"
      password "changeme"
      admin_access true
    end

    Platform:
    ---------
    x86_64-linux
	
	
 Running handlers:
Running handlers complete
Chef Client failed. 4 resources updated in 06 minutes 23 seconds

* There is nothing listening on 443 or 8443
root@ip-10-42-0-107:~# netstat -an | grep 8443
root@ip-10-42-0-107:~# netstat -an | grep 443

'iptables -L -t nat' doesn't show nat rules, but the rules are in /etc/iptables.d/arcgis.iptables
iptables-save > iptables.test
iptables-restore < iptables.test

The rules are now active:
root@ip-10-42-0-107:~# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:http redir ports 8080
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 8443

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:http redir ports 8080
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 8443

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination

I started the script again with the same error:
chef-solo -j /tmp/node.json -r https://arcgisstore1051.s3.amazonaws.com/7333/cookbooks/arcgis-3.1.0-cookbooks.tar.gz -L /var/log/chef-run.log -l info

root@ip-10-42-0-107:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0a:84:92:9c:44:5c brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.107/23 brd 10.42.1.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::884:92ff:fe9c:445c/64 scope link
       valid_lft forever preferred_lft forever

*root@ip-10-42-0-107:~# apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02

root@ip-10-42-0-107:~# /etc/init.d/apache2 status -l
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: failed (Result: exit-code) since Mon 2018-02-05 13:25:17 UTC; 8h ago
     Docs: man:systemd-sysv-generator(8)

Feb 05 13:24:57 ip-10-42-0-107 systemd[1]: Starting LSB: Apache2 web server...
Feb 05 13:24:57 ip-10-42-0-107 apache2[14721]:  * Starting Apache httpd web server apache2
Feb 05 13:25:17 ip-10-42-0-107 apache2[14721]:  *
Feb 05 13:25:17 ip-10-42-0-107 apache2[14721]:  * The apache2 instance did not start within 20 seconds. Please read the log file...roblems
Feb 05 13:25:17 ip-10-42-0-107 systemd[1]: apache2.service: Control process exited, code=exited status=1
Feb 05 13:25:17 ip-10-42-0-107 systemd[1]: Failed to start LSB: Apache2 web server.
Feb 05 13:25:17 ip-10-42-0-107 systemd[1]: apache2.service: Unit entered failed state.
Feb 05 13:25:17 ip-10-42-0-107 systemd[1]: apache2.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.

less /var/log/apache2/error.log
[Mon Feb 05 13:24:57.667405 2018] [proxy_balancer:emerg] [pid 14745:tid 139917398517632] AH01177: Failed to lookup provider 'shm' for 'slotmem': is mod_slotmem_shm loaded??
[Mon Feb 05 13:24:57.667450 2018] [:emerg] [pid 14745:tid 139917398517632] AH00020: Configuration Failed, exiting
recipes/mod_proxy_balancer.rb => https://github.com/sous-chefs/apache2/commit/c2ab27e91a8e5a92c51263247515c03c5e3088b0

=>
ln -s /etc/apache2/mods-available/slotmem_shm.load /etc/apache2/mods-enabled/slotmem_shm.load

**Comment by stijnvanrenterghem** [comment]
[syslog-b.txt](https://github.com/Esri/arcgis-cookbook/files/1697242/syslog-b.txt)
[chef-run-b.log](https://github.com/Esri/arcgis-cookbook/files/1697243/chef-run-b.log)

**Comment by pbobov** [comment]
As far as I know, ArcGIS Enterprise 10.5.1 Ubuntu AMI does not have Apache web server installed. It looks like the EC2 instance was customized.  Please contact Esri tech support to address this issue.

**Comment by stijnvanrenterghem** [comment]
Thank you

**Comment by cameronkroeker** [comment]
Closing since the recommendation was to reach out to Esri Support, and thread is a few years old.
