### ISSUE TITLE
Clarification on URL attributes in Server deployment

### ISSUE THREAD

**Issue by mschoelen** [Esri/arcgis-cookbook#137]
I am attempting to deploy a machine with ArcGIS Server and Server WA, but every time I federate, the machine is listed as the _machine name_, rather than the _domain name_. 

Assuming that I have a machine (machine01.machine.com) and it has a domain name of (website.domain.com), what am I specifying wrong here? 

      "web_context_url": "https://website.domain.com/server",
      "wa_name": "server",
      "wa_url": "https://website.domain.com/arcgis",
      "url": "https://machine01.machine.com:6443/arcgis",

**Comment by pbobov** [comment]
The default values for server URLs are set this way:
```
default['arcgis']['server']['url'] = 'https://' + node['fqdn'] + ':6443/arcgis'
default['arcgis']['server']['private_url'] = 'https://' + node['arcgis']['server']['domain_name'] + ':6443/arcgis'
default['arcgis']['server']['wa_url'] = 'https://' + node['fqdn'] + '/' + node['arcgis']['server']['wa_name']
default['arcgis']['server']['web_context_url'] = 'https://' + node['arcgis']['server']['domain_name'] + '/' + node['arcgis']['server']['wa_name']
```
By default node['arcgis']['server']['domain_name'] is set to FQDN of the machine (machine01.machine.com).
```
default['arcgis']['server']['domain_name'] = node['fqdn']
```
Setting `domain_name` attribute affects `private_url` and `web_context_url` attributes. The `domain_name` is typically set to the load balancer domain name. All of the *_url attributes can also be set explicitly just like other attributes.
