### ISSUE TITLE
Provision a highly available ArcGIS Enterprise deployment on three AWS machine

### ISSUE THREAD

**Issue by sourav1985** [Esri/arcgis-cookbook#139]
Hello Sir, 

I want to deploy the below architecture in aws can you assist with the code please will you assist

[code.txt](https://github.com/Esri/arcgis-cookbook/files/1739383/code.txt)

https://s3.amazonaws.com/arcgisstore106/8321/docs/ReadmeHAWebGIS.html

**Comment by pbobov** [comment]
Please use the Esri CloudFormation templates
https://s3.amazonaws.com/arcgisstore106/8321/docs/index.html for that.
