### ISSUE TITLE
Setups for ArcGIS for Server, Portal, Web Adaptor 

### ISSUE THREAD

**Issue by ryanmcadler** [Esri/arcgis-cookbook#14]
Hi,

I'm attempting to install ArcGIS Server, Portal, etc. on an Ubuntu 14.04 LTS (AWS) box and am getting an error related to the setup of AGS; here's the contents of my chef-stacktrace.out file:

    Generated at 2015-08-13 20:12:47 +0000
    Mixlib::ShellOut::ShellCommandFailed: execute[Install ArcGIS for Server] (/home/ubuntu/chef/cookbooks/arcgis/providers/server.rb line 68) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '126'
    ---- Begin output of sudo -H -u arcgis bash -c "/home/ubuntu/ags_binaries/ArcGIS_for_Server -m silent -l yes -d "/"" ----
    STDOUT:
    STDERR: sudo: unable to resolve host ip-172-30-1-71
    bash: /home/ubuntu/ags_binaries/ArcGIS_for_Server: cannot execute binary file: Exec format error
    ---- End output of sudo -H -u arcgis bash -c "/home/ubuntu/ags_binaries/ArcGIS_for_Server -m silent -l yes -d "/"" ----
    Ran sudo -H -u arcgis bash -c "/home/ubuntu/ags_binaries/ArcGIS_for_Server -m silent -l yes -d "/"" returned 126
    /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:289:in `invalid!'
    /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:276:in `error!'
    /opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
    /opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:61:in `block in action_run'
    /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
    /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
    /opt/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
    /opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:60:in `action_run'
    /opt/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
    /opt/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
    /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
    /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
    /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
    /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
    /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
    /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
    /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
    /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
    /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
    /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
    /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
    /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
    /opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
    /opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
    /opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
    /opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
    /opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
    /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
    /usr/bin/chef-solo:55:in `load'
    /usr/bin/chef-solo:55:in `<main>'

For my setups I'm using binaries I've downloaded through MyESRI.  The paths used in the example configs suggest that I should perhaps being using an image of the installation media.  Is that's the case, 
is there a way I can use the MyESRI binaries or is it best to use the installation media?

Thanks in advance.

**Comment by pbobov** [comment]
Hi, 

You need to extract the server Setup from the distributive archive and provide cookbook with the setup path. 

Deployment of ArcGIS for Server in AWS is has some specifics. In particular, in VPC there is no DNS server (hostnames are not resolved) and in classic EC2 instances change IP addresses after restart,...

ArcGIS 10.3.1 for Server is not officially supported on Ubuntu, unless you start from AMIs provided by Esri.

Regards,
Pavel

**Comment by ryanmcadler** [comment]
Hi Pavel,

Thanks for the response.  Does ESRI have any docs that cover extracting the Setup from the distributive archive?  I'm not sure where to start.

Thanks again.

**Comment by pbobov** [comment]
Hi Ryan,

As far as I know, the linux setups are distributed as tar.gz archives. You need to extract the files from the archives. I'm not sure if ESRI has a doc for that. This document 
http://server.arcgis.com/en/server/latest/install/linux/silently-install-arcgis-server.htm (and the arcgis chef cookbook) assume that the setups are already extracted. (We will think about automating the extraction of setups as well in future versions of the cookbook...).

If you need to install portal and server on Ubuntu in AWS, check out  CloudFormation templates to set up ArcGIS for Server on Amazon Web Services (http://esriarcgisserverrepository.s3.amazonaws.com/10.3.1/Index.htm). CF templates "ArcGIS for Server WebGIS on one instance in EC2-VPC (Ubuntu)" uses chef-solo and arcgis cookbook internally. 10.3.1 ArcGIS Server AMIs have chef client, portal and server installed. And the arcgis cookbook is used to configure all the apps.

Regards,
Pavel

**Comment by pbobov** [comment]
Ryan,

Can you share your node.json file (without actual passwords)?

Thanks,
Pavel

**Comment by ryanmcadler** [comment]
Hi Pavel,

I should probably clarify that my problem isn't unpacking tar.gz files.  Basically I suspect the downloads that I've obtained through MyESRI (which are distributed in *.gz format) don't work with the current cookbook as when I gunzip them, an extension-less binary is returned (should the linux setups consist of bash scripts?).  The setup paths used in the example node JSON files vaguely suggest that I should be using images of the installation media for the setups--is this the case or should the downloads from MyESRI for AGS, Portal, etc. work?

Here is contents of my node-linux.json file that I'm running Chef Client against, albeit slightly anonymized (I plan to use Tomcat with a self-signed cert for now):

    {
            "licensemanager":{
                    "setup":"/home/ubuntu/ags_binaries/ArcGIS_License_Manager"
            },
            "java":{
                    "install_flavor":"oracle",
                    "jdk_version":"7",
                    "oracle":{
                            "accept_oracle_download_terms":true
                    }
            },
            "tomcat":{
                    "base_version":7,
                    "port":80,
                    "ssl_port":443,
                    "authbind":"yes"
            },
            "web_adaptor":{
                    "setup":"/home/ubuntu/ags_binaries/Web_Adaptor"
            },
            "data_store":{
                    "setup":"/home/ubuntu/ags_binaries/ArcGIS_DataStore"
            },
            "server":{
                    "domain_name":"ags0.mydomain.com",
                    "admin_username":"admin",
                    "admin_password":"keyboardcat",
                    "directories_root":"/home/ags/arcgis/server/usr/directories",
                    "setup":"/home/ubuntu/ags_binaries/ArcGIS_for_Server",
                    "authorization_file":"/home/ubuntu/authorization_file.ecp"
            },
            "portal":{
                    "domain_name":"ags0.mydomain.com",
                    "admin_username":"admin",
                    "admin_password":"keyboardcat",
                    "admin_email":"ryan.mcadler@mydomain.com",
                    "security_question":"What is your favorite color?",
                    "security_question_answer":"Green",
                    "setup":"/home/ubuntu/ags_binaries/Portal_for_ArcGIS",
                    "authorization_file":"/home/ubuntu/authorization_file.ecp"
            },
            "run_list":[
                    "recipe[arcgis::system]",
                    "recipe[java]",
                    "recipe[arcgis::authbind]",
                    "recipe[tomcat]",
                    "recipe[arcgis::server]",
                    "recipe[arcgis::server_wa]",
                    "recipe[arcgis::datastore]",
                    "recipe[arcgis::portal]",
                    "recipe[arcgis::portal_wa]",
                    "recipe[arcgis::federation]"
            ]
    }

Thanks again for your help.

**Comment by pbobov** [comment]
Ryan,

Here is how ArcGIS 10.3.1 Server setup directory looks for me after unzipping the .gz file.
```
-bash-4.1$ pwd
/bobo1/temp/pavel/ArcGISServer
-bash-4.1$ ll
total 40
drwxr-xr-x 3 ags ags  4096 Apr  3 15:20 Documentation
-rw-r--r-- 1 ags ags  1200 Apr  3 15:20 Install.htm
drwxr-xr-x 4 ags ags  4096 Feb 27 11:23 serverdiag
-rwxr-xr-x 1 ags ags 23137 Feb 27 16:05 Setup
drwxr-xr-x 4 ags ags  4096 Apr  3 15:21 setup_resources

```

For this folder structure the server setup path should be set as 

```
"server":{
...
                "setup":"/bobo1/temp/pavel/ArcGISServer/Setup",
 ..
        },
```
The cookbook just launches that Setup.

(In general, the cookbook just automates the steps described in the ArcGIS for Server installation guides. Everything it does you can also do manually.)

Thanks,
Pavel

**Comment by ryanmcadler** [comment]
Thanks Pavel,

I don't have the correct linux installs.
