### ISSUE TITLE
customize entperise role -webgis-windows

### ISSUE THREAD

**Issue by fpotempa** [Esri/arcgis-cookbook#143]
I want to only install portal, server, datastore and not WA as these are on different server. Can I adjust webgis-windows and drop those parameters?

Do I need to run separate recipes for each component?

 I've done some initial editng of the webgis-windows json file but when it runs it errors out. 
For example
[webgis-windows_1.txt](https://github.com/Esri/arcgis-cookbook/files/1783019/webgis-windows_1.txt)
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>chef-solo -j C:\chef\roles\webgis-windows.json
[2018-03-05T15:40:47-08:00] WARN: *****************************************
[2018-03-05T15:40:47-08:00] WARN: Did not find config file: C:/chef/client.rb, u
sing command line options.
[2018-03-05T15:40:47-08:00] WARN: *****************************************
Starting Chef Client, version 13.7.16
resolving cookbooks for run list: ["arcgis-enterprise::system", "arcgis-enterpri
se::server", "arcgis-enterprise::datastore", "arcgis-enterprise::portal"]
W, [2018-03-05T15:40:55.882216 #5372]  WARN -- : You are setting a key that conf
licts with a built-in method Hashie::Mash#default defined in Hash. This can caus
e unexpected behavior when accessing the key as a property. You can still access
 the key via the #[] method.
W, [2018-03-05T15:40:56.022842 #5372]  WARN -- : You are setting a key that conf
licts with a built-in method Hashie::Mash#default defined in Hash. This can caus
e unexpected behavior when accessing the key as a property. You can still access
 the key via the #[] method.
W, [2018-03-05T15:40:57.319746 #5372]  WARN -- : You are setting a key that conf
licts with a built-in method Hashie::Mash#default defined in Hash. This can caus
e unexpected behavior when accessing the key as a property. You can still access
 the key via the #[] method.
Synchronizing Cookbooks:
  - arcgis-enterprise (3.2.0)
  - hostsfile (2.4.5)
  - limits (1.0.0)
  - authbind (0.1.10)
  - iptables (1.0.1)
  - windows_firewall (3.0.2)
  - ms_dotnet (3.2.1)
  - windows (3.1.1)
  - nfs (2.3.1)
  - java_properties (0.1.3)
  - ohai (5.1.0)
  - line (0.6.3)
  - sysctl (0.8.1)
Installing Cookbook Gems:
Compiling Cookbooks...
c:/chef/local-mode-cache/cache/cookbooks/hostsfile/resources/entry.rb:35: warnin
g: constant ::Fixnum is deprecated
Recipe: arcgis-enterprise::system
  * chef_gem[multipart-post] action install (up to date)

  ==============================================================================
==
  Recipe Compile Error in c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterp
rise/recipes/server.rb
  ==============================================================================
==

  Chef::Exceptions::ValidationFailed
  ----------------------------------
  Property path must be one of: String!  You passed nil.

  System Info:
  ------------
  chef_version=13.7.16
  platform=windows
  platform_version=6.3.9600
  ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
  program_name=C:/opscode/chef/bin/chef-solo
  executable=C:/opscode/chef/bin/chef-solo

  Running handlers:
[2018-03-05T15:41:02-08:00] ERROR: Running exception handlers
  Running handlers complete
[2018-03-05T15:41:02-08:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 14 seconds
[2018-03-05T15:41:02-08:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache
/cache/chef-stacktrace.out
[2018-03-05T15:41:02-08:00] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2018-03-05T15:41:02-08:00] FATAL: Chef::Exceptions::ValidationFailed: Property
path must be one of: String!  You passed nil.

Using ChefClient 13.7.16
ArcGIS 10.6
WS 2012 R2

**Comment by pbobov** [comment]
Try to remove 'server_wa' and 'portal_wa' recipes form the run_list and set the Web Adaptor's URLs using arcgis/server/wa_url and arcgis/portal/wa_url attributes in the JSON files. 

I have not tried that configuration personally, but I believe the key here is to set the URLs correctly.

**Comment by dmusci-reancloud** [comment]
I have the same error, and all I'm trying to run is:
include_recipe "arcgis-enterprise::server"

I'm not setting any overridden attributes to nil, null, '', "", or any other value that would reasonably be expected to be interpreted as nil.  I'm attempting to install 10.4.1 on WS 2012 R2.

I'm using the latest version of the cookbook (arcgis-enterprise (3.2.0))

Given the lack of documentation by ESRI on how to use the cookbooks, is there any chance that ESRI is working to fix this?

**Comment by cameronkroeker** [comment]
With more recent cookbooks (for example v3.6.1) can define the following recipes in the run-list that will only install (does not authorize or configure/create site):

```
"run_list": [
    "recipe[arcgis-enterprise::system]",
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::install_portal]",
    "recipe[arcgis-enterprise::webstyles]",
    "recipe[arcgis-enterprise::install_server]",
    "recipe[arcgis-enterprise::install_datastore]"
  ]
```

https://github.com/Esri/arcgis-cookbook/wiki/arcgis%E2%80%90enterprise-Cookbook-Recipes#install_datastore
