### ISSUE TITLE
Clarification on URL attributes in Server deployment 

### ISSUE THREAD

**Issue by nadiaChaimae** [Esri/arcgis-cookbook#144]
"web_context_url": "https://website.domain.com/server",
  "wa_name": "server",
  "wa_url": "https://website.domain.com/arcgis",
  "url": "https://machine01.machine.com:6443/arcgis",

**Comment by cameronkroeker** [comment]
- `node['arcgis']['server']['web_context_url']` = ArcGIS server web context URL. This is used in the federation recipe for the federated server services url:
https://devtopia.esri.com/WebGIS/arcgis-automation/blob/b13452064f84c73a2f79f4be587f0e6a6ffefe3a/cookbooks/arcgis-enterprise/recipes/federation.rb#L24

- `node['arcgis']['server']['wa_name']` = The name of the Web Adaptor used for ArcGIS Server. Default name is server.
- `node['arcgis']['server']['wa_url']` = URL of the Web Adaptor used for ArcGIS Server. Default name is `https://<FQDN of the machine>/node['arcgis']['server']['wa_name']`.
- `node['arcgis']['server']['url']` = ArcGIS Server URL. The default URL is `https://<FQDN of the machine>:6443/arcgis` using the fully qualified domain name of the machine on which Chef is running. If ArcGIS Server and the web adaptor are running on different machines, then this value should be explicitly set.
