### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by vmurga** [Esri/arcgis-cookbook#148]
I'm encountering an issue during arcgic_enterprise_webadpator[Configure Web Adaptor with Portal], I'm getting the error that "The system cannot find the path specified".  It's in reference to the "C;\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe". It appears that the server web adpator has placed this file (ConfigureWebAdaptor.exe) in a different location, then stated in this error with portal.

**Comment by rwmajor2** [comment]
@vmurga So, to be clear, you are trying to configure the Web Adaptor to Portal.  Did you install the Web Adaptor with Chef?  

What does your JSON file look like?  Maybe you can set the install dir to the correct location and see if that makes a difference?
```json
{
  "arcgis": {
    "version": "10.5",
    "web_adaptor": {
      "install_dir": "c:\\correctlocation\\IIS\\Tools\\ConfigureWebAdaptor.exe",
    },
    ...

```

**Comment by vmurga** [comment]
I 'm using Chef and I did try to correct the location.

**Comment by mschoelen** [comment]
@vmurga , for that "TCP connection" error, have you tried running chef directly on the node using the `chef-client` command?

**Comment by vmurga** [comment]
To resolve the issue. I set Portal and Server up on two different machines and configured Tomcat on the Portal machine to 443. Thanks everyone.
