### ISSUE TITLE
Missing cookbooks : Could not satisfy version constraints for : esri-iis

### ISSUE THREAD

**Issue by rohansnaik** [Esri/arcgis-cookbook#151]
Hi @pbobov ,
I am getting the following error while executing the ArcGIS Enterprise recipe. Can you please help me in resolving the issue?

Missing Cookbooks:
------------------
Could not satisfy version constraints for: esri-iis

Expanded Run List:
------------------
* arcgis-enterprise::system
* esri-iis
* arcgis-enterprise::server
* arcgis-enterprise::server_wa

System Info:
------------
chef_version=13.8.5
platform=windows
platform_version=6.3.9600
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-
program_name=C:/opscode/chefdk/embedded/bin/chef-solo
executable=C:/opscode/chefdk/embedded/bin/chef-solo

**Comment by pbobov** [comment]
ArcGIS Chef cookbooks v3.2.0 and all the dependent cookbooks are packaged in https://github.com/Esri/arcgis-cookbook/releases/download/v3.2.0/arcgis-3.2.0-cookbooks.zip. You will need to extract the archive to C:\chef directory.

**Comment by rohansnaik** [comment]
@pbobov Thanks for your help. I have extracted all the cookbooks, and now getting an error - FATAL: UncaughtThrowError: uncaught throw "Unsupport
ed ArcGIS version". Here is the error log -


UncaughtThrowError
------------------
uncaught throw "Unsupported ArcGIS version"

Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/arcgis-enterprise/attributes/default.rb:81:in `throw'
  c:/chef/cache/cookbooks/arcgis-enterprise/attributes/default.rb:81:in `from_fi
le'

Relevant File Content:
----------------------
c:/chef/cache/cookbooks/arcgis-enterprise/attributes/default.rb:

 74:  end
 75:
 76:    case node['arcgis']['desktop']['version']
 77:      when '10.5.1'
 78:        default['arcgis']['desktop']['product_code'] = '{4740FC57-60FE-45BB-
B513-3309F6B73183}'
 79:        default['arcgis']['licensemanager']['product_code'] = '{DF06C3DC-54B
5-49A1-9756-B68FD65A0AD0}'
 80:      else
 81>>       throw 'Unsupported ArcGIS version'
 82:      end
 83:
 84:
 85:
 86:

System Info:
------------
chef_version=13.8.5
platform=windows
platform_version=6.3.9600
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
program_name=C:/opscode/chefdk/embedded/bin/chef-solo
executable=C:/opscode/chefdk/embedded/bin/chef-solo


Running handlers:
[2018-04-11T12:31:16+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-04-11T12:31:16+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2018-04-11T12:31:16+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stack
trace.out
[2018-04-11T12:31:16+00:00] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2018-04-11T12:31:16+00:00] FATAL: UncaughtThrowError: uncaught throw "Unsupport
ed ArcGIS version"

**Comment by pbobov** [comment]
What ArcGIS version do  you use? 
ArcGIS Chef Cookbook v3.2.0 support ArcGIS 10.4 to 10.6.
Did you set the ArcGIS version in the JSON file?
```
{
  "arcgis":{
    "run_as_password":"Run_As_Pa$$w0rd",
    "run_as_user":"arcgis",
    "version":"10.5.1",
...
}
```

**Comment by pbobov** [comment]
The dialog most likely pops up because the ArcGIS Server installation directory is not accessible. By default arcgis-enterprise Chef cookbook installs ArcGIS Server in `C:\\Program Files\\ArcGIS\\Server`.  You can change the installation directory by setting `arcgis/server/install_dir` attribute in the JSON file.

```JSON
{
  "arcgis" : {
     ...
     "server" : {
        "install_dir" : "C:\\ArcGIS",
        ...
   }
   ...
}

**Comment by pbobov** [comment]
I'm not sure what `windows-package with installation type custom`  means...

This issue probably duplicates https://github.com/Esri/arcgis-cookbook/issues/129.
