### ISSUE TITLE
Publish feature service using Chef

### ISSUE THREAD

**Issue by rohansnaik** [Esri/arcgis-cookbook#152]
@pbobov - Is it possible to publish multiple feature services using Chef? Where are the attributes for the service properties defined?I checked the arcgis server-services under the roles folder. I am trying to use connection neutral SD files for publishing of feature services, and want to avoid SDE registration.

**Comment by pbobov** [comment]
Yes it's possible to publish multiple services of any type to ArcGIS Server. I have not tried publishing feature services myself, though.

```JSON
{
  "arcgis": {
    "server": {
      "url": "https://domain.com:6443/arcgis",
      "publisher_username": "publisher",
      "publisher_password": "changeit",
      "services": [{
         "folder": "",
         "name": "MyMap1",
         "type": "MapServer",
         "definition_file": "C:\\data\\map_bv1.sd",
         "properties": {
           "maxInstancesPerNode" : 4
         } 
      }, {
         "folder": "",
         "name": "MyMap2",
         "type": "MapServer",
         "definition_file": "C:\\data\\map_bv2.sd",
         "properties": {
           "maxInstancesPerNode" : 4
         } 
      }] 
    }
  },
  "run_list": [
    "recipe[arcgis-enterprise::services]"
  ]
}
```

Service configuration properties, such as configuredState, minInstancesPerNode, maxInstancesPerNode, and all other properties can be specified by node['arcgis']['server']['services']['properties'] attribute. Chef just passes all the service properties to publish service requests on the server admin API. The recipe is not aware of the individual services' properties. 

💡  [ArcGIS Python API](https://github.com/Esri/arcgis-python-api) provides more advanced capabilities for publishing services.

**Comment by cameronkroeker** [comment]
closing since original question has been answered.
