### ISSUE TITLE
Cached Authorization File error?

### ISSUE THREAD

**Issue by jsthusker** [Esri/arcgis-cookbook#156]
I am trying to install portal but when I run my run list which only includes ['arcgis']['portal'] I get the following error and it points at line 101 in portal.rb recipe
>>   path node['arcgis']['portal']['cached_authorization_file']

FATAL: Chef::Exceptions::ValidationFailed: Property path must be one of: String!  You passed nil.

There is no mention of [cached_authorization_file'] in the portal cookbook.  I also have the ['authorization_file'] parameter populated and pointing at a valid prvc file.

Any thoughts?

**Comment by pbobov** [comment]
Can you share the chef attributes json file?

**Comment by jsthusker** [comment]
This is the role file if that is what you are looking for.  I am not sure which chef attributes json file you mean.

{
  "name": "catgispt1",
  "description": "Portal Server of CAT ArcGIS Enterprise",
  "arcgis":{
    "version":"10.6",
    "run_as_user":"stn\\sa.gis.test",
    "run_as_password":"Password",
    "cache_authorization_files": false,
    "configure_windows_firewall": false,
    "portal":{
      "domain_name": "ne.gov",
      "setup":"D:\\Install\\10.6\\PortalForArcGIS\\Setup.exe",
      "install_dir": "D:\\Program Files\\ArcGIS\\Portal",
      "authorization_file":"\\\\GISMetro\\GIS_Config\\Repository\\PortalforArcGIS_632333.prvc",
      "authorization_file_version": "10.6",
      "install_system_requirements": true,
      "configure_autostart": true,
      "data_dir": "\\\\GISMetro\\gis_config\\CATport\\arcgisportal",
      "log_dir":"D:\\arcgisportal\\logs",
      "log_level": "WARNING",
      "max_log_file_age": 90,
      "content_store_type": "fileStore",
      "content_store_provider": "FileSystem",
      "content_store_connection_string": "\\\\GISMetro\\gis_config\\CATportal\\arcgisportal\\content",
      "object_store": null,
      "url": "https://localhost:7443/arcgis",
      "private_url": "https://catgispt1.stone.ne.gov:7443/arcgis",
      "web_context_url": "https://catgispt1.stone.ne.gov/portal",
      "admin_username":"CatPortalAdmin",
      "admin_password":"password",
      "admin_email":"john.doe@somewhere.com",
      "security_question":"Street you lived on when you were 9?",
      "security_question_answer":"SomeStreetUSA",
      "keystore_file":"D:\\install\\somefile.pfx",
      "keystore_password":"Password",
	  "root_cert": "Somefile.pfx",
      "root_cert_alias": "wc_star.somewhere.com",
      "upgrade_backup": true,
      "upgrade_rollback": true
	  }
  },
  "run_list":[
    "recipe[arcgis-enterprise::portal]"
  ]
}

**Comment by pbobov** [comment]
Do you use chef server or chef-solo? These attributes are correct for chef-server role, but not correct for chef-solo.

**Comment by pbobov** [comment]
The recipe fails because arcgis/portal/cached_authorization_file attribute is not set, though the attribute should not be evaluated if arcgis/cache_authorization_files is  false.

Please set arcgis/portal/cached_authorization_file attribute to an empty string and try to run chef again.

**Comment by jsthusker** [comment]
I have my own chef server setup.  So chef-server role. 
Just tried your work around. No luck. Same error

**Comment by pbobov** [comment]
In our tests chef-server roles JSONs usually looks like this (none `default_attributes` key):

```JSON
{
  "name": "baseenterprise",
  "description": "Primary Machine of Base ArcGIS Enterprise",
  "default_attributes": {
    "arcgis": {
      "iis": {
        "keystore_file": "\\\\REPOMACHINE\\Repository\\Certificates\\wildcardcert.pfx",
        "keystore_password": "abcd.com"
      },
      "web_adaptor":{
        "admin_access":true
      },
      "server":{
	    "domain_name" : "yourdomainname",
        "wa_url": "https://yourdomainname/server",
		"private_url": "https://yourdomainname/server",
        "web_context_url": "https://yourdomainname/server",
        "admin_username":"admin",
        "admin_password":"changeit",
        "authorization_file":"\\\\REPOMACHINE\\Repository\\AuthorizationFiles\\Server106.prvc"
      },
      "portal":{
	    "domain_name" : "yourdomainname",
        "wa_url": "https://yourdomainname/portal",		
        "web_context_url": "https://yourdomainname/portal",
        "admin_username":"admin",
        "admin_password":"changeit",
        "admin_email":"admin@mydomain.com",
        "security_question":"Your favorite ice cream flavor?",
        "security_question_answer":"vanilla",
		"content_dir":"C:\\arcgisportal\\content",
        "authorization_file":"\\\\REPOMACHINE\\Repository\\AuthorizationFiles\\Portal106.prvc"
      }
    }
  },
  "run_list": [
    "recipe[arcgis-enterprise::system]",
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::portal]",
    "recipe[arcgis-enterprise::portal_wa]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::server_wa]",
    "recipe[arcgis-enterprise::datastore]",
    "recipe[arcgis-enterprise::federation]"
  ]
}
```

**Comment by jsthusker** [comment]
Chris W at ESRI told me to follow this pattern.
https://github.com/Esri/arcgis-cookbook/wiki/arcgis%E2%80%90enterprise-Cookbook-Recipes

**Comment by jsthusker** [comment]
I will try what you posted with only the portal on the run list.  I am installing all components on seperate vms.

**Comment by jsthusker** [comment]
Thank you!! The default_attributes key was the issue.

**Comment by pbobov** [comment]
The wiki pages contain JSONs for chef-solo/chef-zero. We probably should mention it there.

**Comment by jsthusker** [comment]
yes you should.  Makes it confusing even for esri staff
