### ISSUE TITLE
Portal won't install

### ISSUE THREAD

**Issue by jsthusker** [Esri/arcgis-cookbook#157]
The chef run gets to the install action and the installer never starts.  It eventually times out and gives me this error.

SystemCallError: arcgis_enterprise_portal[Configure arcgisportal service] (arcgis-enterprise::portal line 82) had an error: SystemCallError: windows_service[Portal for ArcGIS] (c:/chef/cache/cookbooks/arcgis-enterprise/providers/portal.rb line 215) had an error: SystemCallError: The specified service does not exist as an installed service. - OpenService: The specified service does not exist as an installed service.

Any Ideas?  Chef server

**Comment by pbobov** [comment]
Does the portal setup succeed if you run it on the same machine manually?

**Comment by jsthusker** [comment]
I got it to work. Thanks

**Comment by pkdavidson** [comment]
Hi Jeff
For future others, could you describe your solution path?

I'm hoping to move us to chef server at some point and would like to take advantage of your pain. 😏
Thanks!

**Comment by jsthusker** [comment]
yes look at #156 Cached Authorization File error?
I was trying to use some chef solo scripts and it isn't compatible with chef server
