### ISSUE TITLE
Datastore install can't find directory

### ISSUE THREAD

**Issue by jsthusker** [Esri/arcgis-cookbook#159]
Here is the code:
  "name": "catgisds1",
  "description": "DataStore of CAT ArcGIS Enterprise",
  "default_attributes": {
  "arcgis":{
    "version":"10.6",
    "data_store":{
      "setup":"D:\\Install\\10.6\\ArcGISDataStore\\Setup.exe",
	  "install_dir":"D:\\ProgramFiles\\ArcGIS",
	  "data_dir":"D:\\arcgisdatastore\\data",
	  "backup_dir":"D:\\arcgisdatastore\\data\\backup"
	  }
	  }
    },
  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-enterprise::datastore]"
	]
	}

And the error:
 FATAL: Errno::ENOENT: arcgis_enterprise_datastore[Install ArcGIS Data Store] (arcgis-enterprise::datastore line 73) had an error: Er
rno::ENOENT: No such file or directory @ rb_sysopen - D:\ProgramFiles\ArcGIS/framework/arcgis-data-store-config.properties

That directory doesn't exist after the installer ran.
The file in question is in D:\ProgramFiles\ArcGIS\DataStore\etc

How do I correct this?

**Comment by jsthusker** [comment]
It appears to me that it isn't respecting the "data_dir":"D:\arcgisdatastore\data", entry

**Comment by pbobov** [comment]
Try to run ArcGIS Data Store setup from command line with like this:

```
D:\Install\10.6\ArcGISDataStore\Setup.exe /qb INSTALLDIR="D:\ProgramFiles\ArcGIS" USER_NAME="<run_as_user>" PASSWORD="<run_as_password>"
```
That is how arcgis-enterprise::datastore recipe installs ArcGIS Data Store.

**Comment by pbobov** [comment]
@jsthusker I was able to reproduce the problem. 

Set  `install_dir` like this to work around it:

```
 "install_dir":"D:\\ProgramFiles\\ArcGIS\\DataStore",
```

**Comment by jsthusker** [comment]
ok thank you

**Comment by jsthusker** [comment]
I am now returning an issue with the configuring data store process. It says
STDERR: Error encountered: Machine 'https://localhost:2443/arcgis/datastoreadmin' returned an error.
But the correct url should be:
https://localhost:2443/arcgis/datastore/
Why is the admin at the end of the url?

**Comment by pbobov** [comment]
arcgis-enterprise::datastore recipe  registers the data store with server. You need to provide ArcGIS Server's domain name and admin user credentials for that (see https://devtopia.esri.com/WebGIS/arcgis-automation/wiki/arcgis%E2%80%90enterprise-Cookbook-Recipes#datastore).

I suspect that the error message you get from the Data Store configuration tool is misleading.

```JSON
{
  "arcgis": {
    "version": "10.5",
    "run_as_user": "arcgis",
    "run_as_password": "Pa$$w0rdPa$$w0rd",
    "configure_windows_firewall": false,
    "server": {
      "domain_name": "domain.com",
      "admin_username": "admin",
      "admin_password": "changeit"
    },
    "data_store": {
      "setup": "C:\\ArcGIS\\10.5\\Setups\\DataStore\\Setup.exe",
      "install_system_requirements":  true,
      "configure_autostart": true,
      "install_dir": "C:\\Program Files\\ArcGIS\\DataStore",
      "data_dir": "C:\\arcgisdatastore",
      "backup_dir": "C:\\arcgisdatastore\\backup",
      "types": "tileCache,relational,spatiotemporal",
      "preferredidentifier": "hostname"
    }
  },
  "run_list": [
    "recipe[arcgis-enterprise::datastore]"
  ]
}
```

**Comment by jsthusker** [comment]
ok thank you...I cannot reach that url btw

**Comment by pbobov** [comment]
Try accessing 'https://localhost:2443/arcgis/datastore/admin'.

**Comment by jsthusker** [comment]
{
  "error" : {
    "code" : 403,
    "message" : "Unable to process this request.",
    "details" : null
  }
}

**Comment by jsthusker** [comment]
404..Page not found

**Comment by jsthusker** [comment]
ok got it. I did have another issue.  Figured it out.  Misleading error message.

**Comment by jsthusker** [comment]
is https://devtopia.esri.com/WebGIS/arcgis-automation/wiki/arcgis%E2%80%90enterprise-Cookbook-Recipes#datastore supposed to be a public site?

**Comment by pbobov** [comment]
Here is the public URL: https://github.com/Esri/arcgis-cookbook/wiki/arcgis%E2%80%90enterprise-Cookbook-Recipes#datastore
