### ISSUE TITLE
Failed to create the site for ArcGIS 10.5.1

### ISSUE THREAD

**Issue by rohansnaik** [Esri/arcgis-cookbook#160]
![error](https://user-images.githubusercontent.com/37072193/41464799-354d7e9a-70b9-11e8-9d2f-6642e1f26650.PNG)

![capture1](https://user-images.githubusercontent.com/37072193/41464823-4d2d3e74-70b9-11e8-8893-97251d68b919.PNG)

Hi @pbobov,  I am getting the following error when I try to create a site using ArcGIS server 10.5.1 -

<Msg time="2018-06-13T12:27:42,665" type="SEVERE" code="6533" source="Admin" process="5664" thread="14" methodName="" machine="Machinaname" user="" elapsed="">Failed to create the site. com.esri.arcgis.discovery.servicelib.AGSException: java.lang.Exception: java.lang.Exception: The server was unable to access the URL 'https://Machinaname:6443/arcgis/services'. Please check your firewall and security settings. For more information, see the ArcGIS Server help topic Ports used by ArcGIS Server. You can access this topic in the table of contents by navigating to Administering ArcGIS Server &gt; Securing your ArcGIS Server site &gt; Configuring a secure environment for ArcGIS Server.</Msg>

Do I need to make any entries in IIS so that the ports are opened? I can see the ports 4000-4004 are closed.

**Comment by pkdavidson** [comment]
You need to manually open the ports needed for the installation you're performing.  For example, if a full stack install on a single machine, then open the required ports for ArcGIS Server, Portal and the Data Store prior to provisioning with Chef.  

I thought the Wiki used to mention this but I didn't see it there just now.

**Comment by rohansnaik** [comment]
Can you tell me how to open the ports manually? I thought the chef recipe takes care of opening the ports. Please guide me on the same.

**Comment by jlunse** [comment]
Did you manage to solve this? I get the same error when trying to create an ArcGIS site with 10.6.1 on a Windows Server 2012. I change the firewall to accept the following programs:

<ArcGIS Server installation location>\bin\ArcSOC.exe
<ArcGIS Server installation location>\framework\etc\service\bin\ArcGISServer.exe
<ArcGIS Server installation location>\framework\runtime\jre\bin\javaw.exe
<ArcGIS Server installation location>\framework\runtime\jre\bin\rmid.exe
 
Also added ports in the firewall: 1098, 4000-4004, 6006, 6080, 6099, and 6443.

Added arcgis user to the Administrator group.

I previously installed ArcGIS server 10.6 on a Windows Server 2012 and could create a site without any problem.

Now, I'm kind of out of ideas.

**Comment by moyoo** [comment]
Any progress ? I have faced same issue at 10.6.1 on Windows Server 2012.

**Comment by pbobov** [comment]
Please contact Esri technical support for ArcGIS installation issues not specific to Chef.
