### ISSUE TITLE
Is the process for upgrading the same as the initial install?

### ISSUE THREAD

**Issue by jsthusker** [Esri/arcgis-cookbook#164]
I have installed an multimachine enterprise on a windows environment using chef server.
Is upgrading just a matter of changing the roles to read 10.6.1 and placing the 10.6.1 software on the correct server, then re-running the same order of processes that were ran before on the initial install?

**Comment by pbobov** [comment]
To upgrade ArcGIS deployment using Chef you need to modify a few attributes in the original node.json file used for the initial deployment and rerun chef:
1.  Update ArcGIS Chef Cookbooks to v3.2.1 (the first cookbooks version that supports ArcGIS 10.6.1).
2. Change arcgis/version attribute to 10.6.1.
3. Change */authorization_file attributes to point to 10.6 licenses.
4. Change */setup attributes to point to 10.6.1 setups or add 10.6.1 self-extracted setup archives to folder specified arcgis/repository/archives attribute.
5. Rerun chef client  on the machines.

The recommended upgrade order for ArcGIS Enterprise is: Portal, Server, Data Store. For all-in-one ArcGIS Enterprise deployments,  make sure that the order of recipes in run_list is 
```

  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::portal]",
    "recipe[arcgis-enterprise::portal_wa]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::server_wa]",
    "recipe[arcgis-enterprise::datastore]",
    "recipe[arcgis-enterprise::federation]"
  ]
```

**Comment by jsthusker** [comment]
Thank you

**Comment by jsthusker** [comment]
Question on #4.  Do I have to extract ex:  (ArcGIS_Server_Windows_1061_163968.exe) prior or will the chef process do that?  Also can I set up a repository on a network share for these files and then point to where the extract goes?  Is that is what is meant by archives?

**Comment by pbobov** [comment]
Yo don't need to extract ArcGIS_Server_Windows_1061_163968.exe from the archive. Chaf will do it for you if you either:
-  You put ArcGIS_Server_Windows_1061_163968.exe file an a folder specified by arcgis/repository/archives attribute, or
- Specify the location of ArcGIS_Server_Windows_1061_163968.exe by arcgis/server/setup_archive attribute.
The default file names of the self extracted setup archives are hardcoded  in the arcgis-enterprise cookbook for each ArcGIS version supported by the cookbook.

```JSON
{
  "arcgis":{
    "run_as_password":"changeit",
    "run_as_user":"arcgis",
    "version":"10.6",
    "repository":{
      "archives":"\\\\myrepo\\Software\\Esri\\106_Final"
    },
    "web_adaptor":{
      "admin_access":true
    },
    "server":{
      "admin_username":"admin",
      "admin_password":"changeit",
      "authorization_file":"\\\\metro\\ArcGIS_Automation\\Authorization_Files\\Version10.6\\server.ecp"
    },
    "portal":{
      "admin_username":"admin",
      "admin_password":"changeit",
      "admin_email":"admin@mydomain.com",
      "security_question":"Your favorite ice cream flavor?",
      "security_question_answer":"vanilla",
      "authorization_file":"\\\\metro\\ArcGIS_Automation\\Authorization_Files\\Version10.6\\portal.ecp"
    }
  },
  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::portal]",
    "recipe[arcgis-enterprise::portal_wa]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::server_wa]",
    "recipe[arcgis-enterprise::datastore]",
    "recipe[arcgis-enterprise::federation]"
  ]
}
```

**Comment by jsthusker** [comment]
since misc.rb in the arcgis attributes was not updated for python should it be removed?  I am getting an error of unsupported ArcGIS version.

**Comment by jsthusker** [comment]
Doesn't this from install_portal.rb
````
arcgis_enterprise_portal 'Unpack Portal for ArcGIS' do
  setup_archive node['arcgis']['portal']['setup_archive']
  setups_repo node['arcgis']['repository']['setups']
 run_as_user node['arcgis']['run_as_user']
 only_if { ::File.exist?(node['arcgis']['portal']['setup_archive']) &&
            !::File.exist?(node['arcgis']['portal']['setup']) }
  if node['platform'] == 'windows'
    not_if { Utils.product_installed?(node['arcgis']['portal']['product_code']) }
  else
    not_if { EsriProperties.product_installed?(node['arcgis']['run_as_user'],
                                               node['hostname'],
                                               node['arcgis']['version'],
                                               :ArcGISPortal) }
```
require both variables?
I am getting an error still after following your pattern with [repository][archives]
I don't think it tells it were to unpack

**Comment by pbobov** [comment]
The setup archive is unpacked into node['arcgis']['repository']['setups'] folder, that by default is set to `%USERPROFILE%\\Documents`.

**Comment by jsthusker** [comment]
I am now getting an error on one of my servers.
Upgrade step 2 of 2 : Failed. REST handler inaccessible when attempting to upgrade
I imagine I would need to roll back and try again.  How do I roll back.
