### ISSUE TITLE
domain user as service account

### ISSUE THREAD

**Issue by afoxi911** [Esri/arcgis-cookbook#168]
whats the correct syntax for setting the a domain users as the service login account.

when I tried domain@username it just create a local account called domain@username

**Comment by pbobov** [comment]
Try `domain\username`.

**Comment by afoxi911** [comment]
nope. throws a lexical error when passing the json file

**Comment by pbobov** [comment]
`\` character must be escaped in JSON. Please try "domain\\username".

**Comment by mkarikari** [comment]
Im having a similar issue with 3.2 version of cookbooks. I have the run_as_user and password set, but it continues to run the arcgis components as LocalSystem when I check the windows service. Are their in prereq that must be set in order use domain\\user?

**Comment by pbobov** [comment]
Is it possible that some other application changes the windows services' logon account of "the arcgis components" to LocalSystem? I can't think of any way for the ArcGIS Chef cookbooks to do that.

**Comment by mkarikari** [comment]
I'm running these cookbooks from Chef Server, is it possible that may tie into the issue I'm having? The  windows box I'm deploying to are clean aws 2012r2 instances

**Comment by pbobov** [comment]
It's unlikely related to Chef Server.

Try to set run_as_user to a new unique local account name, for example "arcuser", run chef, and see if
- the user account is created on the machine, and 
- the windows service logon account is set to that user account.

**Comment by pbobov** [comment]
Also try to manually configure the windows service logon account to the user account  you need.

Only user accounts that have "Log on as a service" policy" can be used by windows services.

**Comment by sbrundige** [comment]
@mkarikari Were you able to resolve your issue? We're having the same issue you are on release 3.2.1 on Windows Server 2016 using a domain account as the service account. The issue (ArcGIS services being run as Local System) only occur when we deploy using Chef Server. Running chef-solo doesn't present this issue.

**Comment by Nickolaitc** [comment]
@sbrundige Could you provide the environment JSON and roles JSON you are utilizing through Chef Server?

The defaults for run_as_user is "arcgis" so it wouldn't make much sense that it would be getting assigned "localsystem" unless physically set or something else out of the ordinary: https://github.com/Esri/arcgis-cookbook/tree/v3.2.1/cookbooks/arcgis-enterprise
