### ISSUE TITLE
Failed to authorize ArcGIS server

### ISSUE THREAD

**Issue by rohansnaik** [Esri/arcgis-cookbook#169]
Hi @pbobov,

I am getting an error " Failed to authorise using the file" while authorizing the ArcGIS server, on a closed environment (without internet). I am having a valid prvc file. 
Can you please suggest if I need to make any changes to the existing recipe? I want to authorise the server automatically using Chef, and do not want to do it manually? Please suggest.

Regards.
Rohan

**Comment by pbobov** [comment]
@rohansnaik ArcGIS software authorization with a .prvc license file involves calling to the Esri license server. It will not work in a closed environment without the internet access. Please call Esri tech support and ask for a license/key-code file that does not require the internet access during software authorization.

**Comment by rohansnaik** [comment]
@pbobov Thanks for the information. A license / key code file, does it mean .**ecp** file? Also, once we get the file, can we use it directly in the Chef recipe to Authorise AGS server 10.5.1, or do we need to make any modifications in the recipe?

**Comment by cameronkroeker** [comment]
Closing since original question has been answered.
