### ISSUE TITLE
Installer opens ui when executing chef

### ISSUE THREAD

**Issue by rreilly-edr** [Esri/arcgis-cookbook#170]
Hi, I have been using chef for a long time but I am very new to arcgis. I was at the esri talk at chef conf and was excited to get our gis servers under chef management. I am attempting to install the rasterservice. I created a role with following:

```
{
  "arcgis": {
    "run_as_password": "changeit",
    "run_as_user": "arcgis",
    "version": "10.6",
    "repository": {
      "archives": "c:/temp/",
      "setups": "c:/temp/"
    },
    "server": {
      "admin_username": "arcgis",
      "admin_password": "changeit",
      "authorization_file": "/temp/ArcGISImageServer_ArcGISServer_677460.prvc",
      "setup": "/temp/ArcGIS_Server_Windows_1061_163968.exe",
      "setup_archive": "c:/temp/",
      "web_context_url": "https://gisrastdev.xx.com:6443/arcgis",
      "config_store_connection_string": "/arcgisserver/config-store",
      "is_hosting": false
    },
    "portal": {
      "wa_url": "https://my.portal.com/portal",
      "admin_username": "admin",
      "admin_password": "changeit"
    }
  },

 "run_list": [
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::federation]",
    "recipe[arcgis-enterprise::enable_rasteranalytics]"
  ]
}
``` 

however when I execute chef-client the installer opens
[https://pasteboard.co/HFqOJtA.png](https://pasteboard.co/HFqOJtA.png)
and as you can see its ignoring the attributes

**Comment by pbobov** [comment]
The "setup_archive" attribute value is invalid. Setup archive is actually a self-extracted archive that contains Setup.exe inside. Try this:

```JSON
{
  "arcgis": {
    "run_as_password": "changeit",
    "run_as_user": "arcgis",
    "version": "10.6",
    "repository": {
      "archives": "c:/temp/",
      "setups": "c:/temp/"
    },
    "server": {
      "admin_username": "arcgis",
      "admin_password": "changeit",
      "authorization_file": "/temp/ArcGISImageServer_ArcGISServer_677460.prvc",
      "setup_archive": "C:/temp/ArcGIS_Server_Windows_1061_163968.exe",
      "web_context_url": "https://gisrastdev.xx.com:6443/arcgis",
      "config_store_connection_string": "/arcgisserver/config-store",
      "is_hosting": false
    },
    "portal": {
      "wa_url": "https://my.portal.com/portal",
      "admin_username": "admin",
      "admin_password": "changeit"
    }
  },
 "run_list": [
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::federation]",
    "recipe[arcgis-enterprise::enable_rasteranalytics]"
  ]
}
```

Actually, you don't even need to set "setup_archive" attribute if you set arcgis/repository/archives attribute, and the setup archive filename is 'standard' for 10.6 (ArcGIS_Server_Windows_1061_163968.exe).

**Comment by rreilly-edr** [comment]
@pbobov  I removed the setup_archive and it is still prompting me where to extract the files.
[https://pasteboard.co/HFwzlk1.png](https://pasteboard.co/HFwzlk1.png)

**Comment by pbobov** [comment]
Did you remove  `"setup": "/temp/ArcGIS_Server_Windows_1061_163968.exe"`?

The cookbook first checks "setup" attribute, if the file (../Setup.exe) specified by this attribute is not found, it checks if the setup archive is available at the path specified by "setup_archive" attribute, and if it's not there it check the files in arcgis/repository/archives. The setup archive file name in determined by arcgis/version attribute.

**Comment by rreilly-edr** [comment]
yes, I just got it working thanks !

**Comment by ethanb1996** [comment]
> yes, I just got it working thanks !

Hi @rreilly-edr 
What was your solution? I have the same problem 

If someone can tell me the difference between  this two attribute :
node['arcgis']['repository']['archives']
node['arcgis']['repository']['setups']

**Comment by cameronkroeker** [comment]
> > yes, I just got it working thanks !
> 
> Hi @rreilly-edr
> What was your solution? I have the same problem
> 
> If someone can tell me the difference between this two attributes :
> node['arcgis']['repository']['archives']
> node['arcgis']['repository']['setups']
> 
> Thanks

Hi @ethanb1996 ,

`node['arcgis']['repository']['archives']` Is where the setup archive files reside (a path to a folder containing the setup archives, can be a local or network share location), whereas `node['arcgis']['repository']['setups']` is where the setup archives will be extracted to.

Thanks,
Cameron K.
