### ISSUE TITLE
STDERR: The system cannot find the path specified.

### ISSUE THREAD

**Issue by rreilly-edr** [Esri/arcgis-cookbook#171]
Well Close, looks like it unpacks the files but when it trys to do the install i get 
STDERR: The system cannot find the path specified.
I am not sure what dirctory it is looking for as 
```
C:\Program Files\ArcGIS\Server exists
C:\Python27 also exists
```

```
 * arcgis_enterprise_server[Setup ArcGIS Server] action install[2018-09-25T09:10:02-07:00] INFO: Processing arcgis_enterprise_server[Setup ArcGIS Server] action install (arcgis-enterprise::install_server line 53)


   ================================================================================
   Error executing action `install` on resource 'arcgis_enterprise_server[Setup ArcGIS Server]'
   ================================================================================

   Mixlib::ShellOut::ShellCommandFailed
   ------------------------------------
   Expected process to exit with [0], but received '1'
   ---- Begin output of "c:\temp\ArcGIS 10.6\ArcGISServer\Setup.exe" /qb INSTALLDIR="C:\Program Files\ArcGIS\Server" INSTALLDIR1="C:\Python27" USER_NAME="arcgis" PASSWORD="password" ----
   STDOUT:
   STDERR: The system cannot find the path specified.
   ---- End output of "c:\temp\ArcGIS 10.6\ArcGISServer\Setup.exe" /qb INSTALLDIR="C:\Program Files\ArcGIS\Server" INSTALLDIR1="C:\Python27" USER_NAME="arcgis" PASSWORD="password" ----
   Ran "c:\temp\ArcGIS 10.6\ArcGISServer\Setup.exe" /qb INSTALLDIR="C:\Program Files\ArcGIS\Server" INSTALLDIR1="C:\Python27" USER_NAME="arcgis" PASSWORD="password" returned 1

   Cookbook Trace:
   ---------------
   c:/chef/cache/cookbooks/arcgis-enterprise/providers/server.rb:237:in `block in class_from_file'

   Resource Declaration:
   ---------------------
   # In c:/chef/cache/cookbooks/arcgis-enterprise/recipes/install_server.rb

    53: arcgis_enterprise_server 'Setup ArcGIS Server' do
    54:   setup node['arcgis']['server']['setup']
    55:   install_dir node['arcgis']['server']['install_dir']
    56:   python_dir node['arcgis']['python']['install_dir']
    57:   run_as_user node['arcgis']['run_as_user']
    58:   run_as_password node['arcgis']['run_as_password']
    59:   if node['platform'] == 'windows'
    60:     not_if { Utils.product_installed?(node['arcgis']['server']['product_code']) }
    61:   else
    62:     not_if { EsriProperties.product_installed?(node['arcgis']['run_as_user'],
    63:                                                node['hostname'],
    64:                                                node['arcgis']['version'],
    65:                                                :ArcGISServer) }
    66:   end
    67:   action :install

   Compiled Resource:
   ------------------
   # Declared in c:/chef/cache/cookbooks/arcgis-enterprise/recipes/install_server.rb:53:in `from_file'

   arcgis_enterprise_server("Setup ArcGIS Server") do
     action [:install]
     default_guard_interpreter :default
     declared_type :arcgis_enterprise_server
     cookbook_name "arcgis-enterprise"
     recipe_name "install_server"
     install_dir "C:\\Program Files\\ArcGIS\\Server"
     run_as_user "arcgis"
     run_as_password "password"
     setup "c:\\temp\\ArcGIS 10.6\\ArcGISServer\\Setup.exe"
     python_dir "C:\\Python27"
     not_if { #code block }
   end

   System Info:
   ------------
   chef_version=13.6.4
   platform=windows
   platform_version=10.0.14393
   ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
   program_name=C:/opscode/chef/bin/chef-client
   executable=C:/opscode/chef/bin/chef-client

2018-09-25T09:10:02-07:00] INFO: Running queued delayed notifications before re-raising exception

unning handlers:
2018-09-25T09:10:02-07:00] ERROR: Running exception handlers
unning handlers complete
2018-09-25T09:10:02-07:00] ERROR: Exception handlers complete
hef Client failed. 4 resources updated in 01 minutes 04 seconds
2018-09-25T09:10:02-07:00] INFO: Sending resource update report (run-id: 5990a389-2636-48d1-88e7-94ab581d531a)
2018-09-25T09:10:02-07:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
2018-09-25T09:10:02-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
2018-09-25T09:10:02-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: arcgis_enterprise_server[Setup ArcGIS Server] (arcgis-enterprise::install_server line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
--- Begin output of "c:\temp\ArcGIS 10.6\ArcGISServer\Setup.exe" /qb INSTALLDIR="C:\Program Files\ArcGIS\Server" INSTALLDIR1="C:\Python27" USER_NAME="arcgis" PASSWORD="password" ----
TDOUT:
TDERR: The system cannot find the path specified.
--- End output of "c:\temp\ArcGIS 10.6\ArcGISServer\Setup.exe" /qb INSTALLDIR="C:\Program Files\ArcGIS\Server" INSTALLDIR1="C:\Python27" USER_NAME="arcgis" PASSWORD="password" ----
an "c:\temp\ArcGIS 10.6\ArcGISServer\Setup.exe" /qb INSTALLDIR="C:\Program Files\ArcGIS\Server" INSTALLDIR1="C:\Python27" USER_NAME="arcgis" PASSWORD="password" returned 1`
```

my config 

```
{
  "arcgis": {
    "run_as_password": "password",
    "run_as_user": "arcgis",
    "version": "10.6",
    "repository": {
      "archives": "c:/temp/",
      "setups": "c:/temp/"
    },
    "server": {
      "admin_username": "arcgis",
      "admin_password": "changeit",
      "authorization_file": "/temp/ArcGISImageServer_ArcGISServer_677460.prvc",
      "setup_archive": "C:/temp/ArcGIS_Server_Windows_1061_163968.exe",
      "web_context_url": "https://gisrastdev.edrnet.com:6443/arcgis",
      "config_store_connection_string": "/arcgisserver/config-store",
      "is_hosting": false
    },
    "portal": {
      "wa_url": "https://my.portal.com/portal",
      "admin_username": "admin",
      "admin_password": "changeit"
    }
  },
  "run_list": [
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::federation]",
    "recipe[arcgis-enterprise::enable_rasteranalytics]"
  ]
}
```

**Comment by pbobov** [comment]
arcgis/version attribute value must  be set to "10.6.1" if you are using 10.6.1 setup (ArcGIS_Server_Windows_1061_163968.exe).

**Comment by pbobov** [comment]
And delete `"setup_archive": "C:/temp/ArcGIS_Server_Windows_1061_163968.exe",` to check out how  the repository works.

**Comment by rreilly-edr** [comment]
@pbobov  thanks so much for the quick response, it looks like it is wokring now. I will report back here if I have any issues.

**Comment by pbobov** [comment]
The license version is missing in `C:\Program Files\ESRI\License\sysgen\keycodes`. It should be 
`C:\Program Files\ESRI\License10.6\sysgen\keycodes`.
Try to add arcgis/server/authorization_file_version attribute and set it to `10.6`.

The cookbooks sets it by default to 
```
server['authorization_file_version'] = node['arcgis']['version'].to_f.to_s 
```
I'm not sure why arcgis/server/authorization_file_version is not set in your case.

**Comment by rreilly-edr** [comment]
is it possible to not us federation ? @pbobov 

```
Recipe: arcgis-enterprise::federation
  * arcgis_enterprise_portal[Federate Server] action federate_server[2018-09-25T11:22:03-07:00] INFO: Processing arcgis_enterprise_portal[Federate Server] action federate_server (arcgis-enterprise::federation line 20)
[2018-09-25T11:42:06-07:00] INFO: Retrying execution of arcgis_enterprise_portal[Federate Server], 4 attempt(s) left
[2018-09-25T12:02:39-07:00] INFO: Retrying execution of arcgis_enterprise_portal[Federate Server], 3 attempt(s) left
```

**Comment by rreilly-edr** [comment]
I removed the federation recipe, see if that works.

**Comment by rreilly-edr** [comment]
@pbobov I removed the federation cookbook and then it runs for quite some time but fails with 

[```
2018-09-25T17:57:10-07:00] INFO: Setting server machine properties...
 (up to date)
  * arcgis_enterprise_server[Configure HTTPS] action configure_https[2018-09-25T17:57:14-07:00] INFO: Processing arcgis_enterprise_server[Configure HTTPS] action configure_https (arcgis-enterprise::server line 104)
 (skipped due to not_if)
Recipe: arcgis-enterprise::enable_rasteranalytics
  * arcgis_enterprise_portal[Enable RasterAnalytics] action enable_server_function[2018-09-25T17:57:14-07:00] INFO: Processing arcgis_enterprise_portal[Enable RasterAnalytics] action enable_server_function (arcgis-enterprise::enable_rasteranalytics line 20)


    ================================================================================
    Error executing action `enable_server_function` on resource 'arcgis_enterprise_portal[Enable RasterAnalytics]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Failed to open TCP connection to FQDN:443 (No connection could be made because the target machine actively refused it. - connect(2) for "FQDN" port 443)

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/arcgis-enterprise/libraries/portal_admin_client.rb:58:in `site_exist?'
    c:/chef/cache/cookbooks/arcgis-enterprise/providers/portal.rb:527:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/arcgis-enterprise/recipes/enable_rasteranalytics.rb

     20: arcgis_enterprise_portal "Enable RasterAnalytics" do
     21:   portal_url node['arcgis']['portal']['wa_url']
     22:   username node['arcgis']['portal']['admin_username']
     23:   password node['arcgis']['portal']['admin_password']
     24:   server_url node['arcgis']['server']['web_context_url']
     25:   server_admin_url node['arcgis']['server']['private_url']
     26:   server_username node['arcgis']['server']['admin_username']
     27:   server_password node['arcgis']['server']['admin_password']
     28:   is_hosting node['arcgis']['server']['is_hosting']
     29:   server_function 'RasterAnalytics'
     30:   action :enable_server_function
     31: end
     32:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/arcgis-enterprise/recipes/enable_rasteranalytics.rb:20:in `from_file'

    arcgis_enterprise_portal("Enable RasterAnalytics") do
      action [:enable_server_function]
      default_guard_interpreter :default
      declared_type :arcgis_enterprise_portal
      cookbook_name "arcgis-enterprise"
      recipe_name "enable_rasteranalytics"
      portal_url "https://FQDN/portal"
      username "admin"
      password "changeit"
      server_url "https://FQDN:6443/arcgis"
      server_admin_url "https://FQDN:6443/arcgis"
      server_username "arcgis"
      server_password "changeit"
      is_hosting false
      server_function "RasterAnalytics"
    end

    System Info:
    ------------
    chef_version=13.6.4
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client

[2018-09-25T18:17:17-07:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2018-09-25T18:17:17-07:00] ERROR: Running exception handlers
Running handlers complete
[2018-09-25T18:17:17-07:00] ERROR: Exception handlers complete
Chef Client failed. 6 resources updated in 23 minutes 26 seconds
[2018-09-25T18:17:17-07:00] INFO: Sending resource update report (run-id: 3d8db55a-b754-4d67-a28f-39ceef504b57)
[2018-09-25T18:17:17-07:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2018-09-25T18:17:17-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-09-25T18:17:17-07:00] FATAL: Errno::ECONNREFUSED: arcgis_enterprise_portal[Enable RasterAnalytics] (arcgis-enterprise::enable_rasteranalytics line 20) had an error: Errno::ECONNREFUSED: Failed to open TCP connection to FQDN:443 (No connecti
on could be made because the target machine actively refused it. - connect(2) for "FQDN" port 443)
PS C:\Windows\system32>






```

**Comment by pbobov** [comment]
Yes. Portal for ArcGIS is required to enable raster analysis capability in image server (see http://enterprise.arcgis.com/en/server/latest/get-started/windows/perform-raster-analysis.htm).

**Comment by cameronkroeker** [comment]
This looks to be resolved, and due to the age of the thread will mark it as closed.
