### ISSUE TITLE
Can't Configure ArcGIS Data Store

### ISSUE THREAD

**Issue by Murkor** [Esri/arcgis-cookbook#172]
While using recipes to install arcgis enterprise, federation fails. Version Enterprise 10.5.1.
Portal + portal_wa, Server + server_wa works properly (but not federate)
DataStore well installed.  OS windows server 2012.

after 5 tries:

Hudson.ingenieria.esri.cl     # Declared in c:/chef/cache/cookbooks/arcgis-enterprise/recipes/datastore.rb:40:in `from_file'
Hudson.ingenieria.esri.cl
Hudson.ingenieria.esri.cl     arcgis_enterprise_datastore("Configure ArcGIS Data Store") do
Hudson.ingenieria.esri.cl       action [:configure]
Hudson.ingenieria.esri.cl       default_guard_interpreter :default
Hudson.ingenieria.esri.cl       declared_type :arcgis_enterprise_datastore
Hudson.ingenieria.esri.cl       cookbook_name "arcgis-enterprise"
Hudson.ingenieria.esri.cl       recipe_name "datastore"
Hudson.ingenieria.esri.cl       install_dir "C:\\Program Files\\ArcGIS\\DataStore"
Hudson.ingenieria.esri.cl       run_as_user "HUDSON\\Administrador"
Hudson.ingenieria.esri.cl       data_dir "D:\\enterprise\\arcgisdatastore"
Hudson.ingenieria.esri.cl       types "tileCache,relational"
Hudson.ingenieria.esri.cl       server_url "https://hudson.ingenieria.esri.cl:6443/arcgis"
Hudson.ingenieria.esri.cl       username "Administrador"
Hudson.ingenieria.esri.cl       password "EsriChile2014"
Hudson.ingenieria.esri.cl       retries 5
Hudson.ingenieria.esri.cl       retry_delay 60
Hudson.ingenieria.esri.cl     end
Hudson.ingenieria.esri.cl
Hudson.ingenieria.esri.cl     System Info:
Hudson.ingenieria.esri.cl     ------------
Hudson.ingenieria.esri.cl     chef_version=14.5.33
Hudson.ingenieria.esri.cl     platform=windows
Hudson.ingenieria.esri.cl     platform_version=6.3.9600
Hudson.ingenieria.esri.cl     ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
Hudson.ingenieria.esri.cl     program_name=C:/opscode/chef/bin/chef-client
Hudson.ingenieria.esri.cl     executable=C:/opscode/chef/bin/chef-client
Hudson.ingenieria.esri.cl
Hudson.ingenieria.esri.cl [2018-09-27T12:25:53-03:00] INFO: Running queued delayed notifications before re-raising exception
Hudson.ingenieria.esri.cl
Hudson.ingenieria.esri.cl [2018-09-27T12:25:54-03:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: arcgis_enterprise_datastore[Configure ArcGIS Data Store] (arcgis-enterprise::datastore line 40) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
Hudson.ingenieria.esri.cl ---- Begin output of "C:\Program Files\ArcGIS\DataStore/tools\configuredatastore" "https://hudson.ingenieria.esri.cl:6443/arcgis/admin" "Administrador" "EsriChile2014" "D:\enterprise\arcgisdatastore" --stores tileCache,relational ----
Hudson.ingenieria.esri.cl STDOUT: Configuring data store(s). It may take a few minutes. Please wait...
Hudson.ingenieria.esri.cl STDERR: Error encountered: Machine 'https://localhost:2443/arcgis/datastoreadmin' returned an error. 'Se ha producido un error al intentar configurar el data store.. Extended error message: Se ha producido un error al intentar configurar el data store.. Extended error messa
ge: Se ha producido un error al intentar configurar el data store.. Extended error message: Fallo al conceder el permiso del archivo.'
Hudson.ingenieria.esri.cl ---- End output of "C:\Program Files\ArcGIS\DataStore/tools\configuredatastore" "https://hudson.ingenieria.esri.cl:6443/arcgis/admin" "Administrador" "EsriChile2014" "D:\enterprise\arcgisdatastore" --stores tileCache,relational ----
Hudson.ingenieria.esri.cl Ran "C:\Program Files\ArcGIS\DataStore/tools\configuredatastore" "https://hudson.ingenieria.esri.cl:6443/arcgis/admin" "Administrador" "EsriChile2014" "D:\enterprise\arcgisdatastore" --stores tileCache,relational returned 1
ERROR: Failed to execute command on Hudson.ingenieria.esri.cl return code 1

When try manually : 

C:\Program Files\ArcGIS\DataStore\tools>configuredatastore.bat "https://hudson.ingenieria.esri.cl:6443/arcgis/admin"  Administrador EsriChile2014 d:\enterprise\arcgisdatastore  --stores tileCache,relational

Configuring data store(s). It may take a few minutes. Please wait...

Error encountered: Machine 'https://localhost:2443/arcgis/datastoreadmin' returned an error. 'Se ha producido un error al intentar configurar el data store.. Extended error message: Se ha producido un error al intentar configurar el data store.. Extended error message: Se ha producido un error al intentar configurar el data store.. Extended error message: Fallo al conceder el permiso del archivo.'

Se ha producido un error al intentar configurar el data store=**An error occurred while trying to configure the data store**
Fallo al conceder el permiso del archivo = **Failed to grant file permission**

when try using the wizard:
![image](https://user-images.githubusercontent.com/5073895/46159345-77f01980-c256-11e8-967a-16502f81dee4.png)

role file:
{
  "name": "webgis-windows-cl",
  "description":"Ejemplo WEBGIS ESRI CHILE",
  "default_attributes": {
  "arcgis":{
    "run_as_user":"HUDSON\\Administrador",
    "run_as_password":"EsriChile2014",
    "version":"10.5.1",
    "iis":{
      "keystore_file":"D:\\Setups\\Licencias\\certificadoInterno.pfx",
      "keystore_password":"12345"
    },
    "web_adaptor":{
      "setup":"D:\\Setups\\wa\\setup.exe",
      "admin_access":true
    },
    "data_store":{
      "setup":"D:\\Setups\\DataStore\\Setup.exe"
    },
    "server":{
      "domain_name" : "hudson.ingenieria.esri.cl",
      "admin_username":"Administrador",
      "admin_password":"EsriChile2014",
      "setup":"D:\\setups\\arcgisserver\\Setup.exe",
      "authorization_file":"D:\\Setups\\licencias\\ags1051.ecp"},

    "portal":{
      "admin_username":"Administrador",
      "admin_password":"EsriChile2014",
      "admin_email":"fhernandez@esri.cl",
      "domain_name":"hudson.ingenieria.esri.cl",
      "security_question":"Your favorite ice cream flavor?",
      "security_question_answer":"vanilla",
      "content_dir":"D:\\enterprise\\arcgisportal\\content",
      "setup":"D:\\Setups\\Portal\\Setup.exe",
      "authorization_file":"D:\\Setups\\licencias\\Portal1051.prvc",
      "keystore_file":"D:\\Setups\\Licencias\\certificadoInterno.pfx",
      "keystore_password":"12345"
    }
  }},
"run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::portal]",
    "recipe[arcgis-enterprise::portal_wa]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::server_wa]",
    "recipe[arcgis-enterprise::datastore]",
    "recipe[arcgis-enterprise::federation]"
   
  ]
}
![image](https://user-images.githubusercontent.com/5073895/46160491-3b71ed00-c259-11e8-9bad-939f3576af0f.png)

**Comment by pbobov** [comment]
Does `HUDSON\Administrador` domain user account have full access to `D:\enterprise\arcgisdatastore` folder on the machine?

**Comment by Murkor** [comment]
Pbobov.  Thanks,

Yes, Hudson\Administrador has full control on that folder AND EVERYONE as well

**Comment by Murkor** [comment]
![image](https://user-images.githubusercontent.com/5073895/46163790-7debf780-c262-11e8-97b7-e996e5d27aee.png)

![image](https://user-images.githubusercontent.com/5073895/46163842-aaa00f00-c262-11e8-800e-1ec071b3f122.png)

**Comment by pbobov** [comment]
I'm not sure what can cause this issue. Please call Esri tech support.

**Comment by Murkor** [comment]
ok, I'll open an incident.

**Comment by jhevenor** [comment]
Has there been progress on this issue. I get a similar looking failure when I hit the datastore. 5 attempts 

>arcgis_enterprise_datastore[Configure ArcGIS Data Store] (arcgis-enterprise::datastore line 40) had an error: ...
> Extended error message: Attempt to configure data store failed..

**Comment by Cjones252** [comment]
I too am having the same issue. Any update?

**Comment by amantere** [comment]
In role config file in "data store" node, there was no setting for data_dir, like this:
"data_store":{
"setup":"D:\Setups\DataStore\Setup.exe",
"data_dir":"F:\\ArcGIS\\datastore"
},
This might cause issues (at least when installing data store apart from ArcGIS server), since without this setting data store configurator does not find it's local settings.

**Comment by cdflint** [comment]
I am noticing that this issue may be a result of an improperly concatenated url "https:/localhost:2443/arcgis/datastoreadmin" in particular.   I cannot find where the recipe is assigning this particular variable by default.  if you go to the datastore assignment page on the server it is https://localhost:2443/arcgis/datastore without any admin at the end.  So if there is an overrride variable like with arcgis server and portal where you can assign the domain, private_url etc. that appears to be the solution here.

**Comment by Ioetre** [comment]
I got the same error: Fallo al conceder el permiso del archivo (Failed to grant file permission)

**Solution:** 

1. Uninstall ArcGIS Datastore 
2. Delete folder C: \ arcgisdatastore 
3. Delete C: \ Program Files \ ArcGIS \ DataStore folder 
4. Open the firewall ports for ArcGIS Datastore that indicates the documentation for your installation 
5. Do not use the xml file generated when the arcgis
6. Write the arcgis account, and its password twice as requested by the installation window
7. Follow all installation steps and you will no longer get the error

**Comment by cameronkroeker** [comment]
This should no longer be an issue. Please try with latest cookbooks v3.6.1.
