### ISSUE TITLE
Enabling features on Windows Server 2016 on Azure

### ISSUE THREAD

**Issue by jhevenor** [Esri/arcgis-cookbook#173]
Hi,
I'm just getting started with Chef, but I like its potential. I'm working on automating our deployment of a fairly large ArcGIS Enterprise platform. I'm following the "Deploy-a-full-stack-ArcGIS-Enterprise-on-a-single-machine" to get my feet wet. My first attempt went as follows:

- Install ChefDK on machine VM-WRK
- Sign up for hosted Chef Server
- Configure Esri Cookbooks in Berksfile and upload
```
cookbook 'arcgis-enterprise',  "~> 3.2.1", github: 'Esri/arcgis-cookbook', rel: "cookbooks/arcgis-enterprise"
cookbook 'esri-iis',  "~> 0.1.1", github: 'Esri/arcgis-cookbook', rel: "cookbooks/esri-iis"
```
- Bootstrap the node VM-NODE to the most recent compatible chef-client. (No 14.x support?)
- Edit the sample role from the blog referenced and add my details (role name webgis-windows)

When I use _knife winrm_ to apply the role to apply the role I get errors from *esri-iis* when attempting to enable features on the remote node. The error says:

>Chef::Exceptions::NoSuchResourceType: windows_feature[Web-Asp-Net] (esri-iis::default line 33) had an error: 
>    Chef::Exceptions::NoSuchResourceType: Cannot find a resource for windows_feature_dism on windows version 10.0.14393

I assume this is related to Server 2016 not being supported yet.

I did try configuring overrides for the [iis][features] array assuming the wrong feature list was being selected. No change.

I then tried updating _esri-iis\recipes\default.rb_ to use powershell instead of the windows_feature resource with some success --  the script moves on to the arcgis-enterprise cookbook now. I'm not familiar enough with Chef/Ruby to know if this is a good idea. My patch looks like:

```
node['arcgis']['iis']['features'].each do |feature|
  powershell_script "Install #{feature}" do
    code "Add-WindowsFeature #{feature}"
    guard_interpreter :powershell_script
    not_if "(Get-WindowsFeature -Name #{feature}).Installed"
  end
end
```

I should note for reference what my platform looks like:

> "platform_version": "10.0.14393",
> "os_info""product_type": 3,

This chef::windows issue looks relevant: https://github.com/chef/chef/issues/7177

**Comment by pbobov** [comment]
Windows Server 2016  is supported by ArcGIS Chef Cookbooks. I suspect the problem is caused by the new version of `windows` cookbook pulled by Berkshelf. That version probably is not compatible with esri-iis cookbook. In our tests we use `windows` cookbook version 4.1.4 with esri-iis cookbook. 

Chef Client 14 deprecates many features of old windows cookbook versions.

**Comment by jhevenor** [comment]
So I should limit the version of _windows_ to 4.1.4?

**Comment by pbobov** [comment]
@jhevenor Yes. Please try locking the windows cookbook version to 4.1.4. 

We will add support for Chef Client 14 and update the _windows_ cookbook dependency in the next release of ArcGIS Chef Cookbooks.

**Comment by cameronkroeker** [comment]
please try latest cookbook release v3.6.1, it supports Chef client 14+ and uses windows cookbook 5.3.
