### ISSUE TITLE
SSL Protocol configuration

### ISSUE THREAD

**Issue by arash8m** [Esri/arcgis-cookbook#183]
I've deployed Server and Portal with the same SSL bundle pfx that includes root certs. (this is a wildcard cert)

On the Server admin page, I see it's configured automatically with SSL Protocols TLSv1.2 and TLSv1.1.
On the Portal admin page, SSL Protocols value is not even set. (bug perhaps?)

Question: Is is possible to easily set both Portal and Server to TLSv1.2 only, and with the proper Cipher Suites?

**Comment by pbobov** [comment]
So far arcgis-enterprise cookbook does support updating SSL certificate on Portal and Server, but it does not support configuring specific TLS versions, which is supported by Portal admin REST API (see https://developers.arcgis.com/rest/enterprise-administration/portal/update-web-server-certificate.htm).

**Comment by arash8m** [comment]
Thanks. I will add the changes to PortalAdminClient library to do what I need. This issue can be closed, but I will leave it open if you're planning to add support for this in the new release.

**Comment by cameronkroeker** [comment]
this is fixed in v3.5.0.
