### ISSUE TITLE
Web adaptor uninstallation prompt

### ISSUE THREAD

**Issue by cadams84** [Esri/arcgis-cookbook#185]
Is there a way to suppress the warning when the web adaptor is uninstalled? The prompt is to restart the computer:

![image](https://user-images.githubusercontent.com/17182158/49580137-23e46e00-f946-11e8-8451-ecab869e8c37.png)

**Comment by pbobov** [comment]
I've never seen this popup before. What OS is that?

**Comment by cadams84** [comment]
Windows Server 2012 R2. I've now run the uninstall on several ArcGIS Server and Portal installs with the web adaptor and do not always get prompted. I will continue to test.

**Comment by pbobov** [comment]
I know that Windows Server 2012 requires restart after installing IIS, while Windows Server 2012 R2 does not. But I did not know that Web Adaptor pops up this message.
