### ISSUE TITLE
GeoEvent Install Upgrade

### ISSUE THREAD

**Issue by mkarikari** [Esri/arcgis-cookbook#194]
Does GeoEvent use the same repository attribute as seen under the arcgis tag, or does it have to be explicitly defined under the geoevent tag?

I noticed that when I try to run the geoevent install as a seperate role with same repository archive as other installs it skips the "unpacking" step. Below is copy of my environment config along with the role

{
  "name": "stg",
  "description": "Testing Stg Chef Deployments",
  "default_attributes": {
    "arcgis": {
      "run_as_password": "xxxx",
      "run_as_user": "dev\\xxxx",
      "version": "10.6.1",
	  "cache_authorization_file": false,
	  "repository":{
		"archives":"\\\\xxx\\gis\\software\\1061",
		"setups":"E:\\Installs"
		},
	 "python":{
		"install_dir":"E:\\Python27"
	  },
	 "desktop":{
		"setup_archive":"\\\\xxxx\\gis\\software\\1061\\ArcGIS_Desktop_1061_163864.exe"
    },
	 "server":{
      "admin_username":"xxxx",
      "admin_password":"xxxx",
	  "directories_root":"E:\\share\\arcgisserver",
	  "install_dir":"E:\\Programs\\ArcGIS\\Server",
	  "authorization_file_version":"10.6",
   	  "authorization_file":"\\\\XXX\\gis\\software\\_licenses\\1061\\ArcGISGISServerAdvanced_XXX.prvc"
	},
	 "geoevent":{
      "authorization_file":"\\\\xxx\\gis\\software\\_licenses\\1061\\ArcGISGeoEventServer_ArcGISServer_XXX.prvc"
    }
    }
  }
}

Role

`{
  "name": "arcgis-geoevent_1061",
  "description": " GeoEvent",
  "default_attributes": {
  
  },
  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-geoevent]"
  ]
}`

Because its skips the unpacking it fails on reading from the install directory since it never exported it

**Comment by mkarikari** [comment]
Appreciate clearing that up for me. After making that adjustment it move forward but then returned the following error later in the run

"A required privilege is not held by the client. - CreateProcessAsUserW (User 'XXX' must hold the 'Replace a process level token' and 'Adjust Memory Quotas for a process' permissions. Logoff the user after adding this right to make it effective.)"

the user account running the knife winrm command is a domain account which i also included in the admin group of the server just to be sure. Can you provide context for where it thinks it need additonal permission?

**Comment by pbobov** [comment]
If you run chef client using WinRM, make sure that the chef's user account can access the network share from a process launched by WinRM.

Knife has flag “—winrm-shell elevated” that helps to workaround problems with WinRM delegation (
See https://github.com/chef/knife-windows#winrm-shell)
