### ISSUE TITLE
Patching cookbook

### ISSUE THREAD

**Issue by mkarikari** [Esri/arcgis-cookbook#197]
Does the patch cookbook have logical included to skip patch installs that dont apply, if they arent on the server?
Use case being:  patch repo contains all patches for ArcGIS enterprise, but i have Portal, ArcGIS Server, Datastore on different machines.

will cookbook attempt to apply all the patches the folder or select the ones designated for the application hosted on the server?

**Comment by azinsharaf** [comment]
@mkarikari  My understanding is that `patch `recipe installs all MSP files existing on a folder (['arcgis']['repository']['patches']). You might manage the folders separately since you have installed each product on separate server. @pbobov can confirm this.

**Comment by cameronkroeker** [comment]
Hi @mkarikari and @azinsharaf,

We have made improvements to patching ArcGIS Enterprise in [Chef Cookbooks for ArcGIS v4.0.0](https://github.com/Esri/arcgis-cookbook/releases/tag/v4.0.0). The cookbooks can now be used to download and install ArcGIS Enterprise patches on both Windows and Linux.

**For more details check out:**
https://esri.github.io/arcgis-cookbook/tutorials/arcgis-enterprise-base-patches/4.0.0.html
