### ISSUE TITLE
ArcGIS 10.7

### ISSUE THREAD

**Issue by azinsharaf** [Esri/arcgis-cookbook#201]
ArcGIS 10.7 will be released on March. How long after the official release its cookbook is available?

**Comment by pbobov** [comment]
The ArcGIS Chef cookbooks will be released at the same time as  ArcGIS 10.7 release.

**Comment by pbobov** [comment]
ArcGIS Chef cookbooks v3.3.0 released a few days ago support ArcGIS 10.7.
