### ISSUE TITLE
export user configuration to file during install

### ISSUE THREAD

**Issue by kevlam** [Esri/arcgis-cookbook#202]
ArcGIS Server and some other ArcGIS Enterprise products allow us to export the encrypted user configuration to an xml file which can be imported later to other ArcGIS Enterprise products.  The silent install command to export the user configuration during install is something like this 

<path to the ArcGIS Server setup download>\setup.exe /qb EXPORTCONFIG=Yes CONFIGPATH=\\networkmachine\serverconfigs\standardaccount.xml 

I would suggest adding an option (CONFIGPATH) into the cookbook will make it easier for us who want to reuse the same user account for other ArcGIS Enterprise products.

   "server":{
      "admin_username":"admin_name",
      "admin_password":"admin_password",
      "setup":"c:\\myServer\\Setup.exe",
      "authorization_file":"c:\\myServer\\server.ecp",
      "CONFIGPATH":"c:\\myServer\\ServerConfig.xml"
    },

So, if CONFIGPATH value is empty or there's no CONFIGPATH in the cookbook then it means we don't want to export the user configuration. It will behave exactly like what we have now.

**Comment by cameronkroeker** [comment]
This feature has been added to v3.5.0 cookbooks. Use the "setup_options" parameters:

`node['arcgis']['server']['setup_options'] = Additional ArcGIS Server setup command line options. Default options are ''`

`node['arcgis']['portal']['setup_options'] = Additional Portal for ArcGIS setup command line options. Default options are ''`

`node['arcgis']['data_store']['setup_options'] = Additional ArcGIS Data Store setup command line options. Default options are ''.`

**Example usage:**

```
"server":{
      "admin_username":"<username>",
      "admin_password":"<password>",
      "setup":"\\\\fileshare\\ArcGIS_Server\\Setup.exe",
      "authorization_file":"\\\\fileshare\\authorization_files\\server.prvc",
      "setup_options":"EXPORTCONFIG=Yes CONFIGPATH=<full path and name of portal configuration file>"
    },
```
