### ISSUE TITLE
ArcGIS Enterprise HA Cookbook

### ISSUE THREAD

**Issue by delatitude** [Esri/arcgis-cookbook#203]
I've found a [cookbook](https://github.com/Esri/arcgis-cookbook/wiki/Using-ArcGIS-Chef-Cookbook-to-deploy-highly-available-base-ArcGIS-Enterprise-deployment-on-Windows ) that allows installation of ArcGIS Enterprise with High Availability (HA) on two servers (Primary & Secondary).  This cookbook is uploaded 2 years ago.  Is this still valid for the current versions 10.6.1 or 10.7 ? 

"[webgis-windows-ha-primary.json](https://github.com/Esri/arcgis-cookbook/blob/master/roles/webgis-windows-ha-primary.json)" was last updated 2 years back in March 2017.

Please advise. Thanks.

**Comment by pbobov** [comment]
Updates JSON examples for 10.7 will be released in a few days with ArcGIS Chef Cookbooks v3.3.0.

**Comment by azinsharaf** [comment]
but it is still valid for 10.6.1?

**Comment by cameronkroeker** [comment]
Hi @azinsharaf,

For 10.6.1 you will want to first deploy webgis-windows-ha-primary.json and will need to use the [3.2.1 cookbook](https://github.com/Esri/arcgis-cookbook/releases/tag/v3.2.1). Then on the second machine deploy the webgis-windows-ha-secondary.json.

For 10.7 you will need to use the latest [cookbook 3.3](https://github.com/Esri/arcgis-cookbook/releases/tag/v3.3.0). Along with the arcgis-enterprise-windows-ha-primary.json on the first machine then the second machine arcgis-enterprise-windows-ha-secondary.json.

Regards,
Cameron
