### ISSUE TITLE
Parameters for arcgis server security recipe

### ISSUE THREAD

**Issue by sandritaD** [Esri/arcgis-cookbook#206]
Who already used the the recipe arcgis-server-windows-security for BUILTIN security?
What are the possible parameters in this case for role_store_config and user_store_config and is it possible to create roles and users with this recipe?

{
  "arcgis": {
    "server": {
      "url": "https://localhost:6443/arcgis",
      "admin_username": "siteadmin",
      "admin_password": "test111",
      "security": {
        "user_store_config" : {
          "type" : "BUILTIN", 
          "properties" : {
          }
        },
        "role_store_config" : {
          "type" : "BUILTIN", 
          "properties" : {
        },
        "privileges" : {
          "PUBLISH" : [], 
          "ADMINISTER" : []
        }
      }
    }
  },
  "run_list": [
    "recipe[arcgis-enterprise::server_security]"
  ]
}

**Comment by pbobov** [comment]
Here is a JSON:

```JSON
{
  "arcgis":{
    "run_as_password":"Run_As_Pa$$w0rd",
    "run_as_user":"arcgis",
    "version":"10.7",
    "server":{
      "admin_username":"admin",
      "admin_password":"changeit",
      "directories_root":"C:\\arcgisserver",
      "setup":"C:\\ArcGIS\\10.7\\ArcGIS_Server\\Setup.exe",
      "authorization_file":"C:\\ArcGIS\\10.7\\Authorization_Files\\Server_Ent_Adv.prvc",
      "security": {
        "user_store_config": {
          "type": "WINDOWS", 
          "properties": {
            "adminUser": "ags",
            "adminUserPassword": "Pa$$w0rd"
          }
        },
        "role_store_config": {
          "type": "WINDOWS", 
          "properties": {
            "adminUser": "ags",
            "adminUserPassword": "Pa$$w0rd"
          }
        },
        "privileges": {
          "PUBLISH" : [],
          "ADMINISTER": ["ags"]
        }
      }
    }
  },
  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::server_security]"
  ]
}
```

**Comment by pbobov** [comment]
Chef passes values of user_store_config and role_store_config attributes to userStoreConfig and roleStoreConfig request parameters in POST request to /arcgis/admin/security/config/updateIdentityStore resource described at https://developers.arcgis.com/rest/enterprise-administration/server/updateidentitystore.htm.
