### ISSUE TITLE
Can we use Cookbook 3.3.0 for ArcGIS Enterprise 10.6.1 installation?

### ISSUE THREAD

**Issue by azinsharaf** [Esri/arcgis-cookbook#208]
Can we use Cookbook 3.3.0 for ArcGIS Enterprise 10.6.1 installation? I see `Dropped support for ArcGIS Enterprise versions prior to 10.7`

**Comment by cameronkroeker** [comment]
@azinsharaf 

That is correct, support for 10.6.1 and previous has been dropped in [cookbook 3.3](https://github.com/Esri/arcgis-cookbook/releases/tag/v3.3.0). For 10.6.1 will need to use cookbook [v3.2.1.](https://github.com/Esri/arcgis-cookbook/releases/tag/v3.2.1)
