### ISSUE TITLE
ArcGIS Pro 2.3 with EXE file

### ISSUE THREAD

**Issue by dird-hyang** [Esri/arcgis-cookbook#212]
Trying to use Chef cookbook 3.3 to install ArcGIS pro 2.3 on Windows Server 2016, hit error with msiexec runs EXE installation file.
My Chef client version is:14.11.21

The error message is"  
Recipe: arcgis-pro::default
  * arcgis_pro_pro[Verify ArcGIS Pro system requirements] action system (up to date)
  * arcgis_pro_pro[Unpack ArcGIS Pro Setup] action unpack (skipped due to only_if)
  * arcgis_pro_pro[Install ArcGIS Pro] action install

================================================================================
    Error executing action `install` on resource 'arcgis_pro_pro[Install ArcGIS Pro]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1620'
    ---- Begin output of msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb ----
    STDOUT: T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     C o n t a c t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W i n d o w s   I n s t a l l e r   p a c k a g e .
    STDERR:
    ---- End output of msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb ----
    Ran msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb returned 1620"

The following is the role file(arcgis-pro.json) used:
{
  "arcgis":{
    "pro":{
      "version":"2.3",
      "setup":"D:\\ArcGIS\\sources\\ArcGISPro_23_167023.exe",
	  "install_dir":"D:\\Program Files\\ArcGIS\\Pro",
	  "allusers":"1",
	  "software_class":"Professional",
	  "authorization_type":"CONCURRENT_USE",
	  "esri_license_host":"CBR1GIS4"
    }
  },
  "run_list":[
    "recipe[arcgis-pro]"
  ]
}

My question is where to get the Pro 2.3's MSI file. The EXE file was downloaded through my.esri site.

Thanks
Helen

**Comment by azinsharaf** [comment]
I see two problems in your json file: 
1- instead of "setup" parameter use can use [`'arcgis']['pro']['setup_archive']` parameter EXE file. 
sth like this:

```
"arcgis":{
    "pro":{
       "setup_archive":"D:\]ArcGIS\sources\\ArcGISPro_23_167023.exe""
```

2- Use \\ instead of \.

**Comment by dird-hyang** [comment]
Thanks for the advise. I am completely new to Chef. This is very helpful.

I have updated the role file, see below.
now I run into the problem that chef runs everything from cache, even though I  deleted the c:\chef\local-mode-cache\chef folder. How can I clear the cache from memory?

The new role file:
{
  "arcgis":{
    "repository":{
	  "setups":"D:\\sources\\Esri"
	  "archives":"D:\\sources\\Esri",
	  "patches":"D:\\sources\\Esri\\Patches"
	}
	"patches":{ 
	  "local_patch_folder":"D:\\sources\\Esri\\Patches"
	},
    "pro":{
      "version":"2.3",
	  "setup_archive":"D:\\sources\\Esri\\ArcGISPro_23_167023.exe",
	  "install_dir":"D:\\Program Files\\ArcGIS\\Pro",
	  "allusers":"1",
	  "software_class":"Professional",
	  "authorization_type":"CONCURRENT_USE",
	  "esri_license_host":"CBR1GIS4"
    }
  },
  "run_list":[
    "recipe[arcgis-pro]",
	"recipe[arcgis-pro::patches"
  ]
}

**Comment by dird-hyang** [comment]
this is the full output from the PS window.
PS C:\chef> chef-solo -j c:\chef\roles\arcgis-pro.json
[2019-04-09T16:59:13+10:00] WARN: No config file found or specified on command line, using command line options.
[2019-04-09T16:59:13+10:00] WARN: *****************************************
[2019-04-09T16:59:13+10:00] WARN: Did not find config file: C:/chef/client.rb, using command line options.
[2019-04-09T16:59:13+10:00] WARN: *****************************************
Starting Chef Client, version 14.11.21
resolving cookbooks for run list: ["arcgis-pro"]
Synchronizing Cookbooks:
  - arcgis-pro (3.3.0)
  - arcgis-repository (3.3.0)
  - windows (4.1.4)
  - aws (7.3.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 4 resources
Recipe: arcgis-pro::default
  * arcgis_pro_pro[Verify ArcGIS Pro system requirements] action system (up to date)
  * arcgis_pro_pro[Unpack ArcGIS Pro Setup] action unpack (skipped due to only_if)
  * arcgis_pro_pro[Install ArcGIS Pro] action install

    ================================================================================
    Error executing action `install` on resource 'arcgis_pro_pro[Install ArcGIS Pro]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1619'
    ---- Begin output of msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb ----
    STDOUT: T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     V e r i f y   t h a t   t h e   p a c k a g e   e x i s t s   a n d   t h a t   y o u   c a n   a c c e s s   i t ,   o r   c o n t a c t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W i n d o w s   I n s t a l l e r   p a c k a g e .
    STDERR:
    ---- End output of msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb ----
    Ran msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb returned 1619

    Resource Declaration:
    ---------------------
    # In c:/chef/local-mode-cache/cache/cookbooks/arcgis-pro/recipes/default.rb

     33: arcgis_pro_pro 'Install ArcGIS Pro' do
     34:   setup node['arcgis']['pro']['setup']
     35:   install_dir node['arcgis']['pro']['install_dir']
     36:   not_if { Utils.product_installed?(node['arcgis']['pro']['product_code']) }
     37:   action :install
     38: end
     39:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/local-mode-cache/cache/cookbooks/arcgis-pro/recipes/default.rb:33:in `from_file'

    arcgis_pro_pro("Install ArcGIS Pro") do
      action [:install]
      default_guard_interpreter :default
      declared_type :arcgis_pro_pro
      cookbook_name "arcgis-pro"
      recipe_name "default"
      setup "D:\\sources\\1.ArcGISPro_23_167023.exe"
      install_dir "D:\\Program Files\\ArcGIS\\Pro"
      not_if { #code block }
    end

    System Info:
    ------------
    chef_version=14.11.21
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-solo
    executable=C:/opscode/chef/bin/chef-solo


Running handlers:
[2019-04-09T16:59:41+10:00] ERROR: Running exception handlers
Running handlers complete
[2019-04-09T16:59:41+10:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 25 seconds
[2019-04-09T16:59:41+10:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-04-09T16:59:41+10:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-04-09T16:59:41+10:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: arcgis_pro_pro[Install ArcGIS Pro] (arcgis-pro::default line 33) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1619'
---- Begin output of msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb ----
STDOUT: T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     V e r i f y   t h a t   t h e   p a c k a g e   e x i s t s   a n d   t h a t   y o u   c a n   a c c e s s   i t ,   o r   c o n t a c t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W i n d o w s   I n s t a l l e r   p a c k a g e .
STDERR:
---- End output of msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb ----
Ran msiexec.exe /i "D:\sources\1.ArcGISPro_23_167023.exe" ALLUSERS=1 Portal_List= ESRI_LICENSE_HOST=CBR1GIS4 AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional BLOCKADDINS=#0 INSTALLDIR="D:\Program Files\ArcGIS\Pro" /qb returned 1619
PS C:\chef>

**Comment by cameronkroeker** [comment]
@dird-hyang 

I recommend renaming the following two folders:

- C:\chef\nodes
- C:\chef\local-mode-cache

Then when chef is re-ran it will recreate them.

**Comment by azinsharaf** [comment]
Also I think you need to use `\\` instead of` \` in your path. 
For instance: `"setups":"D:\\sources\\Esri"`

**Comment by dird-hyang** [comment]
Thanks Azin and Cameron. It works. 
BTW, the double backslash was reduced to one after copying. The above modified role works.
This gives me the confident to go ahead installing and configuring the distributed ArcGIS Enterprise system. 
Really appreciate your quick response.
Helen

**Comment by dird-hyang** [comment]
Hi, 
one hiccup from the last installation, although it didn't return any error. 
The license manager was not set properly, although the license type, and the license level are correct.
And it locked the licensing screen. 
Even though I change the Windows Registry, the screen is still locked.

**Comment by azinsharaf** [comment]
Include `"seat_preference":"Float"` in your json.

**Comment by cameronkroeker** [comment]
@dird-hyang 

There are two issues.

1. license manager host not being set
2. License settings being locked

The first issue is related to the 'portal_list' attribute having a default value of '':
_node['arcgis']['pro']['portal_list'] = ArcGIS Portal URLs. Default value is ''._

This causes Chef to use the following command to install Pro:

msiexec.exe /i ArcGISPro.msi ALLUSERS=1 **Portal_List=** ESRI_LICENSE_HOST=lmhost.domain.com AUTHORIZATION_TYPE=CONCURRENT_USE SOFTWARE_CLASS=Professional INSTALLDIR="C:\Program Files\ArcGIS\Pro" /qb

This causes Pro to ignore the ESRI_LICENSE_HOST parameter therefore it doesn't set it. So as a workaround try defining the 'portal_list' attribute in your json file. Could use arcgis online as the default. For example:

"portal_list":"https://www.arcgis.com"

As for the second issue, I believe its related to the lock_auth_settings being set to true. According to the [ArcGIS Pro documentation](https://pro.arcgis.com/en/pro-app/get-started/arcgis-pro-installation-administration.htm#GUID-3BC34488-228D-4D37-8F96-6206CCA7539F):

During a silent, per-machine installation of ArcGIS Pro, **if the authorization type is defined**, this is set to True under HKEY_LOCAL_MACHINE\SOFTWARE\Esri\ArcGISPro\Licensing. When LOCK_AUTH_SETTINGS is True, the licensing settings in the registry apply to all ArcGIS Pro users on that machine; an individual user cannot make changes. To allow ArcGIS Pro users on the machine to define their own authorization settings through the ArcGIS Pro application, set LOCK_AUTH_SETTINGS to False. This property does not apply to a per-user installation.

The ArcGIS Pro cookbook doesn't look to accept the "lock_auth_settings" attribute, so we will have to manually edit the LOCK_AUTH_SETTINGS to false in the following registry path:

HKEY_LOCAL_MACHINE\SOFTWARE\Esri\ArcGISPro\Licensing

(Be careful editing the registry manually, I highly recommend making a backup of the registry first).

Example json that worked for me:

{
"arcgis":{
"pro":{
"version":"2.3",
"setup_archive":"C:\\\\software\\\\ArcGISPro_23_167023.exe",
"install_dir":"C:\\\\Program Files\\\\ArcGIS\\\\Pro",
"allusers":"1",
"software_class":"Professional",
"authorization_type":"CONCURRENT_USE",
"portal_list":"https://www.arcgis.com/",
"esri_license_host":"lm.domain.com"
}
},
"run_list":[
"recipe[arcgis-pro]"
]
}

Thanks,
Cameron K.

**Comment by dird-hyang** [comment]
@cameronkroeker Many thanks. Add in the portal_list resolved the issue. I have a lot to learn about the Chef architecture to figure this kind of error myself.

As for the lock issue, it was my ignorant not noticing the LOCK_AUTH_SETTINGS. Really appreciate your prompt response.

Helen

**Comment by dird-hyang** [comment]
For whoever concerns.
I'm using Chef client 14.11.21 (chef-client-14.11.21-1-x64.msi) on Windows Server 2016.
The Cookbook version is 3.3.0
I got many messages as following:

Deprecated features used!
  Resource windows_auto_run from a cookbook is overriding the resource from the client. Please upgrade your cookbook or
remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_feature from a cookbook is overriding the resource from the client. Please upgrade your cookbook or r
emove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_feature_dism from a cookbook is overriding the resource from the client. Please upgrade your cookbook
 or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_feature_powershell from a cookbook is overriding the resource from the client. Please upgrade your co
okbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_font from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remo
ve the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_pagefile from a cookbook is overriding the resource from the client. Please upgrade your cookbook or
remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_path from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remo
ve the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_printer from a cookbook is overriding the resource from the client. Please upgrade your cookbook or r
emove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_printer_port from a cookbook is overriding the resource from the client. Please upgrade your cookbook
 or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_shortcut from a cookbook is overriding the resource from the client. Please upgrade your cookbook or
remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_task from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remo
ve the cookbook from your run_list before the next major release of Chef. at 1 location:
    - C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/log.rb:51:in `caller_lo
cation'
   See https://docs.chef.io/deprecations_map_collision.html for further details.

Not sure if I post this will help.
Helen

**Comment by dird-hyang** [comment]
Just a summary of the issue and how it was resolved.
The problems and the resolution
1.  the installation file (EXE) was ignored. No unpacking action was performed. 
Solution: 
Use "setup_archive":"C:\\software\\ArcGISPro_23_167023.exe", instead of "setup".
2. the license server was not set and the license setting window was locked after installation.
Solution:
add in "portal_list":"https://www.arcgis.com/", attribute, instead of leaving the default blank.

Thanks for all that have responded and helped to resolve the issue.
Helen
