### ISSUE TITLE
authorization (AWS is a required dependency)

### ISSUE THREAD

**Issue by jsthusker** [Esri/arcgis-cookbook#214]
When upgrading to 10.7 portal  the authorization piece at the end gets stuck.  It has access to the file share where the .json file is located but it will not authenticate.
Here is the error
`#<Mixlib::ShellOut::ShellCommandFailed: arcgis_enterprise_portal[Authorize Portal for ArcGIS] (arcgis-enterprise::portal line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '-1073741502' ---- Begin output of "C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe" /VER 10.7 /LIF "\\GISMetro\GIS_Config\Repository\10_7\ArcGIS_Enterprise_Portal_107_278223_20190411.json" /S ---- STDOUT: STDERR: ---- End output of "C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe" /VER 10.7 /LIF "\\GISMetro\GIS_Config\Repository\10_7\ArcGIS_Enterprise_Portal_107_278223_20190411.json" /S ---- Ran "C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe" /VER 10.7 /LIF "\\GISMetro\GIS_Config\Repository\10_7\ArcGIS_Enterprise_Portal_107_278223_20190411.json" /S returned -1073741502> had an error:
arcgis_enterprise_portal[Authorize Portal for ArcGIS] (arcgis-enterprise::portal line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '-1073741502' ---- Begin output of "C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe" /VER 10.7 /LIF "\\GISMetro\GIS_Config\Repository\10_7\ArcGIS_Enterprise_Portal_107_278223_20190411.json" /S ---- STDOUT: STDERR: ---- End output of "C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe" /VER 10.7 /LIF "\\GISMetro\GIS_Config\Repository\10_7\ArcGIS_Enterprise_Portal_107_278223_20190411.json" /S ---- Ran "C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe" /VER 10.7 /LIF "\\GISMetro\GIS_Config\Repository\10_7\ArcGIS_Enterprise_Portal_107_278223_20190411.json" /S returned -1073741502`

**Comment by cameronkroeker** [comment]
@jsthusker 

The issue is most likely because the chef process that is executing the authorization command is LocalSystem, which may not have access to the file share where the authorization file is located.

If the portal authorization file is moved to a local path does it succeed?

**Comment by jsthusker** [comment]
no I tried that.  I think I just realized that for some reason the chef server is trying to run the 3.2.1 version of arcgis-enterprise.  It still runs but not correctly.  3.3 is in my repo and uploaded to the Chef Server but if I go to the portal node the 3.2.1 cookbooks are in the chef/cache folder.  ???  Any ideas?  I know that I am getting out of scope here

**Comment by cameronkroeker** [comment]
> no I tried that. I think I just realized that for some reason the chef server is trying to run the 3.2.1 version of arcgis-enterprise. It still runs but not correctly. 3.3 is in my repo and uploaded to the Chef Server but if I go to the portal node the 3.2.1 cookbooks are in the chef/cache folder. ??? Any ideas? I know that I am getting out of scope here

@jsthusker Perhaps try renaming (or removing) chef/local-mode-cache and chef/nodes directories.

**Comment by jsthusker** [comment]
I have figured out my issue.  This is very important and I have not found mention of it anywhere.  AWS cookbook is now a required dependency for arcgis-enterprise 3.3.0 cookbooks.  If you try and run your scripts and do not have aws the cookbook will revert to the previous version 3.2.1 which is not compatible.  Here is the kicker.  It won't error out saying that.  It will run until it cannot authenticate and will mess up your install.  
It took me all day to figure this out. ugh

**Comment by jsthusker** [comment]
Re-Opening so this gets documented

**Comment by cameronkroeker** [comment]
@jsthusker 

Wow, great catch! Looks like arcgis-enterprise cookbook has a dependency on arcgis-repository cookbook:

[ArcGIS-Enterprise cookbook dependencies](https://github.com/Esri/arcgis-cookbook/blob/master/cookbooks/arcgis-enterprise/README.md#dependencies)

And the ArcGIS-Repository cookbook has a dependency on the [AWS cookbook](https://github.com/Esri/arcgis-cookbook/tree/master/cookbooks/arcgis-repository#dependencies).

**Comment by cameronkroeker** [comment]
> I have figured out my issue. This is very important and I have not found mention of it anywhere. AWS cookbook is now a required dependency for arcgis-enterprise 3.3.0 cookbooks. If you try and run your scripts and do not have aws the cookbook will revert to the previous version 3.2.1 which is not compatible. Here is the kicker. It won't error out saying that. It will run until it cannot authenticate and will mess up your install.
> It took me all day to figure this out. ugh

@jsthusker 

Wow, great catch! Looks like arcgis-enterprise cookbook has a dependency on arcgis-repository cookbook:

[ArcGIS-Enterprise cookbook dependencies](https://github.com/Esri/arcgis-cookbook/blob/master/cookbooks/arcgis-enterprise/README.md#dependencies)

And the ArcGIS-Repository cookbook has a dependency on the [AWS cookbook](https://github.com/Esri/arcgis-cookbook/tree/master/cookbooks/arcgis-repository#dependencies).

**Comment by azinsharaf** [comment]
@jsthusker 
aws cookbook exists in arcgis cookbook zip file. Didn't you copy it on the server? I am curios to know.

**Comment by jsthusker** [comment]
> @jsthusker
> aws cookbook exists in arcgis cookbook zip file. Didn't you copy it on the server? I am curios to know.

Where does it exist? Not here that I can find.

**Comment by jsthusker** [comment]
Trevor at ESRI helped me through this issue.  I am closing this, but make sure you clarify the information on this page.  The repository does not contain all required dependencies, but the release does.  Lesson learned.
