### ISSUE TITLE
Configure Data Store server_url

### ISSUE THREAD

**Issue by ClaesGIS** [Esri/arcgis-cookbook#216]
I got a question regarding the configuration of ArcGIS Data Store. The datastore recipe refer to the server with domain_name instead of the actual server url. Is that intended?
For example the portal-recpie use `node['arcgis']['portal']['url']`.

This is troublesome in our current configuration because the domain_name is only running the webadaptor and not the arcgisserver. So nothing is listening on `server_url 'https://' + node['arcgis']['server']['domain_name'] + ':6443/arcgis'`. Keep in mind, we might be using domain_name wrong, if so please enlighten me.

Relevant code: https://github.com/Esri/arcgis-cookbook/blob/0fb2143442cb57f2022b85c80742bdef89db4374/cookbooks/arcgis-enterprise/recipes/datastore.rb#L41

**Comment by pbobov** [comment]
That is a valid question. The datastore recipe constructs server_url instead if using private_url attribute because few releases ago Data Store configuration tool required the URL to end with ':6443/arcgis' and server/private_url might not. 

It's probably time to revisit that. Does configuredatastore tool in ArcGIS Data Store 10.7 still require the ArcGIS Server URL to end with ':6443/arcgis'?

**Comment by cameronkroeker** [comment]
> That is a valid question. The datastore recipe constructs server_url instead if using private_url attribute because few releases ago Data Store configuration tool required the URL to end with ':6443/arcgis' and server/private_url might not.
> 
> It's probably time to revisit that. Does configuredatastore tool in ArcGIS Data Store 10.7 still require the ArcGIS Server URL to end with ':6443/arcgis'?

The ArcGIS Server admin URL format has changed a bit. It no longer needs the '/arcgis' but does require ':6443'.

[The ArcGIS Server admin URL is in the format https://gisserver.domain.com:6443. Note that even if your GIS Server site uses a web adaptor, you must provide the URL in the aforementioned format.](http://enterprise.arcgis.com/en/portal/latest/administer/windows/data-store-utility-reference.htm#ESRI_SECTION1_21824FB573434E5783C48F0D63C1F228)

**Comment by pbobov** [comment]
configuredatastore tool does not needs the '/arcgis' part because it always adds '/arcgis' to the server URL, and that is the problem.

**Comment by pbobov** [comment]
arcgis-enterprise cookbook uses uniform URLs like <protocol>://<domain>:<port>/<context> for server and portal URLs. That does not work for configuredatastore tool because it requires <context> = 'arcgis'.

**Comment by ClaesGIS** [comment]
I should have mentioned we are still on 1.6.1 (cookbook version 3.2.1). The deployment will look similar to the one mentioned at the bottom of this [page](http://enterprise.arcgis.com/en/portal/latest/administer/windows/ha-scenarios-web-gis.htm) ([image](http://enterprise.arcgis.com/en/portal/latest/administer/windows/GUID-EF93D4A2-1A2F-45E4-818D-E28705A3F75F-web.png)). 

Both Portal and Arcgis servers are exposed by the same WA running on the same host as portal. I guess I'll have to manually modify recipe to meet our needs. 

Feel free to close this issue unless you guys have any additional ideas on how I should proceed.

**Comment by ClaesGIS** [comment]
Solved by changing :configure to use `node['arcgis']['server']['url']` instead of `server_url 'https://' + node['arcgis']['server']['domain_name'] + ':6443/arcgis'`

Result:
```
...
arcgis_enterprise_datastore 'Configure ArcGIS Data Store' do
  install_dir node['arcgis']['data_store']['install_dir']
  data_dir node['arcgis']['data_store']['data_dir']
  types node['arcgis']['data_store']['types']
  run_as_user node['arcgis']['run_as_user']
  server_url node['arcgis']['server']['url']
  username node['arcgis']['server']['admin_username']
  password node['arcgis']['server']['admin_password']
  retries 5
  retry_delay 60
  action :configure
end
...
```
