### ISSUE TITLE
Skipping run_as_user

### ISSUE THREAD

**Issue by ClaesGIS** [Esri/arcgis-cookbook#219]
### Description
The service is never updated with the account/user specified in the attribute `node['arcgis']['run_as_user']`. Not limited to any of the enterprise products. I've reproduced the error on datastore, arcgis and portal.

### Troubleshooting/actions done so far

- Running the command (configureserviceaccount.bat with flags) manually works fine (as the same user running chef-client)
- Added debug output within :update_account and verified it doesn't output when running chef-client in debug mode
- Granted logon as service to the run_as_user-account
- Added the account to the local administrator group 

### Log output
```
Recipe: arcgis-enterprise::install_portal
  * arcgis_enterprise_portal[Update Portal for ArcGIS service logon account] action nothing[2019-04-24T16:46:20+02:00] INFO: Processing arcgis_enterprise_portal[Update Portal for ArcGIS service logon account] action nothing (arcgis-enterprise::install_portal line 21)
 (skipped due to action :nothing)
[2019-04-24T16:46:20+02:00] DEBUG: Skipping arcgis_enterprise_portal[Update Portal for ArcGIS service logon account] due to action :nothing
```
### Attributes
I prefer not to disclose any attributes at this time. Hopefully I've provided enough details to locate the culprit. Keep in mind running it manually with the same values works fine. So my guess it has something to do with `node['arcgis']['server']['product_code']` not being populated/assigned.

### Versions
**Arcgis-cookbook**: 3.2.1
**Chef-client**: 13.12.14.1
**Portal for Arcgis**: 10.6.1 (10.6.9270)
**ArcGIS Server**: 10.6.1 (10.6.9270)

**Comment by pbobov** [comment]
Do you have `arcgis-enterprise::system` recipe in the run_list? The service logon account updates are triggered by that recipe if the run_as_user account was updated.

**Comment by ClaesGIS** [comment]
> Do you have arcgis-enterprise::system recipe in the run_list? The service logon account updates are triggered by that recipe if the run_as_user account was updated.

Sorry I should have included the run-lists. Yes, `arcgis-enterprise::system` is the first one in the run_list. However to my understanding it's the `install_*`-recipes that should trigger the account change. Example for portal [link](https://github.com/Esri/arcgis-cookbook/blob/75e3e5b495610ce70fc41f52d0d6e7c221c65648/cookbooks/arcgis-enterprise/recipes/install_portal.rb#L21).

The problem is that it never updates the service in windows (see [image](https://i.imgur.com/t6NbAPE.png)).


We are using a domain-account (see below). 
```
      "arcgis": {
        "run_as_user": "OUR-DOMAIN\\sa.arcgis",
        "run_as_pasword": "REDACTED"
      }
```

### Run-lists

**ArcGIS primary**
```
    "run_list":[
        "recipe[arcgis-enterprise::system]",
        "recipe[esri-iis]",
        "recipe[arcgis-enterprise::server]",
        "recipe[arcgis-enterprise::datastore]",
        "recipe[arcgis-enterprise::federation]"
      ]

```
**Portal primary**
```
    "run_list":[
      "recipe[arcgis-enterprise::system]",
      "recipe[esri-iis]",
      "recipe[arcgis-enterprise::portal]",
      "recipe[arcgis-enterprise::portal_wa]",
      "recipe[arcgis-enterprise::server_wa]"
    ]
```

**Comment by pbobov** [comment]
```ruby
if node['platform'] == 'windows'
  arcgis_enterprise_portal 'Update Portal for ArcGIS service logon account' do
    install_dir node['arcgis']['portal']['install_dir']
    run_as_user node['arcgis']['run_as_user']
    run_as_password node['arcgis']['run_as_password']
    only_if { Utils.product_installed?(node['arcgis']['portal']['product_code']) }
    subscribes :update_account, "user[#{node['arcgis']['run_as_user']}]", :immediately
    action :nothing
  end
end
```

This subscribes to  `user[#{node['arcgis']['run_as_user']}]` resource changes, which is only triggered if the user account was created or modified by Chef.

Was the user account modified by 'system' recipe in this case?

**Comment by pbobov** [comment]
I just realized that it's a domain account. It cannot be modified. So 'Update Portal for ArcGIS service logon account' will not be triggered.

To workaround the problem you can add a recipe to trigger 'Update Portal for ArcGIS service logon account' using 'notify'...

**Comment by pbobov** [comment]
Something like

```ruby
file '#{node['arcgis']['run_as_user']}' do
  content ''
  notifies :update_account, 'arcgis_enterprise_portal[Update Portal for ArcGIS service logon account]', :immediately
end
```

**Comment by ClaesGIS** [comment]
Fair enough. So there is no support for using a domain account as run_as_user?

**Comment by pbobov** [comment]
Domain account as run_as_user is supported. But, apparently, changing the account is not supported.

**Comment by ClaesGIS** [comment]
I see. So the problem occurs earlier then. My guess would be at this step https://github.com/Esri/arcgis-cookbook/blob/75e3e5b495610ce70fc41f52d0d6e7c221c65648/cookbooks/arcgis-enterprise/providers/portal.rb#L97-L100. 
Perhaps it's not escaping the characters correctly or the password has to comply with some policy?

Is there anything wrong with this format?
```
      "arcgis": {
        "run_as_user": "OUR-DOMAIN\\sa.arcgis",
        "run_as_pasword": "REDACTED"
      }
```

**Comment by pbobov** [comment]
The format looks correct. 

Try using new 3.3.0 cookbook. There were some problems with handling passwords containing spaces and some other special characters that were fixed in 3.3.0.

**Comment by pbobov** [comment]
Though 3.3.0 cookbooks officially  do not support ArcGIS 10.6.1...

**Comment by pbobov** [comment]
Try to change `action :install` implementation in providers/portal.rb to use the fresh code.

**Comment by ClaesGIS** [comment]
> Try to change `action :install` implementation in providers/portal.rb to use the fresh code.

I'll have a look, thanks!

**Comment by ClaesGIS** [comment]
Yeah something is fishy about the install process. I updated the :install in the provider files for arcgis, portal and datastore to 3.3.0. Ran chef-client manually in an elevated powershell terminal. 
After a few minutes "invalid password" shows up: https://i.imgur.com/7LOYrZ0.png

There isn't anything special about the password at all. Gotta be the username somehow.

**Comment by pbobov** [comment]
Please try to run the ArcGIS Server setup from the command line the same way Chef does that, to figure out what exactly the setup does not like.

**Comment by ClaesGIS** [comment]
I found the issue... The run_as_password attribute was not correct. Thanks a lot pbobov for helping me troubleshoot!

**Comment by azinsharaf** [comment]
> The format looks correct.
> 
> Try using new 3.3.0 cookbook. There were some problems with handling passwords containing spaces and some other special characters that were fixed in 3.3.0.

hi @pbobov , 
I am going to use a domain account with a password o 20 characters including )(:> . Do you know exactly which special characters makes problem? I have to use 3.2.1 for 10.6.1 deployment.

**Comment by pbobov** [comment]
I know that there were problems with '&' characters in passwords. The fix in 3.3.0 cookbook takes care  only of '&'.  

```ruby
run_as_password = @new_resource.run_as_password.gsub("&", "^&")
```

I assume all the other characters should be Ok.

**Comment by tsmalls93** [comment]
@pbobov This is still an issue for me. I am using 3.2.1 cookbooks for a 10.6.1 deployment. Our password contains an `!`. Would that be the cause? I need to use a domain account in order to access a file share. It seems to run okay with Chef Solo but not Chef Server. Any ideas?

**Comment by tsmalls93** [comment]
It turns out that it was normal for it to skip updating the service account in my case. It was just using Local System to run the service instead of the desired domain account. I was using a local administrator account for the WinRM connection on the Chef provisioner in Terraform. I switched to using the domain account and the issue was resolved.

**Comment by ClaesGIS** [comment]
@tsmalls93 my issue was rather embarrassing however no one caught it. If you look at the top, I typed run_as_password as run_as_pasword.

**Comment by tsmalls93** [comment]
Yeah, that isn't my issue unfortunately. I thought I had fixed it, but it is still runs the service as Local System sometimes. I might need to open a new issue.

**Comment by tsmalls93** [comment]
@Nickolaitc yes that is what we are using. The password is 8 characters long with the “!” at the end.

**Comment by Nickolaitc** [comment]
@tsmalls93 I know that password wouldn't generate a problem as my own Active Directory and local accounts passwords include an "!" at the end and I have deployed multiple different versions successfully (10.5x-10.7x) with Chef client and Chef Server (and CloudFormation)

There could be a possibility it has something to do with environmental variables or another setting of some sort, but further testing would need to be conducted. https://docs.microsoft.com/en-us/windows/win32/services/localsystem-account

**Comment by tsmalls93** [comment]
Yeah it is a strange issue and the fact that it sometimes works okay makes it even harder to figure out what is happening. For now I am going to run a script after installing server/portal to ensure that the service account is set properly. We wanted to switch to a GMSA anyway, so we would have had to do this either way.
