### ISSUE TITLE
arcgis-egdb sample json

### ISSUE THREAD

**Issue by drobinson13** [Esri/arcgis-cookbook#222]
The following line in the arcgis-egdb sample JSON (https://github.com/Esri/arcgis-cookbook/tree/master/cookbooks/arcgis-egdb) appears to have a typo:

"connection_file": "C:\\chef\\**msic**_scripts\\connection_files\\RDS_egdb.sde",

**Comment by cameronkroeker** [comment]
fixed in v3.6.0.
