### ISSUE TITLE
arcgis-egdb Register Connection

### ISSUE THREAD

**Issue by drobinson13** [Esri/arcgis-cookbook#223]
On testing the new arcgis-egdb cookbook it creates the enterprise GDB fine, however it doesn't register this within ArcGIS Server manager as a Data Store. 

Is it expected that the enterprise GDB is registered as a Data Store in ArcGIS Server? 
The sample seems to suggest so:

"data_items": [{
        "database": "egdb",
        "data_item_path": "/enterpriseDatabases/registeredDatabase",
        "connection_file": "C:\\chef\\misc_scripts\\connection_files\\RDS_egdb.sde",
        "is_managed": true,
        "connection_type": "shared"
      }]

Are there any pre-requisites required for this to work? Through testing i have found one - the security groups of the instance running the Chef script and the RDS need to be open too each other on the postgres port and within the same VPC (if running under no public access).

**Comment by azinsharaf** [comment]
try to use double slash instead:
`"connection_file": "C:\\chef\\msic_scripts\\connection_files\\RDS_egdb.sde",
`

**Comment by pbobov** [comment]
@drobinson13 Can you remove all the sensitive info and share the chef run log and the JSON file?

**Comment by drobinson13** [comment]
Found the issue. 

In the "server": { "private_url" parameter, it wasn't possible to use any of the following [localhost:6443/arcgis, internalIP:6443/arcgis, privateDNS:6443/arcgis]. I think this is for one of two reasons:
1. External access is required - hence internal facing DNS won't work
2. It needs to match the webContextURL - usually the external DNS in AWS - e.g. https://mydomain.com/server
