### ISSUE TITLE
arcgis-enterprise depends issues

### ISSUE THREAD

**Issue by cdflint** [Esri/arcgis-cookbook#226]
https://github.com/Esri/arcgis-cookbook/blob/37a2bc5db4f65c72715d947a1b1f5fd9b7ba46d5/cookbooks/arcgis-enterprise/providers/server.rb#L28-L58

The current depends format for arcgis-enterprise needs to be refactored.  Currently there is no package version preference.  Using Berkshelf to upload arcgis-enterprise results in the latest packages being installed.  The current version of windows_firewall cookbook (5.0.1) does not have a `dir' method and throws an error when node[arcgis][server][install_system_requirements] = true.  Below is a list of the packages and versions included in the release 3.3.1.

`arcgis-cookbook v3.3.1`  cookbooks and versions included in arcgis-3.3.1-cookbook.zip
```ruby
depends 'apt', '~> 2.7.0'
depends 'arcgis-egdb', '~> 1.0.0'
depends 'arcgis-enterprise', '~> 3.3.1'
depends 'arcgis-geoevent', '~> 3.3.0'
depends 'arcgis-insights', '~> 3.3.0'
depends 'arcgis-pro', '~> 3.3.0'
depends 'authbind', '~> 0.1.10'
depends 'aws', '~> 7.3.1'
depends 'chef_handler', '~> 1.1.7'
depends 'chef-sugar', '~> 2.5.0'
depends 'esri-iis', '~> 0.1.1'
depends 'esri-tomcat', '~> 0.1.4'
depends 'homebrew', '~> 4.1.0'
depends 'hostsfile', '~> 2.4.5'
depends 'iptables', '~> 1.0.1'
depends 'java', '~> 1.50.0'
depends 'java_properties', '~> 0.1.0'
depends 'limits', '~> 1.0.0'
depends 'line', '~> 0.6.3'
depends 'ms_dotnet', '~> 3.2.1'
depends 'mt-server', '~> 0.1.0'
depends 'nfs', '~> 2.3.1'
depends 'ohai', '~> 5.1.0'
depends 'openssl', '~> 8.1.2'
depends 'sysctl', '~> 0.8.1'
depends 'tomcat', '~> 3.2.0'
depends 'windows', '~> 4.1.4'
depends 'windows_firewall', '~> 3.0.2'
depends 'yum', '~> 3.5.3'
depends 'yum-epel', '~> 0.6.0'
```

Cookbooks and versions pulled into chef-server when using Berkshelf to install based on depends.
```ruby
depends 'apt', '~> 7.1.1'
depends 'arcgis-egdb', '~> 1.0.0'
depends 'arcgis-enterprise', '~> 3.3.1'
depends 'arcgis-geoevent', '~> 3.3.0'
depends 'arcgis-insights', '~> 3.3.0'
depends 'arcgis-pro', '~> 3.3.0'
depends 'authbind', '~> 0.1.10'
depends 'aws', '~> 8.0.3'
depends 'build-essential', '~> 8.2.1'
depends 'download-setups-s3', '0.0.0'
depends 'esri-iis', '~> 0.1.1'
depends 'esri-tomcat', '~> 0.1.4'
depends 'homebrew', '~> 5.0.8'
depends 'hostsfile', '~> 3.0.1'
depends 'iptables', '~> 4.5.0'
depends 'java', '~> 4.0.0'
depends 'java_properties', '~> 0.1.3'
depends 'limits', '~> 1.0.0'
depends 'line', '~> 2.3.1'
depends 'mingw', '~> 2.1.0'
depends 'ms_dotnet', '~> 4.2.1'
depends 'nfs', '~> 2.6.3'
depends 'openssl', '~> 8.5.5'
depends 'sysctl', '~> 0.8.1'
depends 'poise', '~> 2.8.2'
depends 'poise-service', '~> 1.5.2'
depends 'postgresql', '~> 7.1.4'
depends 'postgresql-test', '~> 0.0.0'
depends 'seven_zip', '~> 3.1.0'
depends 'tar', '~> 2.2.0'
depends 'test', '~> 3.2.0'
depends 'tomcat', '~> 3.2.0'
depends 'windows', '~> 6.0.0'
depends 'windows_firewall', '~> 5.0.1'
```

As you can see the difference I pointed out above with the one breaking issues with windows_firewall may just be the tip of the iceberg as many of the packages have changed major and/or minor versions.

**Comment by cdflint** [comment]
changing the ```dir :in``` to ```direction :inbound``` in the following providers will fix the `dir' missing method issue.  

arcgis-enterprise
>providers
>
>>`datastore.rb`
>>
>>`portal.rb`
>>
>>`server.rb`

Link to docs for [windows_firewall_rule](https://docs.chef.io/resource_windows_firewall_rule.html) is included in chef since 14.7 and compatible with windows_firewall v5.0.1

**Comment by pbobov** [comment]
In the next 3.4.0 version of arcgis-* cookbook we will update and lock the dependent cookbooks versions.

**Comment by wilhelmi** [comment]
Trying to get started with chef-solo/chef-zero and ran into this. Is there a good workaround until 3.4 comes out?

I tried adding the dependencies listed above, that gets past the dir error but raises a new error:

NoMethodError
       -------------
       undefined method `local_port' for Custom resource windows_firewall_rule from cookbook windows_firewall

**Comment by pbobov** [comment]
To workaround the problem, instead of using berks get the cookbooks from arcgis-*-cookbooks.zip/tar.gz archives available at [https://github.com/Esri/arcgis-cookbook/releases](https://github.com/Esri/arcgis-cookbook/releases). The archives include cookbooks used by/with arcgis-* cookbooks.

**Comment by cdflint** [comment]
What chef client version is running on your node?  If your on windows I've been sticking to 14.12.9 as the latest stable release.  There are some breaking changes with the new chef infra v15+ even on linux nodes.

**Comment by cdflint** [comment]
Like @pbobov said, unzip the latest release copy all the cookbooks to your cookboooks directory and use `knife upload \cookbooks` to push them as they stand to your server.  

Berks will require appending the specified depends above to the `metadata.rb` of all `arcgis-*` cookbooks.  Then using Berks to build will capture the specified versions and their dependencies.

**Comment by pbobov** [comment]
arcgis-* cookbooks support Chef Client 13 and 14. 14.12.9 should work.

**Comment by wilhelmi** [comment]
Thanks for the response, I was able to get around this. I hit a different problem that I will file a separate issue for.
