### ISSUE TITLE
 Using Chef to install ArcGIS Enterprise 10.7.1 on Windows Server 2019

### ISSUE THREAD

**Issue by MantalopePG** [Esri/arcgis-cookbook#234]
I am attempting to install ArcGIS Enterprise 10.7.1 with Chef on Windows Server 2019.
I installed the newest version of Chef and downloaded the most recent ArcGIS cookbook however I got the error:

Cookbook 'arcgis-enterprise' version '3.4.0' depends on chef version [">= 12.6", "< 15.0"], but the running chef version is 15.3.14

From what I can tell there is no version of Chef < 15 that works with Windows Server 2019 and no ArcGIS cookbook that works with Chef >15
Is a new cookbook pending release?

**Comment by Nickolaitc** [comment]
Hey @MantalopePG,

I hope all is well.  My current testings with Chef Kitchen and Windows 2019 utilizes Chef-Client 14.5.33 and has been successful thus far in deploying a full ArcGIS Enterprise, which tells us version pre-Chef-Client v15 should work.

**Comment by pbobov** [comment]
Chef client 14.14.25 officially supports Windows Server 2019. 
See https://downloads.chef.io/chef/stable/14.14.25#windows
