### ISSUE TITLE
Unable to register with Portal. The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by MantalopePG** [Esri/arcgis-cookbook#236]
I am working through the process of installing ArcGIS Enterprise with Chef and the program is failing at:
“Configure Web Adaptor with Portal” 
I am getting the error:
“Unable to register with Portal. The remote server returned an error: (401) Unauthorized.” I 
noticed in the output the following:
Files\ArcGIS\WebAdaptor\IIS\10.7.1\Tools\ConfigureWebAdaptor.exe" /m portal /w "https://PC187.csnt.princegeorge.ca/portal/webadaptor" /g "https://PC187.csnt.princegeorge.ca:7443"

We have a valid CA signed wildcard certificate, however, I think the subdomains may be the root cause of the issue. Can anyone confirm this or offer possible solutions? 
Thanks

**Comment by Nickolaitc** [comment]
Hey @MantalopePG,

The error you have provided is not providing a username/password (unless you had removed these).  If the username/password was in there, can you confirm these are the same used for deploying your Portal?  

Are you able to manually access the Web Adaptor configuration via a Browser and configure it with Portal?

**Comment by MantalopePG** [comment]
I did strip out the username and password. When I go to register the portal manually I hit the expected page that says:
A server is not configured with your Web Adaptor 
A portal is not configured with you Web Adaptor 
When it says which component to you want to configure with your Web Adaptor?
If I choose ArcGIS Server, it directs me to an ArcGIS page that looks correct however if I choose Portal for ArcGIS it redirects me over to the Windows Admin Center

**Comment by Nickolaitc** [comment]
Thank you for getting back to me @MantalopePG we definitely should not be sent to Windows Admin Center when we select Portal.  

When running the chef role, did we enable the run_list "recipe[esri-iis]"?
Is the system we are deploying Enterprise on already have IIS enabled and configured?

**Comment by MantalopePG** [comment]
Hey Nickolaitc, Thanks for your help on this,
I am running this on a brand new virtual server. The Recipe[esri-iis] ran with no issues and all the bindings look correct to me although I am admittedly no expert on IIS

<img width="507" alt="Capture" src="https://user-images.githubusercontent.com/55815997/66064683-bcae3080-e4fa-11e9-93af-3378743511cd.PNG">

Since our cert is for *.princegeorge.ca do you think my initial guess of the issue being the subdomains i.e. PC187.csnt.princegeorge.ca could be the problem or is it likely something else?

**Comment by MantalopePG** [comment]
Here's what happens when I go to configure the web Adaptor 
<img width="764" alt="Capture1" src="https://user-images.githubusercontent.com/55815997/66069777-e2403780-e504-11e9-986e-e9527b155465.PNG">
when choose the radial button for portal it tries to go to: 
pc187.csnt.princegeorge.ca/portal/webadaptor/portal
but I end up here:
<img width="666" alt="Capture2" src="https://user-images.githubusercontent.com/55815997/66070087-7dd1a800-e505-11e9-86db-e2b8a5e44ac8.PNG">
windows Authentication is disables and Anonymous is enabled
<img width="545" alt="Capture" src="https://user-images.githubusercontent.com/55815997/66069706-c341a580-e504-11e9-8910-25d19a678948.PNG">

**Comment by Nickolaitc** [comment]
@MantalopePG Okay so when you selected the "ArcGIS Server" option, in reality, it still utilizes "localhost", but, with Portal it will redirect to the hostname/portal/webadaptor.  The issue here is it appears perhaps your IIS is directing pc187.csnt.princegeorge.ca to the Windows Admin Center.

If you select the "ArcGIS Server" option and hit next and then manually change "localhost" to be the hostname, you could very well see this same behavior.

At this point, I do not believe this is an actual Chef issue, but an IIS/Windows Admin Center issue.

**Comment by MantalopePG** [comment]
OK thanks for your help anyways

**Comment by Nickolaitc** [comment]
@MantalopePG We could connect if you would like to provide me your email or you can have a case created with Esri Technical Support.
