### ISSUE TITLE
Failed to import Json file (license) to portal when Enterprise installation done with chef 3.2.1

### ISSUE THREAD

**Issue by anaskanaan** [Esri/arcgis-cookbook#239]
Hi ,

we have an issue here regarding ArcGIS Enterprise 10.6.1 installed with the help of chef ArcGIS cookbook 3.2.1.

The installation goes very well no issue at all the only thing which is does not go is when trying to import the license from the portal regardless where this operation done so we get 
  "error" :
    "code" : 500,
    "message" : "java.lang.RuntimeException: java.lang.Exception: The server at 'https://hostname.domain.com:7443/arcgis/sharing/rest/content/listings/9f017d9f94c74154aa7b2bcd2216687f/provisionOrgEntitlements' returned an error. Invalid URL []",
    "details" : nul

Attaching the json attribute file used 

would like to mention if portal installed manually without chef so importing the license works with no issue

Thanks in Advance
//Anas
[Chef_attributes](https://github.com/Esri/arcgis-cookbook/files/3848148/testenv_redacted.zip)

**Comment by Nickolaitc** [comment]
Hey @anaskanaan,

Thank you for providing the .json of your Chef deployment.  The URL that is being referenced in the Enterprise URL's, is this the systems FQDN, DNS Alias, or Load Balancer?

**Comment by anaskanaan** [comment]
This is the fqdn

**Comment by Nickolaitc** [comment]
Could you perhaps elaborate a bit further on the issue we are encountering?

-Are we encountering this error during the deployment of ArcGIS Enterprise or are you deploying Enterprise successfully and then running a separate chef script (one provided) and it fails?  If so, is the script's purpose to upload a license?
-Are we using Chef Server for the deployment?  If so, could you provide the Roles file?

**Comment by anaskanaan** [comment]
Hi again,
The deployment gets completed without any issue using chef but then when we try to import a license file (navigator licenses) via ArcGIS portal so we get the error mentioned.

yes, this is done using chef Server and the role file used is attached and is based on arcgis-enterprise role used in  arcgis workbook 3.2.1

**Comment by cameronkroeker** [comment]
Hello @anaskanaan,

Is there an error when manually browsing to https://hostname.domain.com:7443/arcgis/sharing/rest/content/listings/9f017d9f94c74154aa7b2bcd2216687f/provisionOrgEntitlements within the web browser? Does the ssl certificate match?

**Comment by anaskanaan** [comment]
Hi Cameron,

When chef was done installing enterprise so the pfx file was imported so yes the ssl certificate is matching

attached is the response when browsing to this url 
![54D3F17C](https://user-images.githubusercontent.com/3976323/69154523-73349780-0ae0-11ea-8536-492a48814111.PNG)

**Comment by cameronkroeker** [comment]
Thanks @anaskanaan. Are there any errors within the Portal logs?

**Comment by anaskanaan** [comment]
Nothing really special it is the same error message
error" :
"code" : 500,
"message" : "java.lang.RuntimeException: java.lang.Exception: The server at 'https://hostname.domain.com:7443/arcgis/sharing/rest/content/listings/9f017d9f94c74154aa7b2bcd2216687f/provisionOrgEntitlements' returned an error. Invalid URL []",
"details" : nul

**Comment by cameronkroeker** [comment]
@anaskanaan 

Can you sign into Portal Sharing with the default portaladmin account and browse to https://hostname.domain.com:7443/arcgis/sharing/rest/content/listings, then in the 'Search Text' box enter 9f017d9f94c74154aa7b2bcd2216687f. Then switch 'My Listings' from false to true and select 'Search Listings' button, does the "Navigator for ArcGIS (Mobile Application)" appear in the search results?

Also, let's check the Index Status to see if all the items match.

Sign into portaladmin endpoint https://hostname.domain.com:7443/arcgis/portaladmin and select System -> Indexer -> Indexer Status

**Comment by Nickolaitc** [comment]
Hey @anaskanaan 

Any update on the previous step provided by @cameronkroeker ?

If we don't see the listing, this means Portal didn't create the itemID for it.

**Comment by anaskanaan** [comment]
Hi @Nickolaitc 
just now so we have a technical problem so we are unable to perform the steps provided by @cameronkroeker 
i will get back to you with more details once available
Have a nice day

**Comment by anaskanaan** [comment]
Hi @Nickolaitc and @cameronkroeker 

attached are the result of your questions. the portal was not able to create the listing and the index has no issues
![s1](https://user-images.githubusercontent.com/3976323/69347122-3c8f8600-0c74-11ea-9796-a325995c7012.jpg)
![s2](https://user-images.githubusercontent.com/3976323/69347123-3c8f8600-0c74-11ea-885d-a1371a7449c5.jpg)
thanks

**Comment by Nickolaitc** [comment]
@anaskanaan 

Thank you for sending this information along.  If you go into your content directory > items and search for "9f017d9f94c74154aa7b2bcd2216687f"  do we find the item?

The Chef Cookbook 3.2.1 you are using, could you share this with us?

**Comment by anaskanaan** [comment]
Hi @Nickolaitc 

Yes, the item exists under content directory - items 

and the chef cookbook used is https://github.com/Esri/arcgis-cookbook/tree/v3.2.1

**Comment by Nickolaitc** [comment]
Hey @anaskanaan,

Thank you for getting back to me.  Any chance you could go here: https://github.com/Esri/arcgis-cookbook/releases  and download the arcgis-3.2.1-cookbooks.zip
 and upload the entire cookbook into Chef Server and give it another go?

**Comment by anaskanaan** [comment]
Thanks @Nickolaitc for your fast response

will get back to you once getting the results

**Comment by anaskanaan** [comment]
Hej @Nickolaitc  Actually we are using the same release which you were referring in your latest post so unfortunately this does not seem to help

**Comment by Nickolaitc** [comment]
Hey @anaskanaan 

It is the same release, but, the location in which you got your original cookbook doesn't have all the typical cookbooks and their dependencies.  If you look at the zip you download from the location I provided, you will see there is more to it then https://github.com/Esri/arcgis-cookbook/tree/v3.2.1.

**Comment by anaskanaan** [comment]
Hi @Nickolaitc and thanks for your reply
attaching is the cookbook we are using 
[arcgis-enterprise-3.2.1.zip](https://github.com/Esri/arcgis-cookbook/files/3949072/arcgis-enterprise-3.2.1.zip)
I am going to test this in my test environment and see if i can reproduce the problem 
Thanks in advance

**Comment by cameronkroeker** [comment]
@anaskanaan Perhaps try with the latest cookbook release v3.5.0. If still facing this issue feel free to reopen.

Thanks!
