### ISSUE TITLE
CentOS - same packages as redhat

### ISSUE THREAD

**Issue by randallwhitman** [Esri/arcgis-cookbook#24]
`system.rb`

```
@@ -107,7 +108,7 @@

   #TODO: Test packages for each platform family 
   case node['platform']
-  when 'redhat'
+  when 'redhat', 'centos'
     ['mesa-libGLU', 'libXdmcp', 'xorg-x11-server-Xvfb'].each do |pckg|
       yum_package pckg do
         options '--enablerepo=*-optional'
```

**Comment by pbobov** [comment]
ArcGIS for Server 10.3.1 is not officially supported on CentOS (though the cookbook might work there with a few changes).

**Comment by jonathanan** [comment]
We list packages for the debian linux family even though they are not officially supported either. I think we should add centos alongside rhel.
