### ISSUE TITLE
New deployment and dependencies

### ISSUE THREAD

**Issue by drobinson13** [Esri/arcgis-cookbook#240]
Hi,

I have found a potential issue with deployment workflow for updated cookbooks. 

If you download and unzip then completely overwrite the existing cookbooks folder (rather than merge the existing folder) - the required local dependencies are lost.

The git repo doesn't contain the required local dependencies when downloaded and unzipped - hence when I try to run any recipes with the updated cookbooks, i receive errors regarding missing dependencies. The system doesn't seem to be able to install the dependencies from scratch - it requires them to exist already (and then it can sync to the latest version of the dependency).   
 
Should the necessary local dependencies be deployed with each new arcgis cookbook release? 
If not is there a method to install the latest dependencies without them already existing, so I can deploy the latest cookbooks?

Thanks,
Damien

**Comment by cameronkroeker** [comment]
Hello @drobinson13,

All the necessary local dependencies are included in the released version of the cookbooks, which can be found here:

https://github.com/Esri/arcgis-cookbook/releases

**Comment by drobinson13** [comment]
I've been cloning from master! :grimacing:
