### ISSUE TITLE
Can't run 3.4 ArcGIS Workbook with Chef 15.6.1

### ISSUE THREAD

**Issue by jeffw92** [Esri/arcgis-cookbook#241]
I downloaded the latest Esri ArcGIS Chef workbook, version 3.4 and tried to run it with the latest Chef client, version 15.6.1 and I get the error  'Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'arcgis-enterprise' version '3.4.0' depends on Chef Infra Client version [">= 12.6", "< 15.0"], but the running Chef Infra Client version is 15.6.10'.  I can't find a Chef client version 15.0, or an ArcGIS Workbook later than 3.4.  Is there some setting in the current setup to allow this to work, or does someone have and idea of where to find Chef 15.0?

Thanks.

Here's the attempted Chef call:
C:\>chef-solo -j c:\chef\roles\arcgis-enterprise-windows-ha-primary.json

[2020-01-21T11:04:43-07:00] WARN: No config file found or specified on command line. Using command line options instead.
[2020-01-21T11:04:43-07:00] WARN: *****************************************
[2020-01-21T11:04:43-07:00] WARN: Did not find config file: C:/chef/client.rb. Using command line options instead.
[2020-01-21T11:04:43-07:00] WARN: *****************************************
Starting Chef Infra Client, version 15.6.10
resolving cookbooks for run list: ["arcgis-enterprise::system", "esri-iis", "arcgis-enterprise::portal", "arcgis-enterprise::portal_wa", "arcgis-enterprise::server", "arcgis-enterprise::server_wa", "arcgis-enterprise::datastore"]
Synchronizing Cookbooks:
  - arcgis-enterprise (3.4.0)
  - esri-iis (0.1.2)
  - arcgis-repository (3.4.0)
  - hostsfile (3.0.1)
  - limits (1.0.0)
  - authbind (0.1.10)
  - iptables (4.5.0)
  - windows_firewall (5.0.1)
  - windows (5.3.1)
  - ms_dotnet (4.2.1)
  - nfs (2.6.3)
  - java_properties (0.1.3)
  - openssl (8.5.5)
  - s3_file (2.8.5)
  - line (2.3.2)

Running handlers:
[2020-01-21T11:04:59-07:00] ERROR: Running exception handlers
Running handlers complete
[2020-01-21T11:04:59-07:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 14 seconds
[2020-01-21T11:04:59-07:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache/cache/chef-stacktrace.out
[2020-01-21T11:04:59-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-01-21T11:04:59-07:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'arcgis-enterprise' version '3.4.0' depends on Chef Infra Client version [">= 12.6", "< 15.0"], but the running Chef Infra Client version is 15.6.10

**Comment by Nickolaitc** [comment]
Hey @jeffw92 you should be able to find different versions here: https://downloads.chef.io/chef/stable/.  At the top right you will see a list of the client downloads.  You should be able to scroll down and find older versions like: https://downloads.chef.io/chef/stable/14.14.29 (version 14.14.29).

**Comment by jeffw92** [comment]
Thanks Trevor.  I've downloaded a 14.14 version and it seems to be working.  I've seen the ArcGIS Cookbook release page before, but unless I'm missing something I don't see where it specifies it needs a specific Chef version.

**Comment by Nickolaitc** [comment]
Hey @jeffw92 you would need to dig into the metadata.rb file: https://github.com/Esri/arcgis-cookbook/blob/master/cookbooks/arcgis-enterprise/metadata.rb.  This will show the following:

name             'arcgis-enterprise'
maintainer       'Esri'
maintainer_email 'contracts@esri.com'
license          'Apache 2.0'
description      'Installs and configures ArcGIS Enterprise'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '3.4.0'
chef_version     '>= 12.6', '< 15.0' if defined? chef_version

**Comment by jeffw92** [comment]
Ok, good to know.
Thanks again @Nickolaitc

**Comment by Nickolaitc** [comment]
https://supermarket.chef.io/cookbooks/arcgis-enterprise/versions/3.4.0 on the right side can also display the needed client versions.  You can change the versions at the drop.

**Comment by Nickolaitc** [comment]
You're welcome @jeffw92 !

**Comment by compuguy** [comment]
Since Chef 14 is technically EoL, will this mean that future versions of this cookbook will have support for Chef 15?
