### ISSUE TITLE
Problem using chef for upgrade

### ISSUE THREAD

**Issue by peterkusk** [Esri/arcgis-cookbook#245]
Hi,

During the last year I've had the possibility to use chef for installing AGE on a couple of customers sites; after a deep learning curve I've managed to do it correctly.
Now I want to upgrade a system from 10.6.1 to 107.1 using cookbooks 3.5.0.
To a large extent it works as expected - changing references in the original recipes to new install media and updating version field.
I've got two problems:
1. 
On one server with portal, server and data store - server is acting as hosting server -, upgrade runs as expected including upgrading webadaptor (named portal and server).
The same server contains a webadaptor referencing an server located on another machine - this server is federated with portal.
The webadaptor is named arcgis and trying to upgrade it fails - it claims already existing.
In another words: chef are able to upgrade webadaptors portal and server, but not arcgis.
2.
On a separate server we've installed a stand alone server and webdaptor. Trying to upgrade this server responds with error 28809. Could not validate the credentials for account ...... Confirm the credentials are correct and attempt the installation again.
I've checked and double checked the account - it's correct.
Any ideas on this ?

Thank you.

Best regards,

Peter Kusk

**Comment by cameronkroeker** [comment]
Hello @peterkusk, 

For the first issue, how was the third Web Adaptor (arcgis) installed and configured (Manually, or with a separate chef json file)?

I suspect the issue could be related to Chef supporting the installation of two Web Adaptors (one for portal and one for AGS, the context name shouldn't matter). We only list two product codes for each version of the Web Adaptor:

https://github.com/Esri/arcgis-cookbook/blob/master/cookbooks/arcgis-enterprise/attributes/webadaptor.rb#L55

So if neither of these product codes are found in the registry then Chef will likely not recognized that its installed (so uninstall is skipped), and will attempt to install which throws the error that the Web Adaptor with name 'arcgis' already exists.

The product codes for the installed Web Adaptors can be found in `HKEY_LOCAL_MACHINE -> SOFTWARE -> Wow6432Node->ESRI`. Check to see if the 'arcgis' Web Adaptor contains a different product code that doesn't exist in 

https://github.com/Esri/arcgis-cookbook/blob/master/cookbooks/arcgis-enterprise/attributes/webadaptor.rb#L55

And for the second issue, error 28809, is the ArcGIS Server service run-as account a local or domain account? Perhaps try a password reset on the account.

**Comment by peterkusk** [comment]
Hi @cameronkroeker,

Thank you very much for your answer.

Your answer for problem 1 describes exactly whats happening.

I couldn't wait for your answer and removed my problem webadaptor manually followed by install using chef.

Now I've got three webadaptors on my portal server - all version 10.7.11595.

Productcodes for these wa's are:
{5ECEF84F-592C-47D1-B7C5-9F3D7E2AB7CE}
{5F1D01EA-296E-4226-A704-6A90E2916782}
{7368D3C8-F13B-4786-AE38-B51952F43867}

From this it's obvious that the third one can't b recognized by chef according to your list of product codes.

That's OK with me - know I do know about this limitation.

We do in general install many webadaptors on one server - portal, hosting, reference one, reference two, geoevent, ...

Regarding problem two it's a domain account. I'll give your answer a try and if it doesn't help I'll run the update manually.

Thank you.

Best regards,

Peter Kusk
