### ISSUE TITLE
Failed to remove arcgis license manager using arcgis-desktop::uninstall

### ISSUE THREAD

**Issue by anshacm** [Esri/arcgis-cookbook#248]
The uninstall recipe is failing with the below error for the ArcGIS license manager while the desktop is getting removed successfully. The attributes are not modified and product code is declared like ArcGIS desktop.

Starting Chef Client, version 14.10.9
resolving cookbooks for run list: ["arcgis-desktop::uninstall"]
Synchronizing Cookbooks:
  - arcgis-repository (3.5.0)
  - arcgis-desktop (3.5.0)
  - limits (1.0.0)
  - windows (5.3.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: arcgis-desktop::uninstall
  * arcgis_desktop_desktop[Uninstall ArcGIS Desktop] action uninstall (skipped due to only_if)
  * arcgis_desktop_licensemanager[Uninstall ArcGIS License Manager] action uninstall

    ================================================================================
    Error executing action `uninstall` on resource 'arcgis_desktop_licensemanager[Uninstall ArcGIS License Manager]'
    ================================================================================

    NameError
    ---------
    undefined local variable or method `product_code' for #<#<Class:0x000000000756ec88>:0x00000000074bf4b8>

**Comment by cameronkroeker** [comment]
Hi @anshacm,

Which version of License Manager is installed?

Thanks,
Cameron K.

**Comment by anshacm** [comment]
Hi @cameronkroeker

It is 10.5.1

**Comment by anshacm** [comment]
Created one recipe to remove the license manager.
