### ISSUE TITLE
esri arcgis javascript api how to save rectangle coordinates to sql server database table

### ISSUE THREAD

**Issue by AminBangash** [Esri/arcgis-cookbook#249]
I have a scenario to save drawn rectangle coordinates into microsoft SQL server database table and then generate a notification alert for a point feature if it lies inside in it. Can anybody have idea how to save a polygon rectangle feature coordinates into Sql server database?

**Comment by cameronkroeker** [comment]
Hello @AminBangash, this repo is for ArcGIS Chef cookbook related issues/questions. I recommend posting this in GeoNet or reaching out to Esri Technical Support.

Thanks,
Cameron K.
