### ISSUE TITLE
Data Store question and SSl

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#25]
Two questions:
Am I correct that that after running the chef cookbook I need to go into the system and setup the various security settings, install SSL and signed certs?

Since I layout the signd-cert in the json and give the pword, I was under the impression that the WA would be setup with SSL and the signed cert (it's a domain level cert)

I noticed that for hosting AGS I had to go in and bring in the signed cert.
(Is there a way to remove the self-signed cert?  It seems to often get in the way and seems to think it's the primary cert.)

2ndly: I went to C:\Program Files\ArcGIS\DataStore\tools to run some of the batch files to change backup dates and times, etc... and it seems that all batch files I try run return the same error:  "Error encountered: The data store machine may not have been initialized."

I can upload zipped file.gdbs and Feature Layers show up ok.  
But when I try to delete them I get error messages. 
And the backups of the data store appear to be working since they took up almost 70GB....

Should I consider a complete uninstall-reinstall?  

This is a development Portal box that has everything running on the same VM under Win2012R2
Thanks

**Comment by pkdavidson** [comment]
FWIW- when I remote to the server and try to open the DataStore configuration page:
https://localhost:2443/arcgis/datastore
IE returns: This page can't be displayed.

**Comment by pbobov** [comment]
The arcgis cookbook works with SSL certificates like this:
1. If HTTPS is already configured in IIS - it does not touch it. 
2. If SSL certificate file (.pfx) and password are provided in the json attributes - it uses the certificate to configure HTTPS.
3. Otherwise, it generates a self-signed SSL certificate and configures HTTPS in IIS using that certificate (WARNING the certificate expires next day).

I forwarded your Data Store questions to the Data Store devs.

**Comment by pbobov** [comment]
Here is the answer for your second question from the Data Store devs.

******
The user may run into a problem in ArcGIS Data Store 10.3/10.3.1(maintenance scheduler will be started after you configuring data store. You have to restart ArcGIS Data Store Service to start the maintenance scheduler). As a side effect, the database backups and transaction logs backups will be accumulated and eventually exhaust the hard drive, which will then lead to some strange behavior. This problem was fixed in 10.4.

Meanwhile, we have a KB article to address this issue for 10.3/10.3.1. And Laurence should be able assistant this user on this(he is helping another user for similar problem).
*****

**Comment by pkdavidson** [comment]
That sounds quite familiar…

I discovered yesterday 70GB of backups and a drive with 0 space.
I freed up about 7GB and then we added another 100GB to the drive and used DriveManager to expand it out.

If they can get me the link to the KB article, I can probably self-help.

- Paul Davidson
GIS IT Lead
(505) 289-3225 – Desk
(505) 506-5960 – Cell

**Comment by pbobov** [comment]
Here is the link with some comments from Laurence.

**********
The backupretaindays and backupschedule can be set to a low number such as one day and then the data store service should be restarted.   If you set the value to a low number such as 1,  a backup will be taken within 24 hours and subsequently when the maintenance schedule runs at midnight it will initiate the process of cleaning up the walarchives.  The below KB provides further details.  FYI at 10.4 we have taken measures to help resolve this issue.

http://support.esri.com/en/knowledgebase/techarticles/detail/45295

**Comment by pkdavidson** [comment]
Thanks,
I had just found that article in the KB and was working through it.
However, I believe I tried this yesterday and kept getting the error message:
“Error encountered: The data store machine may not have been initialized.”

Yep, same issue.
“Error encountered: The data store machine may not have been initialized.”

Also, I notice that the DataStore windows service keeps ending up stopped.
I start it and then a bit later it’s stopped again.
Now this might be related to running the cmd line options but I don’t see a stop command in there.
But there’s a lot of java going on and I’m not going to dig down deep in .jar to see if there is a pkill or something going on.

There is another possible issue I forgot to mention which might be critical. (slap upside the head)
We mysteriously lost our provisioning license last night.
Turns out there was a hiccup in how the license was given to us and then not re-initialized when our new ELA kicked into effect.
Possibly related?
I re-provisioned this morning.

I just tried a reboot to be sure
Tried to repeat KB 45295 without any luck.  Same error msg:
“Error encountered: The data store machine may not have been initialized.”

I also tried to validate the Data Store as per:
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Validate_Data_Store/02r300000285000000/
This gives me the error:
Could not connect to server on machine 'T-AGS-ALLINONE.ABCWUA.ORG'. ArcGIS Server on that machine may not be running or the machine is not reachable at this time.

I’m going to go back to ground zero on Portal and DataStore and work through the admin pages.

Something has hiccupped and is not restarting or is incorrectly setup.
I also cannot get to the Data Store Configuration web page
https://localhost:2443/arcgis/datastore

When I just now tried to restart DataStore directly after a reboot, Win Services gave me the message:
“The ArcGIS Data Store service on Local Computer started and then stopped.  Some services stop automatically if they are not in use by other services or programs.”

- Paul Davidson
GIS IT Lead
(505) 289-3225 – Desk
(505) 506-5960 – Cell

**Comment by pbobov** [comment]
Try to change the logon account of Data Store windows service to Local System account (the default account used by the setup). The cookbook changes the account to 'arcgis' user account (this is required if backup folder is on a file share).

**Comment by pkdavidson** [comment]
Hi Pavel:
Because this was a dev box and I was having a variety of issues, I decided to just rebuild the setup.
I uninistalled DataStore, Portal, Web Adaptors and AGS.
I then deleted any remaining arcgisserver, arcgisportal and arcgisdatastore folder structures.
Ditto for things in Program Files (both 32 & 64 bit versions)

I then re-ran the Chef cookbooks which then failed on the webadaptor installation.
It looks to me like the cookbook things the webadapator software has been installed already when it hasn't.

I ran the cookbooks a second time (which explains why it says the AGS site is already installed) and I had verified that the folder C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\ did not exist.

I tried to run webadapator install by itself to get past this but without giving the server adaptor another name (you are using server, I believe) it failed.
I suspect something related to webadaptor was not correctly uninstalled so the cookbook thinks it can ignore the installation and go right to configuration?

I'll attach the full log file with mods to IPs and server names, user info etc...
I might as well attach the json file also.

Actually, guess I don't have write files for a text file.
Here's the pertinent error messages, I believe:
[2015-10-17T17:16:58-06:00] INFO: windows_service[ArcGIS Server] restarted
[2015-10-17T17:16:58-06:00] INFO: Processing arcgis_server[Authorize ArcGIS for Server] action authorize (arcgis::server line 29)
[2015-10-17T17:16:58-06:00] INFO: Processing execute[Authorize ArcGIS for Server] action run (C:\chef\cookbooks\arcgis\providers\server.rb line 85)
[2015-10-17T17:17:11-06:00] INFO: execute[Authorize ArcGIS for Server] ran successfully
[2015-10-17T17:17:11-06:00] INFO: Processing directory[C:\arcgisserver] action create (arcgis::server line 35)
[2015-10-17T17:17:11-06:00] INFO: Processing arcgis_server[Create ArcGIS for Server Site] action create_site (arcgis::server line 48)
[2015-10-17T17:17:11-06:00] INFO: URL http://localhost:6080/arcgis/ is available.
[2015-10-17T17:17:11-06:00] WARN: ArcGIS Server site already exists.
[2015-10-17T17:17:11-06:00] INFO: Processing arcgis_server[Enable SSL on ArcGIS Server Site] action enable_ssl (arcgis::server line 58)
[2015-10-17T17:17:12-06:00] INFO: Processing hostsfile_entry[Map server domain name to localhost] action append (arcgis::server_wa line 20)
[2015-10-17T17:17:12-06:00] INFO: hostsfile_entry[Map server domain name to localhost] content already matches - nothing to do.
[2015-10-17T17:17:12-06:00] INFO: Processing arcgis_webadaptor[Setup Web Adaptor for Server] action install (arcgis::server_wa line 26)
[2015-10-17T17:17:12-06:00] INFO: Processing execute[Run ArcGIS Web Adaptor Setup] action run (C:\chef\cookbooks\arcgis\providers\webadaptor.rb line 31)
[2015-10-17T17:17:12-06:00] INFO: Processing arcgis_webadaptor[Configure Web Adaptor with Server] action configure_with_server (arcgis::server_wa line 33)
[2015-10-17T17:17:12-06:00] INFO: Processing ruby_block[Wait for Server and WA] action run (C:\chef\cookbooks\arcgis\providers\webadaptor.rb line 79)
[2015-10-17T17:22:15-06:00] INFO: URL http://xxx.xx.xx.xxx:6080 is available.
[2015-10-17T17:22:15-06:00] INFO: ruby_block[Wait for Server and WA] called
[2015-10-17T17:22:15-06:00] INFO: Processing execute[Configure Web Adaptor with Server] action run (C:\chef\cookbooks\arcgis\providers\webadaptor.rb line 91)

================================================================================
Error executing action `run` on resource 'execute[Configure Web Adaptor with Server]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe" /m server /w "https://tstAllinOne.xxx.org/server/webadaptor" /g "http://xxx.xx.xx.xxx:6080 " /u "srvAcnt" /p "Pword" /a true ----
STDOUT: 
STDERR: The system cannot find the path specified.
---- End output of "C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe" /m server /w "https://tstAllinOne.xxx.org/server/webadaptor" /g "http://xxx.xx.xx.xxx:6080 " /u "srvAcnt" /p "Pword" /a true ----
Ran "C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe" /m server /w "https://tstAllinOne.xxx.org/server/webadaptor" /g "http://xxx.xx.xx.xxx:6080 " /u "srvAcnt" /p "Pword" /a true returned 1

Resource Declaration:
---------------------
# In C:\chef\cookbooks\arcgis\providers\webadaptor.rb

 91:     execute "Configure Web Adaptor with Server" do
 92:       command "\"#{cmd}\" #{args}"
 93:     end
 94:   else

Compiled Resource:
------------------
# Declared in C:\chef\cookbooks\arcgis\providers\webadaptor.rb:91:in `block in class_from_file'

execute("Configure Web Adaptor with Server") do
  action [:run]
  retries 0
  retry_delay 2
  default_guard_interpreter :execute
  command "\"C:\\Program Files (x86)\\Common Files\\ArcGIS\\WebAdaptor\\IIS\\Tools\\ConfigureWebAdaptor.exe\" /m server /w \"https://tstAllinOne.xxx.org/server/webadaptor\" /g \"http://xxx.xx.xx.xxx:6080 \" /u \"srvAcnt\" /p \"Pword\" /a true"
  backup 5
  returns 0
  declared_type :execute
  cookbook_name :arcgis
end

[2015-10-17T17:22:15-06:00] INFO: Running queued delayed notifications before re-raising exception
[2015-10-17T17:22:15-06:00] ERROR: Running exception handlers
[2015-10-17T17:22:15-06:00] ERROR: Exception handlers complete
[2015-10-17T17:22:15-06:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-10-17T17:22:15-06:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[Configure Web Adaptor with Server] (C:\chef\cookbooks\arcgis\providers\webadaptor.rb line 91) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe" /m server /w "https://tstAllinOne.xxx.org/server/webadaptor" /g "http://xxx.xx.xx.xxx:6080 " /u "srvAcnt" /p "Pword" /a true ----
STDOUT: 
STDERR: The system cannot find the path specified.
---- End output of "C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe" /m server /w "https://tstAllinOne.xxx.org/server/webadaptor" /g "http://xxx.xx.xx.xxx:6080 " /u "srvAcnt" /p "Pword" /a true ----
Ran "C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe" /m server /w "https://tstAllinOne.xxx.org/server/webadaptor" /g "http://xxx.xx.xx.xxx:6080 " /u "srvAcnt" /p "Pword" /a true returned 1


Let me know if you want to see the Chef stacktrace
Thanks

**Comment by pbobov** [comment]
Please check if you have 'portal' and 'server' folders under  "C:\inetpub\wwwroot\" directory. The cookbook assumes that an instance of Web Adaptor is already installed if a folder that matches the instance name is present in "C:\inetpub\wwwroot\" directory.

**Comment by pkdavidson** [comment]
Server folder is there....
Removed it and Rerunning Chef now, passed the error so should be ok
Thanks...

**Comment by pkdavidson** [comment]
that did it, thanks
