### ISSUE TITLE
Issue federating hosting server

### ISSUE THREAD

**Issue by arashm2** [Esri/arcgis-cookbook#250]
Hello,

I'm federating a hosting server with Portal. The Server has DataStore configured with it, and I'm also setting is_hosting parameter to true in Chef config file. The federation goes through without any issue, but it is not setting the Server as hosting. If I go to Portal and manually set it as hosting server there is no issue. 
There are no errors in the logs, but looking at the code, I see there's a sleep(180) right before it sets the Server as hosting. 
``` ruby
    if @new_resource.is_hosting
      sleep(180.0)
      portal_admin_client.update_server(server_id, 'HOSTING_SERVER', '')
    end
```

Is it possible the wait time is not enough due to Portal being busy? 
I'm using 3.5.0 release.

Thanks

**Comment by cameronkroeker** [comment]
Hello @arashm2,

What is the error being returned when attempting to set hosting server using Chef? It really shouldn't take that long to federate, however to test your theory you could try increasing it. Perhaps double the value to 360.

Thanks,
Cameron K.

**Comment by arashm2** [comment]
I did more testing and I sometimes get 405 gateway timeout error when I manually set the site as hosting from Portal setting page. Will open a ticket with ESRI. Thanks!
