### ISSUE TITLE
Support for Chef 15?

### ISSUE THREAD

**Issue by compuguy** [Esri/arcgis-cookbook#252]
Since Chef 14 is EoL as of April 30, 2020, when will these cookbooks support the currently supported version of Chef 15?

**Comment by pbobov** [comment]
ArcGIS Chef Cookbooks 3.6.0 that will be released in a few days will support Chef Client <= 14. 

Shortly after 3.6.0 release we plan to release ArcGIS Chef Cookbooks 3.6.1 where we plan to remove the upper bound check for chef_version form the cookbooks' metadata and test the cookbooks with Chef Client 15.

We will update this thread if/when we have more details about Chef Client 15 support.

**Comment by cameronkroeker** [comment]
Support for Chef 15+ has been added to cookbook v3.6.1:

https://github.com/Esri/arcgis-cookbook/releases
