### ISSUE TITLE
String for Protocol to set both HTTP and HTTPS

### ISSUE THREAD

**Issue by anshacm** [Esri/arcgis-cookbook#255]
Please let me know what string needs to be set in the attributes to enable both HTTP and HTTPS. I was able to set it as either HTTP or HTTPS. I tried by giving multiple strings in attribute but, nothing worked. Can someone suggest what should be the right attribute value for server['protocol']  to set both HTTP and HTTPS?

Protocol: HTTP And HTTPS

**attribute:** 

server['protocol'] = 'HTTPS'

**Recipe:**
================
# Update server security config
arcgis_enterprise_server 'Configure Security Protocol' do
  server_url node['arcgis']['server']['url']
  username node['arcgis']['server']['admin_username']
  password node['arcgis']['server']['admin_password']
  protocol node['arcgis']['server']['protocol']
  authentication_mode node['arcgis']['server']['authentication_mode']
  authentication_tier node['arcgis']['server']['authentication_tier']
  hsts_enabled node['arcgis']['server']['hsts_enabled']
  virtual_dirs_security_enabled node['arcgis']['server']['virtual_dirs_security_enabled']
  allow_direct_access node['arcgis']['server']['allow_direct_access']
  allowed_admin_access_ips node['arcgis']['server']['allowed_admin_access_ips']
  retries 5
  retry_delay 30
  action :configure_security_protocol
end
=======================

**Comment by cameronkroeker** [comment]
Hello @anshacm ,

Try : 
```
"arcgis" : {
  "server" : {
       "protocal":"HTTP_AND_HTTPS"
     }
},
```
The acceptable values are:

HTTP
HTTPS
HTTP_AND_HTTPS

https://developers.arcgis.com/rest/enterprise-administration/server/securityconfig.htm

**Comment by anshacm** [comment]
@cameronkroeker : That worked perfectly.. Thank you!!!
