### ISSUE TITLE
Portal WebAdaptor not unpacked before installation

### ISSUE THREAD

**Issue by arashmalekz** [Esri/arcgis-cookbook#256]
Hello,

The unpacking step before installing WebAdaptor for Portal doesn't work (version 3.5.0 for Windows). Issue is I believe a typo on Line 27 in install_portal_wa.rb.
I changed "node['arcgis']['server']['wa_name']" to "node['arcgis']['portal']['wa_name']" and it worked

**Comment by cameronkroeker** [comment]
Good catch @arashm2! This will be fixed in the next release.
