### ISSUE TITLE
unfederating recipe

### ISSUE THREAD

**Issue by thk70** [Esri/arcgis-cookbook#265]
When uninstalling a federated ArcGIS server it leaves an unavailable server instance on the portal. It would be nice to have an "unfederating" recipe, that changes the Authentication tier and deletes the server instance on the portal.
Thanks.

**Comment by cameronkroeker** [comment]
Hello @thk70,

We have added an unfederate_server recipe in release [v3.8.0](https://github.com/Esri/arcgis-cookbook/releases/tag/v3.8.0):

https://github.com/Esri/arcgis-cookbook/wiki/arcgis%E2%80%90enterprise-Cookbook-Recipes#unfederate_server

Thanks,
Cameron K.
