### ISSUE TITLE
Configure Portal System properties to set Proxy

### ISSUE THREAD

**Issue by DamienB-ESRI** [Esri/arcgis-cookbook#273]
The capability to configure the Portal Properties to set the proxy settings would be good. I cant see that the attribtures are available to configure such for Portal, in the recipe cookbooks.

**Comment by cameronkroeker** [comment]
Hi @DamienB-ESRI,

This is a great feature request, and it will be added to the next release of cookbooks (v3.7.0).

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
@DamienB-ESRI pleased to let you know this capability has been added to the latest release, v370!

Attribute **node['arcgis']['portal']['system_properties']** = Portal for ArcGIS system properties. Default value is {}.

An example can be found here:

https://github.com/Esri/arcgis-cookbook/blob/master/templates/arcgis-enterprise-base/10.9/windows/arcgis-enterprise-primary.json#L72-L75

**Comment by DamienB-ESRI** [comment]
HI Cameron,

   This is excellent news - well done for getting that in to this release. It was one of the only manual steps we had to complete.
I am actually leaving ESRI now to join GitHub so I will definitely keep an eye on the ESRI GitHub pages..
I have encouraged my colleagues to be active members of the Chef / ESRI open source community.

Best,
Damien.
