### ISSUE TITLE
Is federation recipe required while adding a node to server that is already federated?

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-cookbook#274]
While trying to setup the single machine base enterprise deployment in HA using the `arcgis-enterprise-windows-ha-primary.json` and `arcgis-enterprise-windows-ha-secondary.json` roles, I noticed that the secondary json also includes the federation recipe at the end. 

Since we are only adding a node to the server site by joining to the primary server site, and this server is already federated with the primary portal, do we need to include the federation recipe in the secondary json?

**Comment by cameronkroeker** [comment]
Hi @anandak,

No in the case where joining a machine to an existing ArcGIS Server site that is already federated, the federation recipe is not needed.

Thanks,
Cameron K.

**Comment by anandak** [comment]
Thanks! that answers my question and the example role for `arcgis-enterprise-windows-ha-secondary.json`  provided in this repository needs to updated to reflect that, as it still includes the federation recipe at the end.
