### ISSUE TITLE
Unable to install raster analytics role - fails with reason "the server does not have a raster data store" 

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-cookbook#276]
Hi, I have a single machine base enterprise deployment and I have added a separate machine with image server installed and set it as image hosting server in Portal. Everything went well up to this point.

While trying to stand up another machine with raster analytics role, it completes the installation, site creation, federation, but fails at the `action_enable_server_function` block with following error:

> RuntimeError: arcgis_enterprise_portal[Enable RasterAnalytics] (arcgis-enterprise::enable_rasteranalytics line 20) had an error: RuntimeError: Failed to update federated server 'machine.domain.com:6443 (id: dxtjTtlXXKQZNOJN)'. Validation failed; the server does not have a raster data store.

I do not see any settings for defining a raster data store in the JSON roles. 
How do we set up a raster data store ?

**Comment by cameronkroeker** [comment]
@anandak prior to enabling Raster Analytics will need to manually register a file share a raster store.

https://enterprise.arcgis.com/en/server/latest/manage-data/windows/registering-your-data-with-arcgis-server-using-manager.htm#ESRI_SECTION2_58F75EEE66634C6BB4A8F26C12DCCDA9

However, in the next release of cookbooks v3.7.0 (Mid May 2021), there will be the ability to register a file share as a raster store. There will be a dedicated recipe for this, as well as json file examples for both Windows and Linux.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hello @anandak,

This capability has been added to the latest release, v370!

Example usage can be found here:

https://github.com/Esri/arcgis-cookbook/tree/master/templates/arcgis-server/10.9

Can use the [arcgis-server-fileserver.json](https://github.com/Esri/arcgis-cookbook/blob/master/templates/arcgis-server/10.9/windows/arcgis-server-fileserver.json) to create the raster store share, and then use [arcgis-server-raster-store.json](https://github.com/Esri/arcgis-cookbook/blob/master/templates/arcgis-server/10.9/windows/arcgis-server-raster-store.json) to register the raster store.

Thanks!
