### ISSUE TITLE
ChefDK is deprecated 

### ISSUE THREAD

**Issue by awittner** [Esri/arcgis-cookbook#277]
According to CHEF, ChefDK is deprecated. Cookbook workflows in the doc call for installing ChefDK. Can you update the workflows to correct for this change?

**Comment by cameronkroeker** [comment]
Hi @awittner ,

Great find! I have updated the Linux doc:

https://github.com/Esri/arcgis-cookbook/wiki/Automate-a-multi-machine-ArcGIS-Enterprise-deployment-on-Linux-using-Chef-Server#2-on-the-chef-workstation-machine-install-chef-workstation

Stay tuned for the Windows one.

Happy Automating,
Cameron K.

**Comment by awittner** [comment]
I am in need of the windows version 😊

From: Cameron Kroeker ***@***.***>
Sent: Thursday, April 15, 2021 16:04
To: Esri/arcgis-cookbook ***@***.***>
Cc: Wittner, Amber N ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Esri/arcgis-cookbook] ChefDK is deprecated (#277)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @awittner<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fawittner&data=04%7C01%7Cawittner%40usgs.gov%7C0c5372003bf0488b4e4c08d90062ce84%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637541246641865217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yLIAy1BqSQ%2FYL7pXWsY4HJmY7voOBAPrnliucs021TQ%3D&reserved=0> ,

Great find! I have updated the Linux doc:

https://github.com/Esri/arcgis-cookbook/wiki/Automate-a-multi-machine-ArcGIS-Enterprise-deployment-on-Linux-using-Chef-Server#2-on-the-chef-workstation-machine-install-chef-workstation<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEsri%2Farcgis-cookbook%2Fwiki%2FAutomate-a-multi-machine-ArcGIS-Enterprise-deployment-on-Linux-using-Chef-Server%232-on-the-chef-workstation-machine-install-chef-workstation&data=04%7C01%7Cawittner%40usgs.gov%7C0c5372003bf0488b4e4c08d90062ce84%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637541246641875174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ul1vnEAfPOJGBRRFNiaSTIVa5fnC8I61Zx0imHj%2B1mw%3D&reserved=0>

Stay tuned for the Windows one.

Happy Automating,
Cameron K.

**Comment by cameronkroeker** [comment]
> I am in need of the windows version 😊

Hi @awittner , sorry for the delay, I have updated the Windows doc:

https://github.com/Esri/arcgis-cookbook/wiki/Automate-a-multi-machine-ArcGIS-Enterprise-deployment-on-Windows-using-Chef-Server

Cheers!
