### ISSUE TITLE
Running the recipe for installing patches keeps failing with a timeout

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-cookbook#283]
Trying to install patches for a fresh install of base enterprise deployment of 10.8.1. The role json contains only one recipe for installing patches and includes the correct repository path for patches folder in network location. 

We are using v3.6.1 of cookbook. Initially we observed a timeout error and noticed the update in patches.rb in latest version which increased the timeout to one hour. We added the same line locally in patches.rb and uploaded to chef server and ran the recipe again.

However this time, it is still failing with a timeout error after an hour. I have attached the debug log of chef run.
[Patch installation chef run log.txt](https://github.com/Esri/arcgis-cookbook/files/6445825/Patch.installation.chef.run.log.txt)

When I install the patch manually by remoting into the machine with the same user mentioned in role json, it works fine.

This is the role json file
![image](https://user-images.githubusercontent.com/1454027/117538208-c4ad4b00-b022-11eb-9ca6-3307ad8c188e.png)

**Comment by cameronkroeker** [comment]
Hi @anandak,

How long does the patch take to successfully complete when manually installing?

`"\\aws-harman1\arcgis-repo\patches\bed\arcgis-1081-pfa-awg-patch.msp"   /qn`

Have you tried increasing it above 1 hour? Perhaps try 2 hours (7200).

Thanks,
Cameron K.

**Comment by anandak** [comment]
When installing manually, I could install 3-4 patches within an hour, out of the full list of 8 patches for portal 10.8.1.
I tried increasing the timeout to 24 hours and it still I see the same error of time out, with no indication of how many were successful, none were installed.

**Comment by cameronkroeker** [comment]
Hi @anandak,

I am now thinking there is something else causing the timeout, like perhaps the *.msp installer is asking for user input but since its silently being installed `\qn` we are not seeing it. Can we try updating the following to `/qb`:

https://github.com/Esri/arcgis-cookbook/blob/f973da68d5d092ebedc005bc9b79611e5aa5aaba/cookbooks/arcgis-enterprise/providers/patches.rb#L32

Hopefully this will display a basic UI and may give us some more insight.

Thanks,
Cameron K.

**Comment by anandak** [comment]
Hi @cameronkroeker 

We tried this with chef-server (12.19) as well as chef-solo(14.14.29) with `/qb` in patches.rb.
We saw the GUI only when using chef-solo. When doing a run using chef-server, we did not see a GUI on that node.

Both are still failing with a timeout.

**Comment by anandak** [comment]
Hi @cameronkroeker that was it! thank you so much for pointing us in the right direction. 
Once we added the exception, everything was fine and we were able to successfully install all patches.
thanks again, closing.
