### ISSUE TITLE
Setting admin url of federated servers to webcontext url when in HA 

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-cookbook#289]
Hi @cameronkroeker, we have successfully done a multi machine base enterprise deployment of 10.8.1 in Amazon cloud. All machines are in HA, i.e., web adaptor, portal, server and data store. This is fronted by the Amazon's load balancer which we are using as the web_context_url. 
However we see that during federation, the `web_context_url` is used only for the `services URL` while the `administration URL` is set to the `private_url (6443)`. According to ArcGIS help docs, it seems that when in HA, you should use the load balancer URL for the `administration URL` too.
Here is a snip from help docs below:
![image](https://user-images.githubusercontent.com/1454027/121874099-abd03d80-cd24-11eb-9686-f1b47f7678c4.png)

In the role JSON we have to specify the private_url which uses the 6443 port and web_context_url, which is the load balancer URL. How can we accomplish the above configuration using the role JSON file? Is this the recommended way to federate when using HA?

**Comment by cameronkroeker** [comment]
Hello @anandak,

In HA deployments it is recommended to use a load balanced url for both the web_context_url (services URL) and a load balanced URL for private_url. The private_url can be the same as your web_context_url or it can be over port 6443. It all depends on how you configure your load balancer/web adaptors. Here are two different examples:

**Example 1:** Using an External Load Balancer (443) & Internal Load Balancer (6443).

External Load Balancer (443) -> Web Adaptors (443) = services URL (web_context_url)
https://external_loadbalancer.domain.com/server -> https://server_webadaptor_1.domain.com/server & https://server_webadaptor_2.domain.com/server

Private Load Balancer (6443) -> Internal Server URLs = Administration URL (private_url)
https://internal_loadbalancer.domain.com:6443/arcgis -> https://server_1.domain.com:6443/arcgis & 
https://server_2.domain.com:6443/arcgis

```
"server": {
    "web_context_url":"https://external_loadbalancer.domain.com/server",
    "system_properties":{
        "WebContextURL":"https://external_loadbalancer.domain.com/server"
    },
    "private_url":"https://internal_loadbalancer.domain.com:6443/arcgis"
}
```
**Example 2:** Using an External Load Balancer for both web_context_url and private_url.
> Note: Administrative access must be enabled on ArcGIS Web Adaptors

External Load Balancer (443) -> Web Adaptor (443) = services URL (web_context_url) & administration url
https://external_loadbalancer.domain.com/server -> https://server_webadaptor_1.domain.com/server & https://server_webadaptor_2.domain.com/server

```
"server": {
   "web_context_url":"https://external_loadbalancer.domain.com/server",
   "system_properties":{
       "WebContextURL":"https://external_loadbalancer.domain.com/server"
    },
   "private_url":"https://external_loadbalancer.domain.com/server"
},
"web_adaptor": {
   "admin_access": true
}
```

**Comment by anandak** [comment]
Apologies for delay in getting back, but thank you! this really helps.
