### ISSUE TITLE
10.3.1 to 10.4 with Chef

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#29]
If we installed 10.3.1 (Portal, Hosting Server, Data Store, WebAdaptors, etc..) with the Chef Cookbook, do we need to uninstall and re-install 10.4 with the new Cookbook.

Or can we just download the Cookbook and json files for 10.4, massage as appropriate and rerun Chef?

I believe 10.4 is able to update 10.3.1 to 10.4 but can that be done using Chef?
I believe that's one of the Benefits of Chef, to re-provision easily?
But Portal is a bit more complicated than a MSoft Office installation.

Thanks for the info

**Comment by g3r4n** [comment]
:+1:

**Comment by pbobov** [comment]
2.2.0 Chef cookbook does not support upgrade from 10.3.1 to 10.4. Supporting upgrades is on our TODO list, but we are not there yet. For some simple cases upgrade would probably just work, but for complex deployments with portal and Web Adaptors it will not be a smooth ride.

**Comment by pkdavidson** [comment]
Thanks Pavel.
So best practice will be to do a full uninstall and then re-install with the new cookbooks

**Comment by pbobov** [comment]
Yes. So far the cookbook works best on clean machines. 

The cookbook provides recipes for uninstalling 10.4 software, but you cannot use it to uninstall 10.3.1 software, unless you specify 10.3.1 product codes for all the apps in the JSON attributes. 

Installation and un-installation logic in the cookbook relies on product codes. This gets a bit tricky in the case of Web Adaptor that can have multiple product codes for one setup and the mapping between product codes and WA instances depends on the installation order. We are trying to sort that out...

**Comment by pbobov** [comment]
More specific "Installation, un-installation, and **upgrade** logic in the cookbook relies on product codes.

**Comment by pkdavidson** [comment]
Very helpful...
Sounds a bit like if I were to hand uninstall the Web Adaptors, then the 10.3.1 uninstall could be automated more easily in Chef.  

In my case, I've held off on a Production Portal waiting for 10.4 to come out since it had some features that seemed most useful.  

To clarify, if we were to want upgrade from 10.3.1 to 10.4, then we would be better off doing it outside  of Chef.  I mean, do the upgrade installation by hand, one machine/system at a time.

**Comment by pbobov** [comment]
Yes. I recommend manual upgrade workflow from 10.3.1 to 10.4. So far, all bets are off if you are using Chef for upgrades.

**Comment by pkdavidson** [comment]
Thanks for all the info Pavel.

**Comment by pkdavidson** [comment]
Reopened to ask some questions:
webgis-windows-uninstall.json  --> only good for 10.4 uninstall, right?

Noticed some changes with the webgis-windows.json file:
First, the arcgis{ section now encompasses everything to right before the runlist.
I assume that's not a typo but a change in scoping you've made?

Next:
This file no longer has domain names in it (they're now in the ha and pa json files... more about that later)

And: The datastore section no longer needs the 	 "preferredidentifier" : "hostname"   added?
I forget the reason for that but seem to recall it was important.

Finally, I'm assuming we grab the appropriate json file from the roles folder and put it into \\Chef\ 
and run from there.

Many thanks for the additional install files for lic mgr, desktop, and pro...
I'm assuming we could setup a Chef server and then it would be much easier to deploy across the domain by using the cookbooks?

Looking at the arcgis-licensemanager.json file, since this doesn't refer to provisioning files, I assume we do that by hand after the install?  
But that at some point you'll add that functionality to the license manager chef cookbook so that we'd really gain benefit from using Chef for LM.  And adding in uninstalling and de-provisioning to automate a full LM install would be great stuff.  

As it stands, what is the benefit to using Chef to install LM?  
I don't mean this in any negative way!  I'm just wondering if I'm not understanding something.
It looks like the work is still mostly done by hand to:
 return licenses, remove the prior version, get new provision files and then install new LM.

Don't get me wrong, I understand this is a work in progress and there are only so many hours in a day.
:-)    If I had the time, I'd learn Chef and try to help this project but ....  

I'm looking forward to getting the Dev allinone box going and then moving to our Test and Production environments with HA!

**Comment by pbobov** [comment]
Yes. webgis-windows-uninstall.json is only good for 10.4 uninstall. You can use it with 10.3.1 if you specify product codes for 10.3.1 applications there.

Yes. Now "arcgis" encompasses all attributes of "arcgis" cookbook. This is a chef convention that we ignored in earlier versions of the cookbook.

The domain names are still supported. If domain names  are not specified, then FQDN of the machine is used. We probably should add the domain names back to the JSON file, but on the other hand it's going to be a bit confusing for simple deployments. 

Now node['arcgis']['datastore']['preferredidentifier'] = 'hostname' by default (which is a default value for datastore). In previous versions of the cookbook it was set to 'ip' (which is not typical).

"Finally, I'm assuming we grab the appropriate json file from the roles folder and put it into \Chef\ 
and run from there." Yes that is the idea, but we still need to work on making a clean and representative collection of "roles". Any ideas are welcome here. 

Frankly speaking, the "desktop-side" of the cookbook (desktop, Pro, LM) was a bit overlooked by us,  because we expected the cookbook to be used mostly server-side (server, portal, DS, WA, GEE, etc).  So the desktop-side resources currently only support basic functionality. Yet, it looks like there is a lot of interest in using Chef to install desktop, Pro, & LM, so we will probably improve support of the "desktop-side" in the next releases.

**Comment by pkdavidson** [comment]
Excellent, thanks for the answers.

I think you're on the right track with this.
As for roles, that is the part that as a novice is a bit confusing.  I mean figuring out which role to use.  I like the separation into the separate folder.  It helps me to understand that I need to pick out the role I want to work with.

Right now I have some questions about the HA vs. the all in one deployment but those questions are for a separate thread once I get a chance to work on the separate box setups.

I think the idea of using Chef to install and update Desktop and Pro is a great one but I think it means we would need to have a Chef server we could use.  Otherwise, installing the stand alone client on each desktop becomes more work than just installing the Arc software on the desktop itself.
I'm still very new to Chef and frankly don't have the time to learn much so having the canned recipes is very helpful.

As I understand it, from a manager perspective, it would be great to have Chef setup to install desktop across the domain, update as needed, etc...  All from one location and under our control.  Like most software pushes except that Esri is a more complicated product than most.

What might be very useful is a simple readme in the roles folder that explains differences between similar json files?  Actually, I guess the only ones that need explaining are the webgis ones and then really just the windows, windows-ha-primary and windows-ha-secondary.  I get it now but the first time around with 1.1, it was a bit confusing figuring out which to use.

I did notice the individual product json files, under arcgis section no longer include the username and password like they did in the past.  I dropped them back in there thinking they're needed but I'm not sure that's the case.  Since I'm already logged into run the cookbook, say for example ArcGIS-desktop.json, then it will install under my current login?  It's only the enterprise level stuff (server/portal) that need a consistent user name for the install?  (and need user and pword to be able to login across the domain.)

Thanks again for this work.  

I think the new wiki page (#3) is very helpful in explaining this.

**Comment by pbobov** [comment]
Desktop and pro run under the user account of the logged in user. LM seems to run under local system account. Server, Portal, and Data Store require a specific user account (to access file shares).

Automating desktop installation with Chef I think could be interesting for teaching and demo environment (where a new set of desktop VMs is required for each new class).

**Comment by pkdavidson** [comment]
One question, I'm trying to install using a domain account.
"mydomain\myDomainAcnt"

I remember this was originally not allowed but then was put into R1.1.3 or 1.1.2?

Is this allowed in 2.2?

**Comment by pbobov** [comment]
Yes. The new version of the cookbook should support domain accounts.

The doman_name is the public FQDN domain name (myserver.mydomain.org) that will be used by the clients. It should resolve to the machine's IP address, or to the load balancer's domain name, if any.

**Comment by pkdavidson** [comment]
Thanks....
It appeared to take the domain account just fine.  
I did start another thread about install issues so I'll close this.
Your help and quick responses have been much appreciated.
