### ISSUE TITLE
Template for ArcGIS Enterprise upgrade

### ISSUE THREAD

**Issue by Ayushyadav19** [Esri/arcgis-cookbook#294]
Hi,
I just wanted to know when we will have the templates for the ArcGIS enterprise upgrade. 

As mentioned in the 10.9 readme that template will be provided in the subsequent releases. Is there any tentative timeline for the next release? So that we will have the template for the ArcGIS enterprise upgrade.

![image](https://user-images.githubusercontent.com/70343349/144364232-223c53c9-8c33-4192-9844-5c452fde0b6d.png)

**Comment by cameronkroeker** [comment]
Hello @Ayushyadav19,

We have added upgrade deployment templates in release [v3.8.0](https://github.com/Esri/arcgis-cookbook/releases/tag/v3.8.0).

https://github.com/Esri/arcgis-cookbook/tree/master/templates/arcgis-enterprise-base/10.9.1#upgrade-workflow

Thanks,
Cameron K.
