### ISSUE TITLE
10.9.1 Portal file name

### ISSUE THREAD

**Issue by ramtechjoe** [Esri/arcgis-cookbook#298]
In the [10.9.1 ReadMe](https://github.com/Esri/arcgis-cookbook/tree/master/templates/arcgis-enterprise-base/10.9.1#readme) the file name for Portal is listed as:
**Portal_for_ArcGIS_Windows_1091_177786**

However, the file name for Portal from the download is:
**Portal_for_ArcGIS_Windows_1091_180052**

Is this a misprint in the ReadMe or is the script looking for the wrong file?

**Comment by cameronkroeker** [comment]
> In the [10.9.1 ReadMe](https://github.com/Esri/arcgis-cookbook/tree/master/templates/arcgis-enterprise-base/10.9.1#readme) the file name for Portal is listed as: **Portal_for_ArcGIS_Windows_1091_177786**
> 
> However, the file name for Portal from the download is: **Portal_for_ArcGIS_Windows_1091_180052**
> 
> Is this a misprint in the ReadMe or is the script looking for the wrong file?

Hello @ramtechjoe,

Great catch! It's typo in the ReadMe. The file name is correct in the actual cookbooks, so it should still work fine:

https://github.com/Esri/arcgis-cookbook/blob/1c7f39341a4a967c6c73a20ee0b6bbb5b2a3dc53/cookbooks/arcgis-enterprise/attributes/portal.rb#L108-L111

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
This has been updated in [Chef for ArcGIS Cookbooks v4.0.0.](https://github.com/Esri/arcgis-cookbook/releases/tag/v4.0.0)

https://github.com/Esri/arcgis-cookbook/tree/master/templates/arcgis-enterprise-base/10.9.1#required-arcgis-software-repository-content

and

https://esri.github.io/arcgis-cookbook/templates/arcgis-enterprise-base/10.9.1.html#required-arcgis-software-repository-content

Thanks,
Cameron K.
