### ISSUE TITLE
Add to single machine installation documentation: cinc-solo

### ISSUE THREAD

**Issue by jesa-esrich** [Esri/arcgis-cookbook#299]
In the arcgis-cookbook [wiki for deploying a base ArcGIS Enterprise deployment on a single machine](https://github.com/Esri/arcgis-cookbook/wiki/Deploy-a-base-ArcGIS-Enterprise-deployment-on-a-single-machine), the command prompt for running the cinc client is: `cinc-client -z -j arcgis-enterprise-primary.json`

It will then create a directory in the user profile: _C:\Users\username\.cinc\local-mode-cache\cache\cinc-client-running.pid_
This causes issues, when the user profiles are managed on a share (E.g. when it can't create that directory). The command will then throw an error and stop.

In those cases it is better to use the command: `cinc-solo -j C:\cinc\templates\arcgis-enterprise\10.9.1\windows\arcgis-enterprise-primary.json` (as it used to be with Chef Client).

The possibility to use the command `cinc-solo` was not documented in the wiki, nor on [cinc webpage](https://cinc.sh/start/client/).

So please add this information (possibility of using the cinc-solo command) to the single machine installation documentations.

**Comment by cameronkroeker** [comment]
@jesa-esrich we have made some improvements to the documentation that both chef-client/cinc-client and chef-solo/cinc-solo can be used.

https://esri.github.io/arcgis-cookbook/support/faqs.html#what-is-the-difference-between-chef-infra-and-cinc

Thanks,
Cameron K.
