### ISSUE TITLE
Install with Chef 2.2

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#30]
We're having a failure with Software Authorization.
I've tried entering in what have been valid keys and the SA software says it has authorized fine but then it pops back up asking for a provisioning file.

Some of the Chef output:
[2016-02-24T18:49:11-07:00] INFO: ruby_block[Wait for 'ArcGIS Server' service to start] called
[2016-02-24T18:49:11-07:00] INFO: Processing arcgis_server[Authorize ArcGIS for Server] action authorize (arcgis::server line 33)
[2016-02-24T18:49:11-07:00] INFO: Processing execute[Authorize ArcGIS for Server] action run (C:\chef\cookbooks\arcgis\providers\server.rb line 171)
[2016-02-24T18:52:07-07:00] INFO: Retrying execution of execute[Authorize ArcGIS for Server], 2 attempt(s) left
[2016-02-24T18:59:33-07:00] INFO: Retrying execution of execute[Authorize ArcGIS for Server], 1 attempt(s) left
[2016-02-24T19:14:16-07:00] INFO: Retrying execution of execute[Authorize ArcGIS for Server], 0 attempt(s) left

================================================================================
Error executing action `run` on resource 'execute[Authorize ArcGIS for Server]'
================================================================================

However, when I opened the Server Manager, I was able to create a new site ok with the same admin name as in the json file.. 

Something odd is going on.  One of my coders could not create a new site earlier today.  He was doing things by hand.

I have an email in to our account rep.
And I seem to recall something similar going from 10.3 to 10.3.1, we had to have all new keys issued.

But this is odd that I could create the site in Server Manager.  And the logs show no errors.
I'm re-running the cookbook now to see if this jumps us past this hurdle.
I do see ArcGISServer running and three ArcSOCs.

The wiki mentions running Chef twice during the install.  Run the second time after a reboot.
But is that an automated reboot or do I wait for Chef to "finish" the first time, then reboot and then rerun it?  Should that be after the above authorization issue stopped Chef?

I'm seeing in the log that it looks like now things took and that a Web Adaptor is being installed, then the Data Store, etc...

Should I reboot at the end and then rerun the cookbook again?

**Comment by pbobov** [comment]
I suspect it's an issue with the software authorization service being unavailable. (When .prvc file is used for software authorization, SoftwareAuthorization.exe calls home to get the keys, and sometimes it fails :(. 

Also please check if the software authorization file path is correct.

Reboots are not required on Windows Server 2102 R. On earlier windows version it is sometimes required to complete installation of IIS on a clean machine. Typically, you will see an error message like 'W3C service not found' in the chef run log.

**Comment by pkdavidson** [comment]
I do recall the IIS reboot issue....  Glad its gone!

Update: last night an Erlang window popped up during Portal install phase.
I went home at that point.

This morning, Chef had finished, no errors in the log, the normal WARN msgs about using an LWRP provider, previous & current user, and cloning an attribute from a prior resource.  All of which seems familiar.

The Erlang window was still open.  I assume this can be closed at this point?

The hiccup was always in the Software Authorization retries (as mentioned above) but I could create the site by hand or so it appears.  

In my last SA attempt I chose to skip the .prvc file and do it using the internet.  It appeared successful that way.  But the prior 3 tries with two different .prvc files and key codes (we have an ELA and I have an EDN so I tried both an ELA and an EDN code) kept showing success but then popping back up the SA dialog box.  And the key code I finally used was the same as one tried previously.

What is odd regarding the SA is that doing it via the "manual" process, the dialog box connected to Esri and said it was successful but then the manual install box kept popping up.
I'll try this again when doing the HA version and see what happens.

One comment regarding the Wiki and this process.
It's been awhile since I first built a Portal (by hand or via Chef)
What would be helpful at this stage is to have the Wiki point to a help page as for the next steps.

There's so much help out there and the install pages have a lot of detail.
I'm left thinking, ok, now what. :-)
I believe at this point, I start setting up Portal by going to the home page, logging in with the Admin account and go from there.

Note: when I did that, it gives me a 403 error because it wants to open http.  I just change the URL to https and things come up fine.
I recall I had to fix this in the past by going to settings and turning on Https only in Portal.

This time I'm seeing something even stranger though.
for example, I clicked on My Content and pulled an error but not a 403 because the URl was not cleared but combined the http with https:
http://mydomain/portal/home/https://mydomain/portal/home/content.html

When I fix it to https://mydomain/portal/home/content.html, everything works ok.
but clicking on any menu item does the same thing: prepends that http://mydomain/portal/home/ to the https address.

Odd stuff!

I did set Portal to be https only but that didn't fix this weirdness.
I'll reboot the server and my PC and see if this doesn't clear some caching or something.

**Comment by pkdavidson** [comment]
NOTE:  when I went to https, then the URL doubling went to 
https://mydomain/portal/home/https://mydomain/portal/home/content.html

The one menu item that sets the URL correctly is clicking on Edit Settings.

**Comment by pbobov** [comment]
Doubling URLs is a new phenomenon for me. I forwarded your question to the portal developers.

As for the popups during software authorization, please check if your authorization file (*.prvc ?) has all the required information, in particular e-mail address. If some information is missing, then silent authorization does not work and it pops up a dialog box for additional user input.

Internally, we use .ecp files (key codes) for authorization of server software, in that case SA does not call home and does not display popups. I'm not sure if this is a valid approach for end users, though.

**Comment by pkdavidson** [comment]
Yep, the doubling is odd, never seen that in any website.
Makes me think it's just a flaky browser and a reboot will take care of it.
I'll let you know once I have a chance to reboot.

But I have had Portal try to open http until I set it to be https only.
I think that only happens when Server is to https only.
I'll have to try Server mixed and Portal mixed and see what happens.

**Comment by pkdavidson** [comment]
BTW - Chef Client 12.5.1, not 12.6 or 12.7 ?

**Comment by pbobov** [comment]
We typically tested the cookbook with Chef-Client 12.5.1. I tried 12.7 once before releasing it, found a few problems and fixed them. Yet, I recommend 12.5.1 if you don't really want to be far ahead of others in learning the Chef features :)

**Comment by pkdavidson** [comment]
Thanks...
Considering how far behind I am...  I'll stick 12.5.1

BTW - I rebooted both the server and my desktop PC.  
Still getting the odd URL doubling.  
But only with IE 11 with compatibility mode on.
I just turned off compatibility mode and the doubling went away.
Unfortunately, we need compatibility mode for our domain.

Having another issue.  I'll start a new thread.
