### ISSUE TITLE
BUG/Enhancement: Recipe arcgis-enterprise datasources not working with cinc client

### ISSUE THREAD

**Issue by jesa-esrich** [Esri/arcgis-cookbook#300]
The registering of datasources does not work when using the cinc-client in ArcGIS Chef Cookbooks 10.9.1.

**Main cause:**

- The path for the python scripts (misc_scripts) for registering datasources is hardcoded in the datasources recipe (...\cookbooks\arcgis-enterprise\attributes\datasources.rb) as 'C:\\Chef\\misc_scripts'
- If you follow  the instructions in the wiki, the cookbooks must be extracted in c:\cinc
- This will run into an error as when running the cookbooks and registering a datasources, as the path of misc_script do not match.

**Expected Behavior:**

- The script automatically recognizes where the Cookbooks are extracted.
- That way the user does not have to place the misc_scripts at another location or change the code in the cookbooks
- This would also guarantee, that the user can either use the chef or cinc clients.

**Comment by cameronkroeker** [comment]
@jesa-esrich Great catch! As a workaround you can extract the cookbooks to `C:\Chef`when using cinc-client or cinc-solo. 

You can pass in the path to the cookbook by using the following commands:

```
chef-client -z --config-option "cookbook_path=C:\chef\cookbooks" -j C:\path_to\your_json_config_file.json
```

or

```
cinc-solo --config-option "cookbook_path=C:\chef\cookbooks" -j C:\path_to\your_json_config_file.json
```

**Comment by cameronkroeker** [comment]
Hi @jesa-esrich,

I looked into this a bit more. You can actually still use `C:\cinc` as your cookbook directory and `C:\cinc\misc_scripts`. To do this you will need to define the `node['arcgis']['misc']['scripts_dir']` attribute within your json config file so that it overrides the default value:

https://github.com/Esri/arcgis-cookbook/blob/1c7f39341a4a967c6c73a20ee0b6bbb5b2a3dc53/cookbooks/arcgis-enterprise/attributes/datasources.rb#L21

**For example:**

```json
{
    "arcgis": {
        "version": "10.9.1",
        "server": {
       
        },
	"datasources": {
	 
        },
	"misc": {
	    "scripts_dir": "C:\\cinc\\misc_scripts"
	}
    },
    "run_list": [
        "recipe[arcgis-enterprise::datasources]"
    ]
}
```

Thanks,
Cameron K.

**Comment by jesa-esrich** [comment]
Hi @cameronkroeker 

Thanks, that is good to know.

**Comment by cameronkroeker** [comment]
Updated the recipe to include `node['arcgis']['misc']['scripts_dir']` attribute.

https://github.com/Esri/arcgis-cookbook/wiki/arcgis%E2%80%90enterprise-Cookbook-Recipes#datasources
