### ISSUE TITLE
Portal Web Styles not removed with enterprise_uninstalled recipe

### ISSUE THREAD

**Issue by ramtechjoe** [Esri/arcgis-cookbook#303]
Running the enterprise_uninstalled recipe does not remove Portal Web Styles .  Could this be added?

Thanks

**Comment by cameronkroeker** [comment]
Hi @ramtechjoe,

This is a great suggestion! We will look to get this feature added.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @ramtechjoe,

The enterprise_uninstalled.rb recipe now includes uninstalling Portal for ArcGIS WebStyles in Chef Cookbooks for ArcGIS v4.0.0.

https://github.com/Esri/arcgis-cookbook/releases/tag/v4.0.0

https://github.com/Esri/arcgis-cookbook/blob/237b0e39fca0a3b5988b997430bf7beb3637e039/cookbooks/arcgis-enterprise/recipes/enterprise_uninstalled.rb#L60-L73

Thanks,
Cameron K.
