### ISSUE TITLE
How to install the latest version (2022.0) of License Manager 

### ISSUE THREAD

**Issue by kakkarvarun** [Esri/arcgis-cookbook#306]
Hello, 
As Esri has released the latest version of license manager 2022.0 and the latest release of the cookbook (3.8.0) didn't have support for the version (2022.0) when we will expect the new release of the cookbook to have support for the latest version of the license manager.

Thanks

**Comment by cameronkroeker** [comment]
Hi @kakkarvarun,

We plan to get support added for ArcGIS License Manager 2022.0 in the next release of the cookbooks that is set to be released along side ArcGIS Enterprise 11.0, sometime end of July.

Thanks,
Cameron K.

**Comment by kakkarvarun** [comment]
Thanks for the update @cameronkroeker

**Comment by cameronkroeker** [comment]
Hi @kakkarvarun,

We have added support for ArcGIS License Manager 2022.0 in [Chef Cookbooks for ArcGIS v4.0.0](https://github.com/Esri/arcgis-cookbook/releases/tag/v4.0.0).

https://esri.github.io/arcgis-cookbook/templates/arcgis-license-manager/2022.0.html

Thanks,
Cameron K.
