### ISSUE TITLE
Error Base Deployment - ArcGIS Server

### ISSUE THREAD

**Issue by Rod-Santos** [Esri/arcgis-cookbook#312]
Hi Peoples,

I'm using `Cinc Client: 17.10.0` for deployment ArcGIS Enterprise 10.9, but receive that message in process install ArcGIS Server

`arcgis_enterprise_server[Unpack ArcGIS Server Setup] action unpack (skipped due to only_if)
  * arcgis_enterprise_server[Setup ArcGIS Server] action install

  * arcgis_enterprise_server[Configure arcgisserver service] action configure_autostart
    * windows_service[ArcGIS Server] action enable

      ================================================================================
      Error executing action `enable` on resource 'windows_service[ArcGIS Server]'
      ================================================================================

      SystemCallError
      ---------------
      O serviþo especificado nÒo existe como serviþo instalado. - OpenService:

      Resource Declaration:
      ---------------------
      # In C:/Users/rodrigo.santos/.cinc/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/server.rb

      638:     service 'ArcGIS Server' do
      639:       action :enable
      640:     end
      641:   else

      Compiled Resource:
      ------------------
      # Declared in C:/Users/rodrigo.santos/.cinc/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/server.rb:638:in `block in class_from_file'

      windows_service("ArcGIS Server") do
        action [:enable]
        default_guard_interpreter :default
        declared_type :service
        cookbook_name "arcgis-enterprise"
        recipe_name "install_server"
        service_name "ArcGIS Server"
        run_as_user "localsystem"
        supports {:restart=>nil, :reload=>nil, :status=>nil}
        run_as_password ""
      end

      System Info:
      ------------
      chef_version=17.10.0
      platform=windows
      platform_version=10.0.19043
      ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
      program_name=C:/cinc/bin/cinc-client
      executable=C:/cinc/bin/cinc-client

    ================================================================================
    Error executing action `configure_autostart` on resource 'arcgis_enterprise_server[Configure arcgisserver service]'
    ================================================================================

    SystemCallError
    ---------------
    windows_service[ArcGIS Server] (arcgis-enterprise::install_server line 638) had an error: SystemCallError: O serviþo especificado nÒo existe como serviþo instalado. - OpenService:

    Resource Declaration:
    ---------------------
    # In C:/Users/rodrigo.santos/.cinc/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/install_server.rb

     73: arcgis_enterprise_server 'Configure arcgisserver service' do
     74:   install_dir node['arcgis']['server']['install_dir']
     75:   only_if { node['arcgis']['server']['configure_autostart'] }
     76:   action :configure_autostart
     77: end
     78:

    Compiled Resource:
    ------------------
    # Declared in C:/Users/rodrigo.santos/.cinc/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/install_server.rb:73:in `from_file'

    arcgis_enterprise_server("Configure arcgisserver service") do
      action [:configure_autostart]
      default_guard_interpreter :default
      declared_type :arcgis_enterprise_server
      cookbook_name "arcgis-enterprise"
      recipe_name "install_server"
      install_dir "C:\\Program Files\\ArcGIS\\Server"
      setup_options ""
      authorization_options ""
      log_level "WARNING"
      system_properties {}
      protocol "HTTPS"
      authentication_mode "ARCGIS_TOKEN"
      authentication_tier "GIS_SERVER"
      allowed_admin_access_ips ""
      user_store_config {}
      role_store_config {}
      privileges {}
      only_if { #code block }
    end

    System Info:
    ------------
    chef_version=17.10.0
    platform=windows
    platform_version=10.0.19043
    ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
    program_name=C:/cinc/bin/cinc-client
    executable=C:/cinc/bin/cinc-client

Running handlers:
[2022-07-02T19:21:40-03:00] ERROR: Running exception handlers
Running handlers complete
[2022-07-02T19:21:40-03:00] ERROR: Exception handlers complete
Infra Phase failed. 8 resources updated in 18 minutes 50 seconds
[2022-07-02T19:21:40-03:00] FATAL: Stacktrace dumped to C:/Users/rodrigo.santos/.cinc/local-mode-cache/cache/cinc-stacktrace.out
[2022-07-02T19:21:40-03:00] FATAL: ---------------------------------------------------------------------------------------
[2022-07-02T19:21:40-03:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2022-07-02T19:21:40-03:00] FATAL: ---------------------------------------------------------------------------------------
[2022-07-02T19:21:40-03:00] FATAL: SystemCallError: arcgis_enterprise_server[Configure arcgisserver service] (arcgis-enterprise::install_server line 73) had an error: SystemCallError: windows_service[ArcGIS Server] (arcgis-enterprise::install_server line 638) had an error: SystemCallError: O serviþo especificado nÒo existe como serviþo instalado. - OpenService:

c:\cinc>`
Tips on how to overcome this problem in ArcGIS Server?

**Comment by cameronkroeker** [comment]
Hi @Rod-Santos,

I suspect the installation of ArcGIS Server did not fully complete or is partially installed because it is trying to configure the ArcGIS Server Windows Service which is failing. Likely, the setup.exe exited silently without an error.

Let's check the Windows Event Viewer application logs around the time ArcGIS Server setup.exe started/finished to see if there are any messages that could provide us with some clues.

**Also, check the following items:**
- ArcGIS Server Windows Service exists in services.msc, if it exists does it stop/start successfully?
   - If it fails to start does it give an error? 
- Check to see if there are any errors in `C:\Program Files\ArcGIS\Server\framework\etc\service\logs\service-0.log`

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker ,
> 
> Searching for the information you requested in **Event Viewer**, find this message: **Product: ArcGIS Server 10.9 -- One or more earlier ArcGIS product(s) exists on your machine. You must uninstall them before installing ArcGIS Server 10.9.** When I viewed it, I remembered that I have an **ArcMap** **installed on my machine**. When uninstalling and running the script again, the ArcGIS Server installation proceeded without errors.
> 
> Can you tell me why ArcGIS Server cannot be installed or updated with an ArcMap next to it?
> 
> Thank you for your help, it was wonderful to have your indications!

Great find @Rod-Santos! I am not sure of the exact reasons, however here it the official statement in the documentation:

https://enterprise.arcgis.com/en/system-requirements/latest/windows/arcgis-server-system-requirements.htm#ESRI_SECTION1_0FA63DB90E3B48D09E48ECB55C69AE1C

Side-by-side installation of ArcGIS Desktop, ArcReader, and ArcGIS Engine clients on the same machine with ArcGIS Server will differ depending on the version of ArcGIS Server being used:

- ArcGIS Server 10.9 cannot be installed on the same machine as any version of ArcGIS Desktop, ArcReader, and ArcGIS Engine clients.
- ArcGIS Server 10.9.1 can be installed on the same machine as ArcGIS Desktop, ArcReader, and ArcGIS Engine 10.8.2 clients only.

Thanks,
Cameron K.
