### ISSUE TITLE
ArcGIS Enterprise recipe fails at extracting the setups of ArcGIS Enterprise components

### ISSUE THREAD

**Issue by Ayushyadav19** [Esri/arcgis-cookbook#313]
Hi,

We are using the recommended version (16.16.13) of cinc-client to deploy ArcGIS Enterprise version 10.9.1 and it fails at extracting the ArcGIS enterprise components setups. We are using the _setup_archive_ key in our role files. We have encountered this error several times.

Kindly help us in resolving the issue. 

Any help will be highly appreciated.

**Comment by Ayushyadav19** [comment]
Hi @cameronkroeker,

The script fails at extracting Portal web styles setup. Please find the error log messages for the same below in the screenshot.:-
![Capture](https://user-images.githubusercontent.com/70343349/179735426-8f66f48c-182b-4dca-aef7-0bbad3c4ebfa.PNG)
 
Please find the JSON file in the attachment.
![image](https://user-images.githubusercontent.com/70343349/179735772-79eb2341-5d11-4467-b334-b03b62f6471e.png)
![image](https://user-images.githubusercontent.com/70343349/179735849-5c580c33-92fa-4119-974e-e91397231716.png)
![image](https://user-images.githubusercontent.com/70343349/179735918-ec7e6962-5ab0-4af2-9434-938d65578a77.png)
![image](https://user-images.githubusercontent.com/70343349/179735986-555cfa22-94e6-4307-a1cb-a2de0fa531b9.png)


Let me know if anything else required

**Comment by cameronkroeker** [comment]
Hi @Ayushyadav19,

Thanks for provided those additional details. Looks like the `"webstyles": { }` is embedded inside the `"portal": {}`attribute bracket. Lets move it outside into its own. For example:

```json
"arcgis":  {
   "version": "10.9.1",
   "server": {
      "setup_archive": ""
   },
   "portal": {
      "setup_archive": ""
   },
   "webstyles": {
      "setup_archive": ""
   },
   "repository": {
      "patches": ""
   }
},
"run_list": [

]
```

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @Ayushyadav19,

I just wanted to follow up, did the suggestion above help resolve the issue with ArcGIS WebStyles not extracting?

Thanks,
Cameron K.

**Comment by Ayushyadav19** [comment]
Hi @cameronkroeker,

Sorry, I missed your reply, I will try the steps that you can have recommended and will let you know soon.

Thanks
Ayush

**Comment by Ayushyadav19** [comment]
Hi @cameronkroeker,

I followed the same procedure you recommended moving webstyles outside the portal and it worked for us. 

Thanks for the help. I really appreciated it. You can go ahead and mark this case as closed

Thanks 
Ayush
