### ISSUE TITLE
License Manager question

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#32]
Does the lic mgr installer also open the required Ports on the Windows server firewall (the software firewall)?

Does it lock the port in the setup.txt file?

I looked briefly through the provider/recipe files and it didn't look like it does but Chef is new to me so I'm not even sure I'm looking in the right place.

Thanks...
If it did do those types of things, that's one reason to use the Chef installer.
I updated our LM the other night and forgot about the setup.txt part of the installed.
Finally remembered I had an install guide I'd written.

**Comment by pbobov** [comment]
Currently ArcGIS cookbook does not configure windows firewall.  It is on our TODO list. But we need to make sure that it works on all the supported windows platforms without security issues.

Meanwhile, you can make your own recipe to configure windows firewall your way. It's not technically difficult for one platform and a specific configuration. See :system action implementation  in /arcgis/providers/geoevent.rb for a hint. The list of ports is available in the server/portal/data store installation guides.
