### ISSUE TITLE
Issues installing ArcGIS Entreprise Portal

### ISSUE THREAD

**Issue by amtsongo** [Esri/arcgis-cookbook#320]
Hello all,
I installed portal for arcGIS and I am having issues accessing it: 
![image](https://user-images.githubusercontent.com/13967932/183605773-067087e3-454a-45e2-8549-a3879935b061.png)

In addition, when I open the web adaptor, as I enter my admin account, the result is : 
![image](https://user-images.githubusercontent.com/13967932/183606310-a15cad0b-0839-474f-95d0-7dde74ddc40f.png)
![image](https://user-images.githubusercontent.com/13967932/183611441-0af6bc5d-f6a1-4518-ba46-fc85f5292eab.png)

When I go the arcgis home page, I am redirected to the createadmin page:
![image](https://user-images.githubusercontent.com/13967932/183607206-91b003c4-93fe-4b6e-80a5-5245eac69590.png)
This createadmin page never succeeded.

Could someone have an idea how to solve this issue please?

**Comment by cameronkroeker** [comment]
Hi @amtsongo,

Could you provide a bit more details on the deployment? For example:

- Which version of ArcGIS Enterprise was deployed?
- Which version of ArcGIS Chef Cookbooks was used?
- Could you provide your json configuration file(s)? (Please scrub out any sensitive information such as passwords)

From the looks of it, Portal for ArcGIS is stuck in upgrade mode. Likely, the initial create site did not succeed, and portal failed to roll its self back properly. I recommend checking the portal logs to see if there is a clue as to what may have caused the first site creation to fail.

Thanks,
Cameron K.

**Comment by amtsongo** [comment]
Hi @cameronkroeker ,
Thank you so much for your rapid response.

My configuration is ArcGIS Entreprise 10.9
[deployment-config.txt](https://github.com/Esri/arcgis-cookbook/files/9293036/deployment-config.txt)
[security-config.txt](https://github.com/Esri/arcgis-cookbook/files/9293037/security-config.txt)
[Server.txt](https://github.com/Esri/arcgis-cookbook/files/9293039/Server.txt)
[site-key.txt](https://github.com/Esri/arcgis-cookbook/files/9293041/site-key.txt)
[token-config.txt](https://github.com/Esri/arcgis-cookbook/files/9293043/token-config.txt)
[webadaptor-config.txt](https://github.com/Esri/arcgis-cookbook/files/9293044/webadaptor-config.txt)

Portal Logs show as follows:
[portal-20220808.161744-2872-0.0.log](https://github.com/Esri/arcgis-cookbook/files/9293057/portal-20220808.161744-2872-0.0.log)
[portal-20220809.141002-14996-0.0.log](https://github.com/Esri/arcgis-cookbook/files/9293059/portal-20220809.141002-14996-0.0.log)

Thank you so much.

**Comment by cameronkroeker** [comment]
Hi @amtsongo,

I am a bit confused, was this deployed through automation using the latest release of [Chef Cookbooks for ArcGIS](https://esri.github.io/arcgis-cookbook/) [v4.0.0](https://github.com/Esri/arcgis-cookbook/releases/tag/v4.0.0), or manually deployed (executing each setup.exe manually and performing create site through browser, etc)?

Thanks,
Cameron K.

**Comment by amtsongo** [comment]
Thanks @cameronkroeker 
This was done by executing each setup manually.
Thank you.

**Comment by cameronkroeker** [comment]
> Thanks @cameronkroeker This was done by executing each setup manually. Thank you.

Ah thank you for clarifying. This GitHub repository is for any issues related to deploying ArcGIS Enterprise using the Chef Cookbooks for ArcGIS. I did, however, examine the artifacts you provided but did not see anything note worthy. I recommend reaching out to Esri Technical Support for further assistance as they will be better equipped to provide assistance for deployments that were manually deployed.

https://support.esri.com/en/contact-tech-support

Thanks,
Cameron K.
