### ISSUE TITLE
Portal RAM specs and renaming a Portal

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#33]
Two questions: 
1. specs I saw somewhere mention 16GB ram minimum.
I noticed that with a dev setup, at 10 or 12GB, I would show 65% RAM usage but have an awful lot of slow and buggy behavior.
Is there a formula for # of users vs. needed RAM?
What would you suggest for a good starting place or RAM.  (16, 20?)
And if we then add 100 named users?

My experience is that the RAM consumption depends mostly on number of services running, right?

2. I have decent setup running now.  But I had given it a name as a Development box (initial testing, learning setups, etc...)  I can fairly easily just kick off a new VM with the correct name and build it up from scratch, thanks to the Chef cookbook.  
But I'm curious, can I rename this dev box, reboot, modify my json file to reflect the new name and rerun Chef and will that rename the correct settings?  

Thanks

**Comment by pbobov** [comment]
I don't have a good formula for recommended RAM, except "the more - the better". For full stack (server, portal, data store) production deployments 16GB sounds like a reasonable start to me. 

RAM consumption depends on the type of services used. Hosted feature  services in portal do not consume much RAM. For other types of services typically there is a trade-of between performance and memory consumption. 

Changing machine name using chef probably would not work. The machine names are stored in many WA, DS, server, and portal configuration properties. Changing host name requires a pretty complex manual configuration.

**Comment by pkdavidson** [comment]
Thanks.... 
matches what I was thinking...  I'll rebuild the site.  Good chance to test the Chef settings.

How is it that hosted Feature Services don't consume much RAM?  Or is the RAM being consumed on the Data Store?  Or ???

**Comment by pbobov** [comment]
Hosted feature services rely on data store and they do not use dedicated instances (processes) per service. 

See http://server.arcgis.com/en/portal/latest/administer/linux/what-is-arcgis-data-store.htm

"If you plan to support publishing large numbers (thousands) of feature layers to your portal, it is strongly recommended that you use ArcGIS Data Store to create a relational data store. Hosted feature layers that rely on the relational data store require a smaller memory footprint to run, making it possible for you to publish many services with less hardware resources."

**Comment by pkdavidson** [comment]
Good info...
Thanks!
