### ISSUE TITLE
why federate always fail

### ISSUE THREAD

**Issue by pfjgeng** [Esri/arcgis-cookbook#34]
dear sir:
this code is my run log,
In the process of installation without error，but federation always fail
I hope you can help me。
Detailed as follows：
- windows_service[Portal for ArcGIS] action restart
  - restart service windows_service[Portal for ArcGIS]
  - ruby_block[Wait until Portal and Web Adaptor are available] action run
    - execute the ruby block Wait until Portal and Web Adaptor are available
  - execute[Configure Web Adaptor with Portal] action run
    - execute "C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe" /m portal /w "https://xipeng.esrichina.com/portal/webadaptor" /g "https://xipeng.esrichina.com:7443" /u "admin" /p "esrichina"
  - ruby_block[Wait until portal is available] action run
    - execute the ruby block Wait until portal is available
      Recipe: arcgis::federation
  - arcgis_portal[Federate Server] action federate_server

Running handlers:
Running handlers complete

Deprecated features used!
  config_store_connection_secret nil currently does not overwrite the value of config_store_connection_secret. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :config_store_connection_secret, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - C:\chef\cookbooks\arcgis\recipes\server.rb:55:in `block in from_file'
  web_context_url nil currently does not overwrite the value of web_context_url. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :web_context_url, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - C:\chef\cookbooks\arcgis\recipes\portal.rb:41:in`block in from_file'
  Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead. at 1 location:
    - C:\chef\cookbooks\windows\resources\feature.rb:32:in `initialize'

Chef Client finished, 54/72 resources updated in 45 minutes 28 seconds

**Comment by pbobov** [comment]
It looks like the chef run completed successfully (with a few warnings). 
Please check your portal and server web apps.
