### ISSUE TITLE
ArcGIS Enterprise 11.1 Support

### ISSUE THREAD

**Issue by Ayushyadav19** [Esri/arcgis-cookbook#344]
Hi @cameronkroeker

Is cookbook 4.0.0 supports ArcGIS Enterprise 11.1?
 
If not then when we can expect to get support for 11.1?

Thanks
Ayush

**Comment by cameronkroeker** [comment]
Hi @Ayushyadav19,

v4.0.0 supports 10.8 through 11.0:

https://esri.github.io/arcgis-cookbook/versions.html

We are aiming to release v4.1.0, that adds support for 11.1, sometime early next week.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @Ayushyadav19,

Cookbooks v4.1.0 for 11.1 has been released:
https://github.com/Esri/arcgis-cookbook/releases/tag/v4.1.0

Thanks,
Cameron K.
