### ISSUE TITLE
Permission issue ?

### ISSUE THREAD

**Issue by simongis** [Esri/arcgis-cookbook#353]
Tring to learn Chef and setting up a base ArcGIS Enteprise Deployment 11.1, on Ubuntu Server 22.04, on VirtualBox, and have snapshots to easily roll back.

Have been following the tutorial, and also added my user is in adm, sudo groups.

With files/auth downloaded into the right folders, I start the process with:

_simon@sycamore:/opt/cinc$ sudo cinc-client -z -j arcgis-enterprise-primary.json_

First error encountered is:

```
 RuntimeError
    ------------
    Cannot read from directory path '/gisdata/arcgisportal'. Please check that the location is valid and that the Portal service account has permissions to the location.

```

I assumed the script would handle creating the relevant permissions for the portal service account?  Other than adding my user into the sudoers file, is there anything else I have missed?  Sure it will be something simple.

Have attached the ouptut and the arcgis-enterprise-primary.json file with passwords removed.

At this stage I am trying with allowing the script to generate self-signed certs, once that rolls through ok, will then look to apply some certs with acme.sh and some fiddling with DNS.

sudoers file:
`%sudo   ALL=(ALL:ALL) ALL
myuser ALL=(ALL:ALL) NOPASSWD: ALL
`
[OutputFromTerminal.txt](https://github.com/Esri/arcgis-cookbook/files/11471587/OutputFromTerminal.txt)

[arcgis-enterprise-primary.txt](https://github.com/Esri/arcgis-cookbook/files/11471589/arcgis-enterprise-primary.txt)

**Comment by simongis** [comment]
Thanks @cameronkroeker for the details.

Will restore snapshot, and run the arcgis-enterprise-fileserver.json manually prior to firing off the main script.
Will report back, fingers crossed.

**Comment by simongis** [comment]
Let me know if you have any ideas if this looks like something simple @cameronkroeker 
Will be dedicating some time over the weekend to troubleshoot further.

**Comment by cameronkroeker** [comment]
Hi @simongis,

ArcGIS Cookbooks v4.1.0 use [NFS cookbook 2.6.4](https://supermarket.chef.io/cookbooks/nfs/versions/2.6.4) for the fileserver recipe in [arcgis-enterprise-fileserver.json](https://github.com/Esri/arcgis-cookbook/blob/b6eba15c34cd5bbb192df830f395b3d5aea0e735/templates/arcgis-enterprise-base/11.1/linux/arcgis-enterprise-fileserver.json#L24).

https://github.com/Esri/arcgis-cookbook/blob/b6eba15c34cd5bbb192df830f395b3d5aea0e735/cookbooks/arcgis-enterprise/metadata.rb#L16

I've found that NFS cookbook 2.6 and 3.0 fail on Ubuntu 22.04 (with the error you described above), but works on Ubuntu 18.04 and 20.04. I suspect it is similar to the issue described here:

https://github.com/sous-chefs/nfs/issues/118

I've tested [NFS cookbook 5.0](https://supermarket.chef.io/cookbooks/nfs/versions/5.0.0) on Ubuntu 22.04 and it works, however it requires `chef_version '>= 15.3'`. This means if we were to upgrade the NFS cookbook from 2.6 to 5.0 in our ArcGIS cookbooks we would have to drop support for Chef 14.

https://github.com/Esri/arcgis-cookbook/blob/b6eba15c34cd5bbb192df830f395b3d5aea0e735/cookbooks/arcgis-enterprise/metadata.rb#L8

We've started a discussion here about the possibility of dropping support for Chef 14 in the future: https://github.com/Esri/arcgis-cookbook/discussions/352

Here are the platforms we've tested/verified that work with the arcgis-enterprise-base 11.1 template:
https://esri.github.io/arcgis-cookbook/templates/arcgis-enterprise-base/11.1.html#supported-platforms

Thanks,
Cameron K.

**Comment by simongis** [comment]
Thanks Cameron.  I did spot 22.04 was not on the list before starting but took a gamble, a bad one. 

Based upon what’s in the recipes for this step, I think ill start from scratch with a supported OS.  

Thanks for your help.  On the plus side, learnt a few things from this mistake.
