### ISSUE TITLE
Timeout with webadaptor

### ISSUE THREAD

**Issue by simongis** [Esri/arcgis-cookbook#354]
Learning to deploy a base Enterprise 11.1 environment onto a single VM running Ubuntu 20.04 using Chef, and hitting an issue with setting up the portal web adaptor step. 

**Environment:**
- ArcGIS Enterprise 11.1 - Base Stack on single machine
- Virtualbox for a homelab, making heavy use of snapshots to learn from mistakes
- Fresh instance of Ubuntu 20.04 - original hostname wombat
- Using a DNS Server, have assigned the machine FQDN:  wombat.simongis.xyx 
- hostname command = wombat.simongis.xyz
- dnsdomainname command = simongis.xyz
- Have not changed any receipes, just the arcgis-enterprise-primary.json file

Issue:
Everything in arcgis-enterprise-primary.json appears to run fine, until portal_wa recipe.

```
WARN: Util.wait_until_url_available timed out for https://wombat.simongis.xyz/portal/webadaptor after 1001.23 seconds. 
ERROR: Failed to configure Web Adaptor with Portal for ArcGIS. Expected process to exit with [0], but received '1'.
```

- Can access and login to the portal via https://wombat.simongis.xyz:7443/arcgis/home/
- Can ping wombat.simongis.xyz from another machine on the LAN
- ERR_CONNECTION_REFUSED on https://wombat.simongis.xyz/portal/home
- ERR_CONNECTION_REFUSED on https://wombat.simongis.xyz/portal/webadaptor

**Can you provide any pointers on where I might be going wrong here?**  

End goal is to have a repeatable way of quickly deploying a fresh 11.1 Enterprise Environment on Linux for self-development, and share the steps to get there via a blog post (and things I learnt along the way).  Eventua

Let me know if you prefer this type of issue raised on Esri Community

[running_deployment_template.txt](https://github.com/Esri/arcgis-cookbook/files/11524112/running_deployment_template.txt)

[arcgis-enterprise-primary.txt](https://github.com/Esri/arcgis-cookbook/files/11524111/arcgis-enterprise-primary.txt)

[portal service.log](https://github.com/Esri/arcgis-cookbook/files/11524113/service.log)

Hosts file on Ubuntu
![image](https://github.com/Esri/arcgis-cookbook/assets/2769383/dc95f480-cd94-4b20-aff4-c17b88637299)

![image](https://github.com/Esri/arcgis-cookbook/assets/2769383/86730b70-fb28-4159-aa7a-ae740e6a1687)

End goal is to have a repeatable way of quickly deploying a fresh 11.1 Enterprise Environment on Linux for self-development, and share the steps to get there via a blog post (and things I learnt along the way).  Eventually get it working with a reverse proxy and fetching LetsEncrypt certs.  That can come later.

**Comment by cameronkroeker** [comment]
Hi @simongis,

I wonder if the issue is related to not having a value specified for the tomcat attribute `"keystore_type": "",`. In the chef run logs I noticed:

```
 +    <Connector protocol="org.apache.coyote.http11.Http11Nio2Protocol"
    +               port="8443" maxThreads="200"
    +               scheme="https" secure="true" SSLEnabled="true"
    +               sslEnabledProtocols="TLSv1.3,TLSv1.2"
    +               keystoreFile="/opt/tomcat_arcgis_9.0.48/certificates/wombat.simon                                                                                        gis.xyz.pfx"
    +               keystorePass="wombat.simongis.xyz"
    +               keystoreType=""
    +               clientAuth="false" sslProtocol="TLS" />
```

Perhaps this is causing the tomcat SSL listner to not start properly. Let's check the following:
- See if there are any clues in the tomcat logs catalina.out located in `/opt/tomcat_arcgis/logs`
- Check to see if the following endpoints return a 200 status code (run from the node where the web adaptor is installed on):

```
curl http://wombat.simongis.xyz:8080/portal/webadaptor -v
```
```
curl http://wombat.simongis.xyz/portal/webadaptor -v
```
```
curl https://wombat.simongis.xyz:8443/portal/webadaptor --insecure -v
```
```
curl https://wombat.simongis.xyz/portal/webadaptor --insecure -v
```

Thanks,
Cameron K.

**Comment by simongis** [comment]
Removing the lines worked.  All services appear to be accessible and functioning as expected - thanks loads @cameronkroeker 
![image](https://github.com/Esri/arcgis-cookbook/assets/2769383/16555d79-4117-4be7-af21-031b6a3a819e)

Will now look at working out how to get some LetsEncrypt certs involved using something like Nginx Proxy Manager or  go-acme - won't be bothering you about that side of things.  Thanks!
