### ISSUE TITLE
Support for ArcGIS Object Store?

### ISSUE THREAD

**Issue by simongis** [Esri/arcgis-cookbook#355]
Is there support for the ArcGIS Data Store - Object Store type in deploying via the ArcGIS Enterprise cookbook?

I note that the current [object_store ](https://esri.github.io/arcgis-cookbook/cookbooks/arcgis-enterprise/4.1.0.html#:~:text=node%5B%27arcgis%27%5D%5B%27portal%27%5D%5B%27object_store%27%5D%20%3D%20Portal%20for%20ArcGIS%20content%20store%20container)in the Enterprise cookbook, is in reference to the Portal Content store, which might get confusing in the future when more uptake in the ArcGIS Data Store - Object Store, starts to happen.

**Comment by cameronkroeker** [comment]
Hi @simongis,

Support for the ArcGIS Data Store - Object Store type has not been added to the cookbooks yet.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Support for the ArcGIS Data Store - Object Store type has been added:

**Template:**
- ://github.com/Esri/arcgis-cookbook/blob/main/templates/arcgis-datastore/11.2/windows/arcgis-datastore-object.json
- https://github.com/Esri/arcgis-cookbook/tree/main/templates/arcgis-datastore/11.2#object-data-store-in-cluster-mode

**Cookbooks:**
- https://github.com/Esri/arcgis-cookbook/releases/tag/v4.2.0

Thanks,
Cameron K.
