### ISSUE TITLE
Changing the licence file type

### ISSUE THREAD

**Issue by cadams84** [Esri/arcgis-cookbook#36]
I am trying to specify *.ecp licence files for Portal and ArcGIS Server when running the 'webgis-windows' recipe. I get an error 'invalid char in json text .ecp'. Is there a way to specify ecp files instead of provisioning files?

**Comment by pbobov** [comment]
It looks like the JSON file is not formatted correctly. Please make sure that all the JSON special characters are escaped correctly.

Otherwise, *.ecp authorization files should work.

**Comment by cadams84** [comment]
The JSON was incorrectly formatted. I have successfully authorized with .ecp. Thanks.
