### ISSUE TITLE
Attempt to configure data store failed. 'graph' data store is not installed in the current configuration.

### ISSUE THREAD

**Issue by sgavathe** [Esri/arcgis-cookbook#367]
I get this error when I run configuredatastore with graph as option. I am using Chef cookkbook for ArcGIS 11.0. 

`
/opt/esri/arcgis/datastore/tools/configuredatastore.sh https://site user pwd  /opt/esri/arcgis/datastore --stores relational,graph

Configuring data store(s). Initial configuration may take a few minutes. When configuring an upgraded data store, this process may take several hours depending on the size of your data. Please wait...

The option "--mode" does not apply to the configuration of relational or spatiotemporal big data stores.

Configuring data store....

Error encountered: Machine 'https://localhost:2443/arcgis/datastoreadmin' returned an error. 'Attempt to configure data store failed.
Caused by: 'graph' data store is not installed in the current configuration. On Windows use the Modify option to select additional features from Add Remove Programs. On Linux, modification of installed data store types is not supported. Consider installing on a separate machine. Consult documentation for more information on specific usage
`

This is my data_store
```
    "data_store": {
      "install_dir": "/opt/esri",
      "data_dir": "/opt/esri/gisdata/arcgisdatastore",
      "configure_autostart": true,
      "preferredidentifier": "hostname", 
      "install_system_requirements": true,
      "setup_options": "-f Graph", 
      "types": "relational,graph",
      "relational": {
          "backup_type": "fs",
          "backup_location": "/net/FILESERVER/gisdata/arcgisbackup/relational"
      },
      "graph": {
          "backup_type": "fs",
          "backup_location": "/net/FILESERVER/gisdata/arcgisbackup/graph"
     }
    },
 ```

**Comment by cameronkroeker** [comment]
@sgavathe can you check to see which data store types are installed:

```shell
$ cat /opt/esri/arcgis/datastore/framework/etc/installed_datastores.properties
```
