### ISSUE TITLE
Setting the root certificate

### ISSUE THREAD

**Issue by cadams84** [Esri/arcgis-cookbook#37]
Is there a way to import a root/intermediate certificate? The keystore_file seems to be the Server certificate; can a root be imported as well?

**Comment by pbobov** [comment]
No. So far the cookbook does not support importing root certificates.

**Comment by pkdavidson** [comment]
cadams:  I've always imported a root cert on the server before firing off the Chef process.
Doing that seems to have cleaned up some certificate errors I've had in the past with the self-signed cert getting in the way.
