### ISSUE TITLE
Will Video Server be a chef script for 11.2?

### ISSUE THREAD

**Issue by simongis** [Esri/arcgis-cookbook#372]
Hoping to incorporate Video Server in our deployments where we currently use Chef.

Any ETA on when this might appear?

**Comment by cameronkroeker** [comment]
ArcGIS Video Server 11.3 has been added to cookbooks v5.0.0:

https://github.com/Esri/arcgis-cookbook/releases/tag/v5.0.0

https://esri.github.io/arcgis-cookbook/templates/arcgis-video-server/11.3.html
