### ISSUE TITLE
RAM allocation in VM-Sphere

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#39]
Hi Pavel:
I believe you have suggested 16GB of RAM minimum for an all in one box?
Do you know if this applies to machines running in a VM environment?

We have a Development Portal running with the basic 5 user license. 
We have this setup in a VMware Sphere environment with 4 cores and 12GB of RAM.
We recently have seen some performance issues when developing maps.
I asked our systems guys to bump us to 16GB.
But they said that when they looked at our RAM usage, over the past month, we're at only 5% of the 12GB.  Of course, this is an average usage over time.  
Based on just Windows Task Manager, at 12GB, we're running at about 60% consumption when we're in there doing development work on larger maps.

What the systems folks just told me though is that in a VM environment, they've been told that too much RAM can slow things down.  That the VM guys say that unlike hard boxes, you want to have your RAM utilization up real high.  We have seen on a virtualized IBM Maximo server that performance increased when we dropped the allocated RAM.

Do you have any experience or guidelines for defining how much RAM to allocate in a VM setting?
Thanks

**Comment by pbobov** [comment]
These are surprising observations for me. 

I forwarded your question to an ArcGIS Server QA engineer.  Here is his answer:

"I am unaware of this phenomena of reduced performance correlating with an increasing percentage of available RAM.  I have not tested this kind of scenario.  Straight up it doesn’t make sense, but apparently you can configure how memory is allocated between processing cores in a VM environment and it has dramatic performance implications: http://searchservervirtualization.techtarget.com/feature/Improve-VM-performance-with-server-memory-configuration   This would apply to any software stack and especially ours where we have lots of processes consuming lots of RAM."

**Comment by pkdavidson** [comment]
Agreed, very counter intuitive.
We've heard rumors of a tool that helps determine the sweet spot for this sort of thing that we're looking into.  

I do know that with our Dev Portal, at 10GB, we were running at about 60+% RAM utilization and having some issues.  Bumped the RAM to 12GB and the issues went away and RAM dropped to about 50%.  Had a similar issue on a virtualized ArcGIS Server.  

We were seeing some issues this morning, again at about 61% consumption and that's what started this conversation with Systems.   They aren't 100% sold on the idea either but wanted to discuss it when I asked for bump in RAM.

Apparently one can do a lot of fine tuning with cores and processes and such.

I guess the bottom line is that it's a brave new VM world out there and each environment is unique based on a lot of factors.  (backbone, drives, OS's, etc... and that's before the software stack comes into it!)

I have a feeling it's going to be somewhat of a trial and error thing.

Thanks for the info.  That's an interesting read.
