### ISSUE TITLE
HA json question

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#40]
In the HA json files there is a domain_name entry for server and portal.
I guess this needs to be the FQDN of the server and portal as opposed to just the domain part of the name?

    "server":{
      "domain_name":"myPortal.mydomain.com",

and not:
    "server":{
      "domain_name":"mydomain.com",

In the all on one box environment, both server and portal would have the same domain name, right?
    "server":{
      "domain_name":"myPortal.mydomain.com",
and
    "portal":{
      "domain_name":"myPortal.mydomain.com",

Some what of a head slapping moment....

**Comment by pbobov** [comment]
Yes. domain_name must be FQDN of the server machine (or the load balancer in HA configuration). 

Yes. In the all on one box environment, both server and portal would have the same domain name.

If domain_name attribute is not set, Chef tries to set "domain_name" to FQDN of the machine. But sometimes (if primary Dns is not set) it does not work and Chef ends up using just hostname and fails trying to register Web Adaptor with portal.

**Comment by pkdavidson** [comment]
Thanks... makes sense after I saw the error.
