### ISSUE TITLE
authorization gets stuck if authorization file does not exist

### ISSUE THREAD

**Issue by dannyim** [Esri/arcgis-cookbook#47]
platform: Windows server 2012 R2
software: Arcgis 10.4 server

If I set the authorization file to a path that does not exist, the provisioning process gets stuck on the authorize action (I had to terminate the process after waiting for over an hour).  I logged into the machine and ran the authorization command manually and found that, even with the /S flag, the authorization dialog gets displayed, so I assume that the authorization software is stuck waiting for user input.  

Can the recipe check if the authorization file exists before proceeding?

**Comment by pbobov** [comment]
Yes. That definitely could and should be done.

**Comment by cameronkroeker** [comment]
A fix for this was implemented in v3.6.0:
https://github.com/Esri/arcgis-cookbook/blob/ae704a00cef52d34057569e36214f8669d539266/cookbooks/arcgis-enterprise/providers/server.rb#L180-L183
