### ISSUE TITLE
Domain Name Attribute not in JSON? 

### ISSUE THREAD

**Issue by micahwilli** [Esri/arcgis-cookbook#49]
I downloaded the cookbook today and it seems there is no domain_name attribute in the webgis-windows.json file. I'm assuming i can just copy/paste that line from the webgis-windows-ha-primary.json file?

**Comment by cameronkroeker** [comment]
The role json files are samples and may not contain all available attributes. All available attributes can be found here:

https://github.com/Esri/arcgis-cookbook/tree/master/cookbooks/arcgis-enterprise

`node['arcgis']['server']['domain_name'] = ArcGIS Server domain name. By default, <node FQDN> is used.`

`node['arcgis']['portal']['domain_name'] = Portal for ArcGIS domain name. By default, <node FQDN> is used.`
