### ISSUE TITLE
Should the >>kitchen converge or >>vagrant up "just work"?

### ISSUE THREAD

**Issue by tjsoftworks** [Esri/arcgis-cookbook#5]
FIrst, it is awesome that this cookbook has appeared in the wild. Thank you.

I was so excited, I pulled it and tried to kitchen create, kitchen converge immediately without success but I was being lazy.
Next with the direct Vagrant up and that didn't go for me directly.

I notice the support platforms are Redhat and Window.... but the .kitchen.yml and Vagrant files don't list either of those. 

Should I be having any success or is this a current limitation?

**Comment by pbobov** [comment]
Thank you for submitting the issue! 

Test Kitchen is not ready yet for the cookbook. kitchen.yaml is just a dummy created by berkshelf. I tried approaching that a few month ago, but run into some troubles configuring Test Kitchen and Vagrant with Windows Server images. I'll get back to it soon. (I heard that windows support in Vagrant was improved in the recent releases...)

**Comment by tjsoftworks** [comment]
Well, let’s see if we can work on this….. I’ll see if we can start the process down a path to working again. I also noticed that Ubuntu 14.0.4 was removed. It there an blocker there or can I add it back in and work to make that a success too?

Terry

**Comment by pbobov** [comment]
The cookbook supports Ubuntu. But ArcGIS itself is not officially supported on Ubuntu. It is supported on Ubuntu only on Amazon AWS with AMIs provided by ESRI. So we removed Ubuntu support from the cookbook to avoid confusion.

**Comment by pbobov** [comment]
I added support for Ubuntu 14.04 back to readme.md with a comment "Ubuntu 14.04 (when deploying ArcGIS for Server on Amazon Web Services)".

**Comment by tjsoftworks** [comment]
Thank you for that clarification. Have been working with the ERSI Ubuntu 14.0.4 on AWS so I knew it was possible and in fact, I'm looking to use your cookbooks to extend the automation of our AWS resources.

**Comment by pbobov** [comment]
On AWS we have a CloudFormation template that installs/configures ArcGIS 10.3.1 Server/Portal/DataStore using this cookbook. The template will be publicly available in a few days. I'll let you know when it is available.

**Comment by tjsoftworks** [comment]
Question about the authorization_tool installer. Where is the URL for that resource?

**Comment by pbobov** [comment]
The default location of server authorization tool is '/arcgis/server/tools/authorizeSoftware'. This tool is installed by the server setup. So first you need to :install server and then :authorize server. The server setup and the authorization files locations are defined by node['server']['setup'] and node['server']['authorization_file'] attributes respectively.  The files must be available to the chef's user account. Currently URLs are not supported.

**Comment by tjsoftworks** [comment]
Sorry .... my question is:

**Comment by pbobov** [comment]
Here is the link to [CloudFormation templates to set up ArcGIS for Server on Amazon Web Services](http://esriarcgisserverrepository.s3.amazonaws.com/10.3.1/Index.htm). The Web GIS CF templates use the chef-solo and arcgis cookbook internally.
