### ISSUE TITLE
ArcGIS Desktop single use licence

### ISSUE THREAD

**Issue by cadams84** [Esri/arcgis-cookbook#51]
I am trying to install ArcGIS Desktop and authorize it with a Standard/Editor SU licence. Desktop installs but is not authorized. Is this supported? 

{
  "arcgis":{
    "version":"10.4",
    "desktop":{
      "setup":"C:\\esri\\Media\\ArcGIS_Desktop_104_149411.exe",
      "authorization_file":"C:\\esri\\_SingleUse_436513.prvc",
      "software_class":"Editor",
      "seat_preference":"Fixed",
      "desktop_config":true
    }
  },
  "run_list":[
    "recipe[arcgis::desktop]"
  ]
}

**Comment by pbobov** [comment]
No. Currently ArcGIS Desktop software authorization is not supported by ArcGIS Chef Cookbook.

@jonathanan @JoAlvarez

**Comment by cadams84** [comment]
Thank you for the quick response.

**Comment by rafteryd** [comment]
Hi, is this still unsupported?

**Comment by pbobov** [comment]
Software authorization for ArcGIS Desktop is only supported by the cookbook when "seat_preference" attribute value is "Fixed".

See https://github.com/Esri/arcgis-cookbook/wiki/arcgis%E2%80%90desktop-Cookbook-Recipes

**Comment by rafteryd** [comment]
Hi Pavel,

Thanks for getting back to me so quickly. I have the following but it is still trying to use a concurrent licence in ArcGIS Administrator:

![image](https://cloud.githubusercontent.com/assets/21330930/24426775/a6728b40-1400-11e7-97f4-576d787c3d6c.png)

![image](https://cloud.githubusercontent.com/assets/21330930/24426809/c76ad2f8-1400-11e7-94da-ddb9f5afe16d.png)

I have probably missed something small!

Thanks,

D

**Comment by pbobov** [comment]
@rafteryd Or maybe it's just a bug in the cookbook... We did not update arcgis-desktop cookbook for quite a while. If you can figure out how to authorize Desktop they way you need from command line, we could try and add support for this configuration to the next release of ArcGIS Chef Cookbooks.

**Comment by cadams84** [comment]
As Pavel says, try a silent command. I have a batch script that runs the Desktop install using Chef. After this has completed, I have a silent install command that licences Desktop. This process also changes the licensing level in the administrator to whatever has been licenced from the prvc

**Comment by ArpitaChakraborty** [comment]
@pbobov 
Is there a way we can configure single licence usage instead of concurrent one?

**Comment by pbobov** [comment]
@ArpitaChakraborty Configuring concurrent use license in ArcGIS Desktop is not yet supported by ArcGIS Chef Cookbooks.

**Comment by pbobov** [comment]
@ArpitaChakraborty I just realized that my previous answer was misleading. 

arcgis-desktop cookbook currently does not support software authorization of ArcGIS desktop using concurrent license, but it does support configuring ArcGIS Desktop to use concurrent license and a specific License Manager host.

To use concurrent license you need to: 
- manually authorize the ArcGIS Desktop machine with License Manager,
- set arcgis/desktop/esri_license_host attribute in the Chef JSON file to the host name of the License Manager, 
- arcgis/desktop/seat_preference attribute to 'Float'.

CC: @cameronkroeker
