### ISSUE TITLE
Import certificate into secondary Portal for ArcGIS

### ISSUE THREAD

**Issue by cadams84** [Esri/arcgis-cookbook#62]
The primary Portal for ArcGIS recipe (portal) has the following code to set the certificate in the Portal keystore. The secondary Portal for ArcGIS recipe (portal_standby) does not. Is a certificate not required because the Portals will be connected to using a load balancer and it is at this level that the certificate matters?

arcgis_server_portal 'Configure HTTPS' do
  portal_url node['arcgis']['portal']['url']
  username node['arcgis']['portal']['admin_username']
  password node['arcgis']['portal']['admin_password']
  keystore_file node['arcgis']['portal']['keystore_file']
  keystore_password node['arcgis']['portal']['keystore_password']
  cert_alias node['arcgis']['portal']['cert_alias']
  not_if { node['arcgis']['portal']['keystore_file'].empty? }
  action :configure_https
end

**Comment by pbobov** [comment]
The secondary portal machine takes the portal HTTPS configuration settings from the primary one.

(It's a bit different in case of ArcGIS Server, where HTTPS settings are configured per machine.)

**Comment by cadams84** [comment]
Hi @pbobov I am still seeing this issue. The problem is that the machine certificate is not imported into the Portal keystore with my JSON on the secondary Portal. This means that the secondary portal still have the out-of-the-box self-signed certificate which is not trusted. At 10.5.1 I am finding that a trusted certificate is required for the Web Adaptor to successfully register with the Portal so this also fails as the domain certificate has not been imported. 

To get around the issue, I have copied the following section to 'portal_standby.rb' from the primary portal recipe as it is not present. This solves the problem as my secondary Portal now has a trusted domain certificate and the web adaptor gets configured successfully. Please can this be added to the core recipe?

arcgis_enterprise_portal 'Configure HTTPS' do
  portal_url node['arcgis']['portal']['url']
  username node['arcgis']['portal']['admin_username']
  password node['arcgis']['portal']['admin_password']
  keystore_file node['arcgis']['portal']['keystore_file']
  keystore_password node['arcgis']['portal']['keystore_password']
  cert_alias node['arcgis']['portal']['cert_alias']
  not_if { node['arcgis']['portal']['keystore_file'].empty? }
  action :configure_https
end

**Comment by pbobov** [comment]
@cadams84 Unlike ArcGIS Server where SSL certificates are imported to individual machines, in case of Portal for ArcGIS the SSL certificate should be imported once on the primary machine and reused automatically by the secondary machine. I'm not sure why that does not work.

**Comment by cameronkroeker** [comment]
This has been added. Please try with v3.5.0:

https://github.com/Esri/arcgis-cookbook/blob/50cbc0f53382dd7f44311018e02d64e09624174b/cookbooks/arcgis-enterprise/recipes/portal_standby.rb#L69
