### ISSUE TITLE
RE: No such cookbook: arcgis-enterprise

### ISSUE THREAD

**Issue by hughwei** [Esri/arcgis-cookbook#68]
I have the following error during the installation:

C:\chef>chef-solo -j c:\chef\roles\webgis-windows.json
Starting Chef Client, version 12.19.36
[2017-03-14T14:26:14-04:00] INFO: *** Chef 12.19.36 ***
[2017-03-14T14:26:14-04:00] INFO: Platform: x64-mingw32
[2017-03-14T14:26:14-04:00] INFO: Chef-client pid: 5460
[2017-03-14T14:26:20-04:00] INFO: Setting the run_list to ["recipe[arcgis-enterp
rise::system]", "recipe[esri-iis]", "recipe[arcgis-enterprise::server]", "recipe
[arcgis-enterprise::server_wa]", "recipe[arcgis-enterprise::datastore]", "recipe
[arcgis-enterprise::portal]", "recipe[arcgis-enterprise::portal_wa]", "recipe[ar
cgis-enterprise::federation]"] from CLI options
[2017-03-14T14:26:20-04:00] INFO: Run List is [recipe[arcgis-enterprise::system]
, recipe[esri-iis], recipe[arcgis-enterprise::server], recipe[arcgis-enterprise:
:server_wa], recipe[arcgis-enterprise::datastore], recipe[arcgis-enterprise::por
tal], recipe[arcgis-enterprise::portal_wa], recipe[arcgis-enterprise::federation
]]
[2017-03-14T14:26:20-04:00] INFO: Run List expands to [arcgis-enterprise::system
, esri-iis, arcgis-enterprise::server, arcgis-enterprise::server_wa, arcgis-ente
rprise::datastore, arcgis-enterprise::portal, arcgis-enterprise::portal_wa, arcg
is-enterprise::federation]
[2017-03-14T14:26:20-04:00] INFO: Starting Chef Run for server1.statcan.ca
[2017-03-14T14:26:20-04:00] INFO: Running start handlers
[2017-03-14T14:26:20-04:00] INFO: Start handlers complete.
[2017-03-14T14:26:20-04:00] INFO: HTTP Request Returned 404 Not Found: Object no
t found:
resolving cookbooks for run list: ["arcgis-enterprise::system", "esri-iis", "arc
gis-enterprise::server", "arcgis-enterprise::server_wa", "arcgis-enterprise::dat
astore", "arcgis-enterprise::portal", "arcgis-enterprise::portal_wa", "arcgis-en
terprise::federation"]
[2017-03-14T14:26:20-04:00] INFO: HTTP Request Returned 412 Precondition Failed:
 No such cookbook: arcgis-enterprise

================================================================================

Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: arcgis-enterprise

Expanded Run List:
------------------
* arcgis-enterprise::system
* esri-iis
* arcgis-enterprise::server
* arcgis-enterprise::server_wa
* arcgis-enterprise::datastore
* arcgis-enterprise::portal
* arcgis-enterprise::portal_wa
* arcgis-enterprise::federation

Platform:
---------
x64-mingw32

Running handlers:
[2017-03-14T14:26:20-04:00] ERROR: Running exception handlers
Running handlers complete
[2017-03-14T14:26:20-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 07 seconds
[2017-03-14T14:26:21-04:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache
/cache/chef-stacktrace.out
[2017-03-14T14:26:21-04:00] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2017-03-14T14:26:21-04:00] FATAL: Net::HTTPServerException: 412 "Precondition F
ailed"

**Comment by pbobov** [comment]
Please check if there is arcgis-enterprise folder in folder C:\chef\cookbooks on the machine.

**Comment by hughwei** [comment]
Thanks.  
Then another error showing up like follows:

===========
ecipe: arcgis-enterprise::system
  * chef_gem[multipart-post] action install[2017-03-14T16:28:56-04:00] INFO: Pro
cessing chef_gem[multipart-post] action install (arcgis-enterprise::system line
20)
[2017-03-14T16:28:58-04:00] WARN: failed to find gem multipart-post (>= 0) from
[https://rubygems.org/]
[2017-03-14T16:29:00-04:00] ERROR: chef_gem[multipart-post] (arcgis-enterprise::
system line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected pro
cess to exit with [0], but received '2'
---- Begin output of C:/opscode/chef/embedded/bin/gem install "multipart-post" -
q --no-rdoc --no-ri  ----
STDOUT:
STDERR: ERROR:  Could not find a valid gem 'multipart-post' (>= 0), here is why:

          Unable to download data from https://rubygems.org/ - no such name (htt
ps://rubygems.org/specs.4.8.gz)
---- End output of C:/opscode/chef/embedded/bin/gem install "multipart-post" -q
--no-rdoc --no-ri  ----
Ran C:/opscode/chef/embedded/bin/gem install "multipart-post" -q --no-rdoc --no-
ri  returned 2; ignore_failure is set, continuing


    ============================================================================
====
    Error executing action `install` on resource 'chef_gem[multipart-post]'
    ============================================================================
====

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '2'
    ---- Begin output of C:/opscode/chef/embedded/bin/gem install "multipart-pos
t" -q --no-rdoc --no-ri  ----
    STDOUT:
    STDERR: ERROR:  Could not find a valid gem 'multipart-post' (>= 0), here is
why:
              Unable to download data from https://rubygems.org/ - no such name
(https://rubygems.org/specs.4.8.gz)
    ---- End output of C:/opscode/chef/embedded/bin/gem install "multipart-post"
 -q --no-rdoc --no-ri  ----
    Ran C:/opscode/chef/embedded/bin/gem install "multipart-post" -q --no-rdoc -
-no-ri  returned 2

**Comment by hughwei** [comment]
BTW, my server is in disconnected environment.

**Comment by pbobov** [comment]
Try to install multipart-post gem before running chef.

**Comment by mschoelen** [comment]
@pbobov Can you outline the steps for that? I think the command is `gem install multipart-post`, but I'm not entirely sure where to run it.
