### ISSUE TITLE
Chef cookbook pre-requisites

### ISSUE THREAD

**Issue by mgg-eagle** [Esri/arcgis-cookbook#69]
Can you please list all the prereq cookbooks that have to be installed beforethis will work.

**Comment by pbobov** [comment]
All the required cookbooks are included here https://github.com/Esri/arcgis-cookbook/releases/download/v3.0.0/arcgis-3.0.0-cookbooks.zip.

Another option is using Berkshelf (http://berkshelf.com/v2.0/) to resolve the cookbook dependencies.

**Comment by mgg-eagle** [comment]
Thanks for that link.  Can I suggest the instructions reference it so it is clear to the users that they need to download and install these cookbooks

**Comment by pbobov** [comment]
And all the docs are here https://github.com/Esri/arcgis-cookbook/wiki.

**Comment by mgg-eagle** [comment]
ok thanks for your help
