### ISSUE TITLE
class or module required

### ISSUE THREAD

**Issue by afoxi911** [Esri/arcgis-cookbook#70]
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: arcgis-enterprise::system
  * chef_gem[multipart-post] action install[2017-03-17T08:44:05+08:00] INFO: Pro
cessing chef_gem[multipart-post] action install (arcgis-enterprise::system line
20)
 (up to date)

  ==============================================================================
==
  Recipe Compile Error in c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterp
rise/recipes/portal.rb
  ==============================================================================
==

I ran into the below after installing the latest 3.0 cookbook and dependencies. Any ideas  

TypeError
  ---------
  class or module required

  Platform:
  ---------
  x64-mingw32

  Running handlers:
[2017-03-17T08:44:06+08:00] ERROR: Running exception handlers
  Running handlers complete
[2017-03-17T08:44:06+08:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 37 seconds
[2017-03-17T08:44:06+08:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache
/cache/chef-stacktrace.out
[2017-03-17T08:44:06+08:00] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2017-03-17T08:44:06+08:00] FATAL: TypeError: class or module required

**Comment by pbobov** [comment]
What is your chef-client version?
Is there anything in C:/chef/local-mode-cache/cache/chef-stacktrace.out?

**Comment by afoxi911** [comment]
client version is 12.19.36

stacktrace content below

Generated at 2017-03-17 08:44:06 +0800
TypeError: class or module required
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:187:in `kind_of?'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:187:in `block in _pv_kind_of'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:186:in `each'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:186:in `_pv_kind_of'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:106:in `block (2 levels) in validate'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:103:in `each'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:103:in `block in validate'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:93:in `each'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/params_validate.rb:93:in `validate'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/property.rb:481:in `validate'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/property.rb:702:in `coerce_and_validate'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/property.rb:681:in `input_to_stored_value'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/property.rb:403:in `set'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/property.rb:302:in `call'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/property.rb:533:in `object_store'
c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/portal.rb:126:in `block in from_file'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_builder.rb:76:in `instance_eval'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_builder.rb:76:in `build'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/dsl/declare_resource.rb:291:in `build_resource'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/dsl/declare_resource.rb:248:in `declare_resource'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/dsl/resources.rb:39:in `arcgis_enterprise_portal'
c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/portal.rb:110:in `from_file'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/run_context.rb:187:in `load'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:511:in `setup_run_context'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:281:in `run'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:59:in `run'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/solo.rb:226:in `run'
c:/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/bin/chef-solo:25:in `<top (required)>'
c:/chef/bin/chef-solo:68:in `load'
c:/chef/bin/chef-solo:68:in `<main>'

**Comment by pbobov** [comment]
Please try it with Chef Client 12.17.44. It looks like the cookbook has some compatibility issues with the new Chef Client.

**Comment by afoxi911** [comment]
yep. that works better. 

Can you run the server installs in silent mode, my current config is still asking for alot of user input to install paths etc
