### ISSUE TITLE
10.5 Setup Runs on the Screen - Is this the correct behavior?

### ISSUE THREAD

**Issue by jvrck** [Esri/arcgis-cookbook#72]
Hi, 

Firstly, thanks for these cookbooks - they will be fantastic for us when we get them working as intended.

I am trying to install ArcGIS 10.5 on a Windows 2012R2 VM. 

I have modified the run list to look like this as I do not need portal, web adapter or data store.

"run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[esri-iis]",
    "recipe[arcgis-enterprise::server]"
 ]

Should the setup run on the screen when I issue the command "chef-solo -j C:\chef\roles\webgis-windows.json" ? After I run this, the setup comes up on the screen as if I was doing an install on the server. I am unsure if this is the correct behavior.

Kind Regards, 
Jim

**Comment by pbobov** [comment]
This is probably the same issue as https://github.com/Esri/arcgis-cookbook/issues/71.

**Comment by jvrck** [comment]
Thanks. 

Just an update with this.

The setup executable that I was using in my json was  the archive. So I executed the exe that extracts the setup file and then referenced the setup.exe that was extracted in it and it worked. 

Kind Regards, 
Jim
