### ISSUE TITLE
migration failed

### ISSUE THREAD

**Issue by afoxi911** [Esri/arcgis-cookbook#75]
got the following error setting up the portal site.

any ideas

Generated at 2017-03-27 10:58:17 +0800
RuntimeError: arcgis_enterprise_portal[Create Portal Site] (arcgis-enterprise::portal line 110) had an error: RuntimeError: Migration failed. null
c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/libraries/portal_admin_client.rb:502:in `validate_response'
c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/libraries/portal_admin_client.rb:91:in `create_site'
c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/providers/portal.rb:322:in `block in class_from_file'
(eval):2:in `block in action_create_site'

**Comment by pbobov** [comment]
Did you have portal installed on that machine before?

Try to create portal site manually. Will you get the same error message ```Migration failed. null```?
