### ISSUE TITLE
Chef 13 Incompatibility

### ISSUE THREAD

**Issue by steveoh** [Esri/arcgis-cookbook#89]
When trying to install the arcgis-pro role with chef 13 I was unsuccessful.

```
NoMethodError
-------------
undefined method `platform' for #<Chef::Node::Attribute:0x000000099d4d98>
```
```
Recipe Compile Error in c:/chef/local-mode-cache/cache/cookbooks/chef_handler/attributes/default.rb
```

**Comment by pbobov** [comment]
Chef-client 13 is not currently supported by ArcGIS Chef cookbooks.

**Comment by mschoelen** [comment]
Update. The 3.2.0 release supports chef-client 13.

> Changes in 3.2.0 release
> - Support for ArcGIS Enterprise 10.6.
> - Support for ArcGIS Pro 2.1.
> - Support for Insights for ArcGIS 2.0/2.1.
> - Support for Chef-Client 13.
