### ISSUE TITLE
ArcGIS Pro 1.4 .NET Framework requirement

### ISSUE THREAD

**Issue by steveoh** [Esri/arcgis-cookbook#91]
arcgis pro 1.4 [requires 4.6.1](http://pro.arcgis.com/en/pro-app/get-started/arcgis-pro-system-requirements.htm#GUID-624723E7-DC18-438D-B66E-AA4B75CE9104)

The `ms_dotnet` recipe that is being used (version 2.4.0) only lists `4.5.2` as the newest item. 

It seems that `including_patches` on the `ms_dotnet` recipe does not fulfill that requirement.

Please update `ms_dotnet` to `3.2.0` in the release so we have access to [4.6.x](https://github.com/criteo-cookbooks/ms_dotnet/blob/master/libraries/package_helper.rb#L84-L88)

![image](https://user-images.githubusercontent.com/325813/26948886-34261682-4c55-11e7-9263-6f054afcc372.png)

Can we add a Berksfile so we can update the dependencies out of your release bands?

**Comment by steveoh** [comment]
After digging into this some more the `ms_dotnet` cookbook at version `3.2.1` has issues installing `4.6.1`. Something about [kb's being prerequisites and not patchs](https://github.com/criteo-cookbooks/ms_dotnet/issues/54)

**Comment by pbobov** [comment]
@steveoh Have you figured out how to install MS DotNet 4.6.x with chef? If you know a way, we can include the right cookbook in the next release of ArcGIS Chef cookbooks.

**Comment by steveoh** [comment]
I have not yet but I would be interested to take that on with you together since I'm so new to this. 

Is there any way we could update the source code of this cookbook to be more dev friendly? Eg updating the berksfile Etc

**Comment by steveoh** [comment]
@pbobov 4.0.0 was released. https://github.com/criteo-cookbooks/ms_dotnet/releases

I think you should consider updating to that cookbook.
