### ISSUE TITLE
Error while installing arcgis-desktop-> No such cookbook: limits

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-cookbook#92]
No such cookbook: limits

Please see screenshot below for reference

![image](https://user-images.githubusercontent.com/11682688/27007575-3642c696-4e0c-11e7-8ac1-c7b32671fa13.png)

**Comment by pbobov** [comment]
Chef client 13 is not yet supported by ArcGIS Chef cookbooks. Please use Chef client 12. Also make sure that 'limits' cookbook is present in C:\chef\cookbooks folder.
