### ISSUE TITLE
undefined method 'platform' in chef_handler

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-cookbook#93]
I am new to chef but it appears that the default.rb file in chef_handlers cookbook does not have windows as an option. Not sure why the arcgis-desktop cookbook is then using it and then failing. What am i missing?

![image](https://user-images.githubusercontent.com/11682688/27007614-96a6ce8c-4e0d-11e7-8ddb-09a49cb6945c.png)

**Comment by pbobov** [comment]
Chef client 13 is not yet supported by ArcGIS Chef cookbooks. Please use Chef client 12.
