### ISSUE TITLE
Modifying firewall ports

### ISSUE THREAD

**Issue by cadams84** [Esri/arcgis-cookbook#96]
I have noticed that if ArcGIS Server is installed with the attribute ""configure_windows_firewall": true,", two firewall rules are created:

ArcGIS Server	1098, 4000-4004, 6006, 6080, 6099, 6443	 
ArcGIS Server (GeoAnalytics)	2181, 2182, 2190, 7077, 56540-56545 

Two questions:

1. I will not be using GeoAnalytics so can I prevent this rule from being created when deploying ArcGISServer? 
2. Can firewall ports be modified?

**Comment by pbobov** [comment]
1. No. So far there is now such option. (In the future, "ArcGIS Server (GeoAnalytics)" rule configuration should be probably moved to enable_geoanalytics recipe.)

2. No. The firewall rules and ports are currently hardcoded. (In the future, the ports should configurable through attributes).

**Comment by cadams84** [comment]
Thanks. I've noticed that Portal also requires dynamic ports. Were the ranges in the web help left out because it is up to the network administrator to decide on the range? Chef opens 5701, 5702, 7080, 7443, 7005, 7099, 7199, 7120, 7220, 7654, but read that Portal could also require ports between 1024 and 5000 or between 49152 to 65535. 

"Portal for ArcGIS may also require the use of ephemeral, sometimes called dynamic, ports for intermachine communications. The ephemeral ports are often a range (typically between 1024 and 5000 or between 49152 to 65535, though system administrators may customize this range). You must ensure that your firewall allows intermachine communication on these specific ports and the ephemeral port range".

**Comment by pbobov** [comment]
Yes. I decided to be conservative about opening port ranges and leave opening 1024 - 5000 and 49152 - 65535 for admins to decide.

On Amazon Windows AMIs we open these ports for portal.
```
netsh advfirewall firewall add rule name="Allow_Portal_Ports" dir=in action=allow protocol=TCP localport="5701,5702,7080,7443,7005,7099,7199,7654,7120,7220,7320,57900,57800,57950,57975" description="Allows connections through all ports used by Portal". 
```

**Comment by cadams84** [comment]
Thanks for this additional information.
