### ISSUE TITLE
An unexpected error is keeping you from copying the file.

### ISSUE THREAD

**Issue by drkludge** [Esri/arcgis-cookbook#98]
I am having problems with the .zip files with the MS Windows 7.x  File Explorer archive extraction. I receive these random messages.  The errors appear to be on the .rb files.  I am guessing that will be a significant problem.  I have a Red Hat Linux server available.  I've also posted my work around.  unzip may be able to handle these files for some reason.

![image](https://user-images.githubusercontent.com/1669057/28191253-0fc3b6e6-67e4-11e7-888e-413bbeb63f78.png)

 1.)  wget https://github.com/Esri/arcgis-cookbook/releases/download/v3.1.0/arcgis-3.1.0-cookbooks.zip
 2.)  unzip arcgis-3.1.0-cookbooks.zip
 3.) sftp files back to the MS Windows computer.

**Comment by pkdavidson** [comment]
did you try 7-zip or winzip on the win box?
the archive downloaded and extracted no problem for me.
but I have winzip installed so not going through built in win7 extraction

**Comment by drkludge** [comment]
Yep! I have neither of those options.  I had to use File Explorer.
