### ISSUE TITLE
Server Admin Wants My New Install On D: Not C:

### ISSUE THREAD

**Issue by drkludge** [Esri/arcgis-cookbook#99]
[I watched an ESRI You Tube video on Chef.](https://youtu.be/0kIe_Ujb0VA).  Everything is going fine except that I am running into hard coded expectations.  My server admin wants to save the C: driver for the OS.  Hence, I have
- D:\chef for the ESRI scripts.
- D:\GIS\Apps\opscode is where the Chef installation is located.
- I expect to install all the ArcGIS server software to D:\GIS\Apps.
- I expect to install python in D:\python27

The 3.10 scripts start up just fine after all my configuration.  But Alas I finding messages such as `STDERR: '"C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe"' is not recognized as an internal or external command, operable program or batch file.`  I find a number of these configurations in the provided scripts, `ENV['ProgramW6432'] + '\\Common Files\\ArcGIS\\bin\\SoftwareAuthorization.exe'` using [this github search](https://github.com/Esri/arcgis-cookbook/search?utf8=%E2%9C%93&q=C%3A%5CProgram+Files%5CCommon+Files%5CArcGIS%5Cbin%5CSoftwareAuthorization.exe&type=).

Are there issues with the Chef scripts or do I need to go back to my SA and say ESRI cannot live without putting some software on C:?

I see a number of other open issues that used 13x version of Chef.  I am using Chef Client 12.21.3 as found on the quick links page if this repository.

**Comment by pbobov** [comment]
The path to server SoftwareAuthorization.exe utility could be specified by setting ```node['arcgis']['server']['authorization_tool']``` attribute. The default value of this attribute is ```ENV['ProgramW6432'] + '\\Common Files\\ArcGIS\\bin\\SoftwareAuthorization.exe'```.
